export const dashboardIntegracao = `
SELECT
  SISTEMAORIGEM AS sistemaOrigem,
  STATUSINTEGRACAO AS statusIntegracao,
  COUNT(*) AS total,
  CAST(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM AD_APONTAMENTOSCHECKLIST WITH (NOLOCK) WHERE ATIVO = 'S') AS DECIMAL(5,2)) AS percentual
FROM AD_APONTAMENTOSCHECKLIST WITH (NOLOCK)
WHERE ATIVO = 'S'
GROUP BY SISTEMAORIGEM, STATUSINTEGRACAO
ORDER BY SISTEMAORIGEM, STATUSINTEGRACAO
`;
