export const pendentesIntegracao = `
SELECT TOP @LIMIT
  C.CODAPONTAMENTO,
  C.CODVEICULO,
  C.PLACAVEICULO,
  C.DESCRGRUPO,
  C.DESCRPERGUNTA,
  C.DESCRESPOSTA,
  C.SISTEMAORIGEM,
  C.STATUSINTEGRACAO,
  C.DTRESPOSTA,
  C.URLRETORNO
FROM AD_APONTAMENTOSCHECKLIST C WITH (NOLOCK)
WHERE C.STATUSINTEGRACAO = 'PENDENTE'
  AND C.ATIVO = 'S'
ORDER BY C.DTRESPOSTA DESC
`;
