export const porApontamento = `
SELECT
  C.CODAPONTAMENTO,
  C.CODVEICULO,
  C.PLACAVEICULO,
  C.CODCHECKLIST,
  C.CODGRUPO,
  C.DESCRGRUPO,
  C.ORDEMGRUPO,
  C.CODPERGUNTA,
  C.DESCRPERGUNTA,
  C.TIPOPERGUNTA,
  C.ORDEMPERGUNTA,
  C.CODRESPOSTA,
  C.DESCRESPOSTA,
  C.DTRESPOSTA,
  C.SITUACAO,
  C.COMENTARIO,
  C.LATITUDE,
  C.LONGITUDE,
  C.SISTEMAORIGEM,
  C.STATUSINTEGRACAO
FROM AD_APONTAMENTOSCHECKLIST C WITH (NOLOCK)
WHERE C.CODAPONTAMENTO = @CODAPONTAMENTO
  AND C.ATIVO = 'S'
ORDER BY C.ORDEMGRUPO, C.ORDEMPERGUNTA
`;
