export const statusIntegracao = `
SELECT
  (SELECT COUNT(*) FROM AD_APONTAMENTOSCHECKLIST WITH (NOLOCK) WHERE ATIVO = 'S') AS totalChecklists,
  (SELECT COUNT(*) FROM AD_APONTAMENTOSCHECKLIST WITH (NOLOCK) WHERE ATIVO = 'S' AND STATUSINTEGRACAO = 'PENDENTE') AS pendentes,
  (SELECT COUNT(*) FROM AD_APONTAMENTOSCHECKLIST WITH (NOLOCK) WHERE ATIVO = 'S' AND STATUSINTEGRACAO = 'SINCRONIZADO') AS sincronizados,
  (SELECT COUNT(*) FROM AD_APONTAMENTOSCHECKLIST WITH (NOLOCK) WHERE ATIVO = 'S' AND STATUSINTEGRACAO = 'ERRO') AS erros
`;
