export const calendarioList = `
SELECT
    cal.NUCALENDARIO,
    cal.CODVEICULO,
    v.PLACA,
    CAST(v.MARCAMODELO AS VARCHAR(200)) AS MARCAMODELO,
    cal.CODPARC,
    CAST(ISNULL(p.RAZAOSOCIAL, '') AS VARCHAR(200)) AS PARCEIRO,
    cal.DHINIC,
    cal.DHFIN,
    cal.STATUS,
    cal.TIPO,
    CAST(ISNULL(cal.OBSERVACAO, '') AS VARCHAR(MAX)) AS OBSERVACAO,
    cal.CODEMP,
    cal.CODUSU,
    CAST(ISNULL(u.NOMEUSU, '') AS VARCHAR(200)) AS USUARIO
FROM SANKHYA.AD_CALENDARIOCOMERCIAL cal
LEFT JOIN SANKHYA.TGFVEI v ON v.CODVEICULO = cal.CODVEICULO
LEFT JOIN SANKHYA.TGFPAR p ON p.CODPARC = cal.CODPARC
LEFT JOIN SANKHYA.TSIUSU u ON u.CODUSU = cal.CODUSU
ORDER BY cal.DHINIC DESC
OFFSET @offset ROWS FETCH NEXT @limit ROWS ONLY
`;

export const calendarioCount = `
SELECT COUNT(*) AS total
FROM SANKHYA.AD_CALENDARIOCOMERCIAL cal
`;

export const calendarioById = `
SELECT
    cal.NUCALENDARIO,
    cal.CODVEICULO,
    v.PLACA,
    CAST(v.MARCAMODELO AS VARCHAR(200)) AS MARCAMODELO,
    cal.CODPARC,
    CAST(ISNULL(p.RAZAOSOCIAL, '') AS VARCHAR(200)) AS PARCEIRO,
    cal.DHINIC,
    cal.DHFIN,
    cal.STATUS,
    cal.TIPO,
    CAST(ISNULL(cal.OBSERVACAO, '') AS VARCHAR(MAX)) AS OBSERVACAO,
    cal.CODEMP,
    cal.CODUSU,
    CAST(ISNULL(u.NOMEUSU, '') AS VARCHAR(200)) AS USUARIO
FROM SANKHYA.AD_CALENDARIOCOMERCIAL cal
LEFT JOIN SANKHYA.TGFVEI v ON v.CODVEICULO = cal.CODVEICULO
LEFT JOIN SANKHYA.TGFPAR p ON p.CODPARC = cal.CODPARC
LEFT JOIN SANKHYA.TSIUSU u ON u.CODUSU = cal.CODUSU
WHERE cal.NUCALENDARIO = @nucalendario
`;

export const calendarioStats = `
SELECT
    COUNT(*) AS total,
    SUM(CASE WHEN cal.STATUS = 'A' THEN 1 ELSE 0 END) AS ativos,
    SUM(CASE WHEN cal.STATUS = 'F' THEN 1 ELSE 0 END) AS finalizados,
    SUM(CASE WHEN cal.STATUS = 'C' THEN 1 ELSE 0 END) AS cancelados,
    COUNT(DISTINCT cal.CODVEICULO) AS veiculos_distintos,
    COUNT(DISTINCT cal.CODPARC) AS parceiros_distintos
FROM SANKHYA.AD_CALENDARIOCOMERCIAL cal
`;

export const calendarioByVeiculo = `
SELECT
    cal.NUCALENDARIO,
    cal.CODVEICULO,
    cal.CODPARC,
    CAST(ISNULL(p.RAZAOSOCIAL, '') AS VARCHAR(200)) AS PARCEIRO,
    cal.DHINIC,
    cal.DHFIN,
    cal.STATUS,
    cal.TIPO,
    CAST(ISNULL(cal.OBSERVACAO, '') AS VARCHAR(MAX)) AS OBSERVACAO
FROM SANKHYA.AD_CALENDARIOCOMERCIAL cal
LEFT JOIN SANKHYA.TGFPAR p ON p.CODPARC = cal.CODPARC
WHERE cal.CODVEICULO = @codveiculo
ORDER BY cal.DHINIC DESC
`;
