export const cotacoesPendentes = `
SELECT
  COT.NUMCOTACAO,
  COT.SITUACAO,
  COT.DHINIC,
  USU.NOMEUSU AS COMPRADOR,
  COT.CODUSUREQ
FROM TGFCOT COT
LEFT JOIN TSIUSU USU ON USU.CODUSU = COT.CODUSUREQ
WHERE COT.NUMCOTACAO > 0
  AND COT.SITUACAO = 'A'
ORDER BY COT.DHINIC
`;
