export const requisicoesPendentesManutencao = `
SELECT TOP 500
  CAB.NUNOTA,
  PRO.DESCRPROD,
  ITE.CONTROLE,
  ITE.QTDNEG,
  ITE.QTDENTREGUE,
  CAB.AD_PRIORIDADE,
  CAB.DTNEG,
  VEI.PLACA AS APLICACAO,
  USU.NOMEUSU,
  CAB.AD_DTLIMITE AS DTLIMITE,
  CAB.CODTIPOPER,
  ITE.CODPROD,
  CAB.CODVEICULO,
  ITE.NUREM
FROM TGFCAB CAB WITH (NOLOCK)
LEFT JOIN TGFITE ITE ON ITE.NUNOTA = CAB.NUNOTA
LEFT JOIN TGFPRO PRO ON PRO.CODPROD = ITE.CODPROD
LEFT JOIN TGFVEI VEI ON VEI.CODVEICULO = CAB.CODVEICULO
LEFT JOIN TSIUSU USU ON USU.CODUSU = CAB.CODUSU
WHERE CAB.TIPMOV = 'Q'
  AND CAB.STATUSNOTA = 'L'
  AND CAB.CODTIPOPER = 57
  AND CAB.NUMCOTACAO IS NULL
ORDER BY CAB.AD_PRIORIDADE, CAB.NUNOTA DESC
`;
