export const requisicoesPendentesCompras = `
SELECT TOP 500
  CAB.NUNOTA,
  CAB.AD_PRIORIDADE,
  CAB.DTNEG,
  CAB.AD_DTLIMITE,
  CAB.CODTIPOPER,
  CAB.CODVEICULO,
  CAB.CODUSU
FROM TGFCAB CAB WITH (NOLOCK)
WHERE CAB.TIPMOV = 'Q'
  AND CAB.STATUSNOTA = 'L'
  AND CAB.CODTIPOPER = PLACEHOLDER_TIPOPER
  AND CAB.NUMCOTACAO IS NULL
ORDER BY CAB.AD_PRIORIDADE, CAB.NUNOTA DESC
`;

export const requisicaoItens = `
SELECT
  ITE.NUNOTA,
  ITE.CODPROD,
  ITE.QTDNEG,
  ITE.QTDENTREGUE,
  ITE.CONTROLE,
  ITE.NUREM
FROM TGFITE ITE
WHERE ITE.NUNOTA = PLACEHOLDER_NUNOTA
`;
