export const requisicoesPendentesCompras = `
SELECT TOP 50 CAB.NUNOTA, ITE.CODPROD, ITE.QTDNEG, ITE.QTDENTREGUE, PRO.DESCRPROD, VEI.PLACA, CAB.AD_PRIORIDADE, CAB.DTNEG, CAB.CODTIPOPER, CAB.CODVEICULO, ITE.CONTROLE, ITE.NUREM
FROM TGFCAB CAB WITH (NOLOCK)
LEFT JOIN TGFITE ITE ON ITE.NUNOTA = CAB.NUNOTA
LEFT JOIN TGFPRO PRO ON PRO.CODPROD = ITE.CODPROD
LEFT JOIN TGFVEI VEI ON VEI.CODVEICULO = CAB.CODVEICULO
WHERE CAB.TIPMOV = 'Q' AND CAB.STATUSNOTA = 'L' AND (CAB.CODTIPOPER = 502 OR CAB.CODTIPOPER = 504 OR CAB.CODTIPOPER = 506 OR CAB.CODTIPOPER = 507) AND CAB.NUMCOTACAO IS NULL
ORDER BY CAB.AD_PRIORIDADE, CAB.NUNOTA DESC
`;
