export const requisicoesPendentesManutencao = `
SELECT TOP 500
  CAB.NUNOTA,
  ITE.CODPROD,
  PRO.DESCRPROD,
  ITE.CONTROLE,
  ITE.QTDNEG,
  ITE.QTDENTREGUE,
  (ITE.QTDNEG - ITE.QTDENTREGUE) AS QTDPENDENTE,
  CAST(CAB.OBSERVACAO AS VARCHAR(500)) AS OBSERVACAO,
  CAB.AD_PRIORIDADE,
  CONVERT(VARCHAR(10), CAB.DTNEG, 103) AS DTNEG,
  CONVERT(VARCHAR(10), CAB.AD_DTLIMITE, 103) AS DTLIMITE,
  CONVERT(VARCHAR(19), CAB.DTNEG, 120) AS DTNEG_ISO,
  CONVERT(VARCHAR(19), CAB.AD_DTLIMITE, 120) AS DTLIMITE_ISO,
  CAB.CODVEICULO,
  CASE CAB.CODVEICULO WHEN 0 THEN 'Uso e Consumo' ELSE VEI.PLACA END AS APLICACAO,
  VEI.AD_TAG AS VEICULOTAG,
  CAST(VEI.MARCAMODELO AS VARCHAR(200)) AS MARCAMODELO,
  USU.NOMEUSU,
  CAB.CODTIPOPER
FROM TGFCAB CAB WITH (NOLOCK)
JOIN TGFITE ITE ON ITE.NUNOTA = CAB.NUNOTA
JOIN TGFPRO PRO ON PRO.CODPROD = ITE.CODPROD
LEFT JOIN TGFVEI VEI ON VEI.CODVEICULO = CAB.CODVEICULO
JOIN TSIUSU USU ON USU.CODUSU = COALESCE(CAB.CODUSUINC, CAB.CODUSU)
WHERE (ITE.QTDNEG - ITE.QTDENTREGUE) > 0
  AND CAB.TIPMOV = 'Q'
  AND CAB.STATUSNOTA = 'L'
  AND CAB.CODTIPOPER = 57
  AND CAB.NUMCOTACAO IS NULL
  AND ITE.NUREM IS NULL
  AND ITE.CODPROD NOT IN (5568, 6689, 8076)
ORDER BY CAB.AD_PRIORIDADE, CAB.NUNOTA DESC
`;
