export const requisicoesPendentesManutencao = `
SELECT TOP 500
  CAB.NUNOTA,
  CAB.AD_PRIORIDADE,
  CAB.DTNEG,
  CAB.AD_DTLIMITE,
  CAB.CODTIPOPER,
  CAB.CODVEICULO,
  CAB.CODUSU,
  CAB.NUMCOTACAO
FROM TGFCAB CAB WITH (NOLOCK)
WHERE CAB.TIPMOV = 'Q'
  AND CAB.STATUSNOTA = 'L'
  AND CAB.CODTIPOPER = 57
  AND CAB.NUMCOTACAO IS NULL
ORDER BY CAB.AD_PRIORIDADE, CAB.NUNOTA DESC
`;
