export const countReqCompras = `
SELECT COUNT(*) AS total
FROM TGFCAB CAB
WHERE CAB.TIPMOV = 'Q'
  AND CAB.STATUSNOTA = 'L'
  AND (CAB.CODTIPOPER = 502 OR CAB.CODTIPOPER = 504 OR CAB.CODTIPOPER = 506 OR CAB.CODTIPOPER = 507)
  AND CAB.NUMCOTACAO IS NULL
`;

export const countReqManut = `
SELECT COUNT(*) AS total
FROM TGFCAB CAB
WHERE CAB.TIPMOV = 'Q'
  AND CAB.STATUSNOTA = 'L'
  AND CAB.CODTIPOPER = 57
  AND CAB.NUMCOTACAO IS NULL
`;

export const countCotacoes = `
SELECT COUNT(*) AS total
FROM TGFCOT COT
WHERE COT.NUMCOTACAO > 0
  AND COT.SITUACAO = 'A'
`;
