export const getLocaisHierarquia = `
SELECT TOP 600
  loc.CODLOCAL,
  RTRIM(CAST(loc.DESCRLOCAL AS VARCHAR(100))) AS DESCRLOCAL,
  loc.CODLOCALPAI,
  loc.GRAU,
  loc.ATIVO,
  loc.ANALITICO,
  loc.AD_CODUSU,
  usu.CODPARC AS USU_CODPARC,
  RTRIM(CAST(ISNULL(usu.NOMEUSU, '') AS VARCHAR(100))) AS NOMEUSU
FROM TGFLOC loc
LEFT JOIN TSIUSU usu ON usu.CODUSU = loc.AD_CODUSU
WHERE loc.ATIVO = 'S'
ORDER BY loc.GRAU, loc.CODLOCAL
`;

export const getEstoquePorLocal = `
SELECT TOP 200
  e.CODPROD,
  RTRIM(CAST(p.DESCRPROD AS VARCHAR(100))) AS DESCRPROD,
  RTRIM(CAST(ISNULL(e.CONTROLE, '') AS VARCHAR(50))) AS CONTROLE,
  e.ESTOQUE,
  ISNULL(e.RESERVADO, 0) AS RESERVADO,
  ISNULL(e.ESTMIN, 0) AS ESTMIN,
  ISNULL(e.ESTMAX, 0) AS ESTMAX,
  p.CODGRUPOPROD,
  RTRIM(CAST(ISNULL(g.DESCRGRUPOPROD, '') AS VARCHAR(100))) AS DESCRGRUPOPROD,
  p.ATIVO AS PRODATIVO,
  RTRIM(CAST(ISNULL(p.COMPLDESC, '') AS VARCHAR(200))) AS COMPLDESC,
  RTRIM(CAST(ISNULL(p.LOCALIZACAO, '') AS VARCHAR(100))) AS LOCALIZACAO,
  RTRIM(CAST(ISNULL(p.USOPROD, '') AS VARCHAR(5))) AS USOPROD
FROM TGFEST e
LEFT JOIN TGFPRO p ON e.CODPROD = p.CODPROD
LEFT JOIN TGFGRU g ON p.CODGRUPOPROD = g.CODGRUPOPROD
WHERE e.CODLOCAL = @CODLOCAL
  AND e.ESTOQUE > 0
ORDER BY p.DESCRPROD, e.CONTROLE
`;
