export const getUsuarios = `
SELECT * FROM (
  SELECT
    U.CODUSU,
    RTRIM(U.NOMEUSU) AS NOMEUSU,
    U.CODGRUPO,
    RTRIM(G.NOMEGRUPO) AS NOMEGRUPO,
    (SELECT COUNT(*) FROM TDDPER P
     WHERE P.CODUSU = U.CODUSU AND P.CODGRUPO = 0) AS qtdDiretas,
    ROW_NUMBER() OVER (ORDER BY U.NOMEUSU) AS RowNum
  FROM TSIUSU U
  LEFT JOIN TSIGRU G ON U.CODGRUPO = G.CODGRUPO
  WHERE U.CODUSU IN (SELECT DISTINCT CODUSU FROM TDDPER WHERE CODUSU > 0)
  @whereClause
) AS T
WHERE RowNum > @offset AND RowNum <= (@offset + @limit)
`;

export const countUsuarios = `
SELECT COUNT(DISTINCT U.CODUSU) AS total
FROM TSIUSU U
WHERE U.CODUSU IN (SELECT DISTINCT CODUSU FROM TDDPER WHERE CODUSU > 0)
@whereClause
`;

export const getUsuarioDiretas = `
SELECT P.IDACESSO, RTRIM(P.ACESSO) AS ACESSO
FROM TDDPER P
WHERE P.CODUSU = @codusu AND P.CODGRUPO = 0
ORDER BY P.IDACESSO
`;

export const getUsuarioHerdadas = `
SELECT P.IDACESSO, RTRIM(P.ACESSO) AS ACESSO,
  P.CODGRUPO, RTRIM(G.NOMEGRUPO) AS NOMEGRUPO
FROM TDDPER P
INNER JOIN TSIGRU G ON P.CODGRUPO = G.CODGRUPO
WHERE P.CODGRUPO = (SELECT U.CODGRUPO FROM TSIUSU U WHERE U.CODUSU = @codusu)
  AND P.CODUSU = 0 AND P.CODGRUPO > 0
ORDER BY P.IDACESSO
`;

export const getConflitos = `
SELECT
  up.IDACESSO,
  up.CODUSU,
  RTRIM(u.NOMEUSU) AS NOMEUSU,
  u.CODGRUPO,
  RTRIM(g.NOMEGRUPO) AS NOMEGRUPO,
  RTRIM(up.ACESSO) AS acessoUsuario,
  RTRIM(gp.ACESSO) AS acessoGrupo
FROM TDDPER up
INNER JOIN TSIUSU u ON up.CODUSU = u.CODUSU
INNER JOIN TSIGRU g ON u.CODGRUPO = g.CODGRUPO
INNER JOIN TDDPER gp ON up.IDACESSO = gp.IDACESSO
  AND gp.CODUSU = 0 AND gp.CODGRUPO = u.CODGRUPO
WHERE up.CODUSU > 0 AND up.CODGRUPO = 0
  AND up.ACESSO <> gp.ACESSO
ORDER BY up.IDACESSO
`;
