export const getGrupos = `
SELECT
  G.CODGRUPO,
  RTRIM(G.NOMEGRUPO) AS NOMEGRUPO,
  (SELECT COUNT(*) FROM TSIUSU U WHERE U.CODGRUPO = G.CODGRUPO) AS qtdMembros,
  (SELECT COUNT(DISTINCT P.IDACESSO) FROM TDDPER P
   WHERE P.CODGRUPO = G.CODGRUPO AND P.CODUSU = 0) AS qtdTelas
FROM TSIGRU G
ORDER BY G.NOMEGRUPO
`;

export const getGrupoMembros = `
SELECT U.CODUSU, RTRIM(U.NOMEUSU) AS NOMEUSU, U.DTLIMACESSO
FROM TSIUSU U
WHERE U.CODGRUPO = @codgrupo
ORDER BY U.NOMEUSU
`;

export const getGrupoTelas = `
SELECT P.IDACESSO, RTRIM(P.ACESSO) AS ACESSO
FROM TDDPER P
WHERE P.CODGRUPO = @codgrupo AND P.CODUSU = 0
ORDER BY P.IDACESSO
`;
