export const agendamentosFuturos = `
SELECT
    v.CODVEICULO,
    v.PLACA,
    CAST(v.MARCAMODELO AS VARCHAR(200)) AS Nome,
    CAST(ISNULL(v.AD_TIPOEQPTO, v.CATEGORIA) AS VARCHAR(100)) AS Categoria,
    (SELECT TOP 1 i.DHPREVISTA
     FROM SANKHYA.TCSOSE o
     INNER JOIN SANKHYA.TCSITE i ON i.NUMOS = o.NUMOS
     WHERE i.AD_CODVEICULO = v.CODVEICULO
     AND o.SITUACAO = 'P' AND o.DTFECHAMENTO IS NULL AND i.INICEXEC IS NULL
     ORDER BY i.DHPREVISTA ASC
    ) AS ProximoAgendamento,
    (SELECT TOP 1 o.NUMOS
     FROM SANKHYA.TCSOSE o
     INNER JOIN SANKHYA.TCSITE i ON i.NUMOS = o.NUMOS
     WHERE i.AD_CODVEICULO = v.CODVEICULO
     AND o.SITUACAO = 'P' AND o.DTFECHAMENTO IS NULL AND i.INICEXEC IS NULL
     ORDER BY i.DHPREVISTA ASC
    ) AS NumOSAgendada,
    (SELECT TOP 1 CAST(p.RAZAOSOCIAL AS VARCHAR(200))
     FROM SANKHYA.TCSOSE o
     INNER JOIN SANKHYA.TCSITE i ON i.NUMOS = o.NUMOS
     INNER JOIN SANKHYA.TGFPAR p ON p.CODPARC = o.CODPARC
     WHERE i.AD_CODVEICULO = v.CODVEICULO
     AND o.SITUACAO = 'P' AND o.DTFECHAMENTO IS NULL AND i.INICEXEC IS NULL
     ORDER BY i.DHPREVISTA ASC
    ) AS ClienteAgendado
FROM SANKHYA.TGFVEI v
WHERE v.ATIVO = 'S'
AND EXISTS (
    SELECT 1 FROM SANKHYA.TCSITE i
    INNER JOIN SANKHYA.TCSOSE o ON o.NUMOS = i.NUMOS
    WHERE i.AD_CODVEICULO = v.CODVEICULO
    AND o.SITUACAO = 'P' AND o.DTFECHAMENTO IS NULL AND i.INICEXEC IS NULL
)
ORDER BY ProximoAgendamento ASC
`;
