export const auditoria = `
SELECT * FROM (
  SELECT
    'MULTIPLAS_OS_COMERCIAIS' AS tipoProblema,
    i.AD_CODVEICULO AS codveiculo,
    v.PLACA AS placa,
    CAST(v.MARCAMODELO AS VARCHAR(200)) AS marcamodelo,
    COUNT(DISTINCT o.NUMOS) AS qtdOS,
    (SELECT TOP 1 CAST(o2.NUMOS AS VARCHAR)
     FROM SANKHYA.TCSITE i2
     INNER JOIN SANKHYA.TCSOSE o2 ON o2.NUMOS = i2.NUMOS
     WHERE i2.AD_CODVEICULO = i.AD_CODVEICULO
     AND o2.DTFECHAMENTO IS NULL AND o2.SITUACAO = 'P'
    ) AS numsOS,
    0 AS diasAberta,
    CASE WHEN COUNT(DISTINCT o.NUMOS) > 3 THEN 'CRITICO'
         WHEN COUNT(DISTINCT o.NUMOS) > 2 THEN 'ALTO'
         ELSE 'ATENCAO'
    END AS severidade
  FROM SANKHYA.TCSITE i
  INNER JOIN SANKHYA.TCSOSE o ON o.NUMOS = i.NUMOS
  INNER JOIN SANKHYA.TGFVEI v ON v.CODVEICULO = i.AD_CODVEICULO
  WHERE o.DTFECHAMENTO IS NULL AND o.SITUACAO = 'P'
    AND i.AD_CODVEICULO IS NOT NULL
  GROUP BY i.AD_CODVEICULO, v.PLACA, v.MARCAMODELO
  HAVING COUNT(DISTINCT o.NUMOS) > 1

  UNION ALL

  SELECT
    'MANUTENCAO_ANTIGA' AS tipoProblema,
    m.CODVEICULO AS codveiculo,
    v.PLACA AS placa,
    CAST(v.MARCAMODELO AS VARCHAR(200)) AS marcamodelo,
    1 AS qtdOS,
    CAST(m.NUOS AS VARCHAR) AS numsOS,
    DATEDIFF(DAY, m.DATAINI, GETDATE()) AS diasAberta,
    CASE WHEN DATEDIFF(DAY, m.DATAINI, GETDATE()) > 90 THEN 'CRITICO'
         WHEN DATEDIFF(DAY, m.DATAINI, GETDATE()) > 60 THEN 'ALTO'
         ELSE 'ATENCAO'
    END AS severidade
  FROM SANKHYA.TCFOSCAB m
  INNER JOIN SANKHYA.TGFVEI v ON v.CODVEICULO = m.CODVEICULO
  WHERE m.DATAFIN IS NULL
    AND DATEDIFF(DAY, m.DATAINI, GETDATE()) > 30
) AS auditoria
ORDER BY
  CASE severidade WHEN 'CRITICO' THEN 0 WHEN 'ALTO' THEN 1 ELSE 2 END,
  diasAberta DESC
`;
