export const contratos = `
SELECT
  c.ID AS id,
  c.CODVEICULO AS codveiculo,
  c.CODPARC AS codparc,
  CAST(ISNULL(p.NOMEPARC, '') AS VARCHAR(200)) AS nomeParc,
  CONVERT(VARCHAR, c.DHINIC, 120) AS dhinic,
  CONVERT(VARCHAR, c.DHFIN, 120) AS dhfin,
  CAST(ISNULL(c.OBS, '') AS VARCHAR(500)) AS obs,
  CASE
    WHEN GETDATE() >= c.DHINIC AND GETDATE() <= c.DHFIN THEN 'ATIVO'
    WHEN c.DHINIC > GETDATE() THEN 'FUTURO'
    ELSE 'ENCERRADO'
  END AS statusContrato,
  CASE
    WHEN GETDATE() >= c.DHINIC AND GETDATE() <= c.DHFIN
      THEN DATEDIFF(DAY, GETDATE(), c.DHFIN)
    WHEN c.DHINIC > GETDATE()
      THEN DATEDIFF(DAY, GETDATE(), c.DHINIC)
    ELSE NULL
  END AS diasRestantes
FROM SANKHYA.AD_CONTRATOS c
LEFT JOIN SANKHYA.TGFPAR p ON p.CODPARC = c.CODPARC
WHERE c.CODVEICULO = @codveiculo
ORDER BY c.DHINIC DESC
`;
