export const estatisticasManutencao = `
SELECT
  COUNT(*) AS totalAtivas,
  SUM(CASE WHEN m.STATUS = 'A' THEN 1 ELSE 0 END) AS abertas,
  SUM(CASE WHEN m.STATUS = 'E' THEN 1 ELSE 0 END) AS emExecucao,
  SUM(CASE WHEN m.MANUTENCAO = 'C' THEN 1 ELSE 0 END) AS corretivas,
  SUM(CASE WHEN m.MANUTENCAO = 'P' THEN 1 ELSE 0 END) AS preventivas,
  SUM(CASE WHEN m.AD_BLOQUEIOS = 'S' THEN 1 ELSE 0 END) AS comBloqueio,
  SUM(CASE WHEN m.AD_STATUSGIG IS NULL OR m.AD_STATUSGIG NOT IN ('AN', 'SN') THEN 1 ELSE 0 END) AS impeditivas,
  SUM(CASE WHEN m.AD_STATUSGIG IN ('AN', 'SN') THEN 1 ELSE 0 END) AS naoImpeditivas,
  SUM(CASE WHEN m.PREVISAO < GETDATE() THEN 1 ELSE 0 END) AS atrasadas,
  ISNULL(AVG(DATEDIFF(DAY, m.DATAINI, GETDATE())), 0) AS mediaDias
FROM SANKHYA.TCFOSCAB m
WHERE m.DATAFIN IS NULL
  AND m.CODVEICULO IS NOT NULL
`;
