export const monitoramento = `
SELECT
  v.CODVEICULO AS codveiculo,
  v.PLACA AS placa,
  CAST(v.MARCAMODELO AS VARCHAR(200)) AS marcamodelo,
  CAST(ISNULL(v.AD_TIPOEQPTO, v.CATEGORIA) AS VARCHAR(100)) AS categoria,
  CAST(ISNULL(v.AD_TAG, '') AS VARCHAR(100)) AS tag,
  v.KMACUM AS kmacum,
  CASE
    WHEN EXISTS (
      SELECT 1 FROM SANKHYA.TCFOSCAB m
      WHERE m.CODVEICULO = v.CODVEICULO
      AND m.DATAFIN IS NULL AND m.AD_BLOQUEIOS = 'S'
    ) THEN 'BLOQUEIO_COMERCIAL'
    WHEN v.BLOQUEADO = 'S' OR v.ATIVO = 'N' THEN 'PARADO'
    WHEN EXISTS (
      SELECT 1 FROM SANKHYA.TCFOSCAB m
      WHERE m.CODVEICULO = v.CODVEICULO
      AND m.STATUS = 'E' AND m.DATAFIN IS NULL
      AND (m.AD_STATUSGIG IS NULL OR m.AD_STATUSGIG NOT IN ('AN', 'SN'))
    ) THEN 'MANUTENCAO'
    WHEN EXISTS (
      SELECT 1 FROM SANKHYA.TCFOSCAB m
      WHERE m.CODVEICULO = v.CODVEICULO
      AND m.STATUS = 'A' AND m.DATAFIN IS NULL
      AND m.MANUTENCAO != 'P'
      AND (m.AD_STATUSGIG IS NULL OR m.AD_STATUSGIG NOT IN ('AN', 'SN'))
    ) THEN 'AGUARDANDO_MANUTENCAO'
    WHEN EXISTS (
      SELECT 1 FROM SANKHYA.AD_CONTRATOS c
      WHERE c.CODVEICULO = v.CODVEICULO
      AND GETDATE() >= c.DHINIC AND GETDATE() <= c.DHFIN
    ) THEN 'ALUGADO_CONTRATO'
    WHEN EXISTS (
      SELECT 1 FROM SANKHYA.TCSITE i
      INNER JOIN SANKHYA.TCSOSE o ON o.NUMOS = i.NUMOS
      WHERE i.AD_CODVEICULO = v.CODVEICULO
      AND o.SITUACAO = 'P' AND o.DTFECHAMENTO IS NULL
      AND (
        (i.INICEXEC IS NOT NULL AND i.TERMEXEC IS NULL)
        OR (i.DHPREVISTA <= GETDATE() AND i.TERMEXEC IS NULL)
      )
    ) THEN 'EM_USO'
    WHEN EXISTS (
      SELECT 1 FROM SANKHYA.AD_CONTRATOS c
      WHERE c.CODVEICULO = v.CODVEICULO AND c.DHINIC > GETDATE()
    ) THEN 'RESERVADO_CONTRATO'
    WHEN EXISTS (
      SELECT 1 FROM SANKHYA.TCSITE i
      INNER JOIN SANKHYA.TCSOSE o ON o.NUMOS = i.NUMOS
      WHERE i.AD_CODVEICULO = v.CODVEICULO
      AND o.SITUACAO = 'P' AND o.DTFECHAMENTO IS NULL
      AND i.DHPREVISTA > GETDATE() AND i.INICEXEC IS NULL
    ) THEN 'AGENDADO'
    ELSE 'LIVRE'
  END AS status,
  osAtiva.NUOS AS osNuos,
  osAtiva.MANUTENCAO AS osTipo,
  CONVERT(VARCHAR, osAtiva.DTABERTURA, 120) AS osDtAbertura,
  CONVERT(VARCHAR, osAtiva.PREVISAO, 120) AS osPrevisao,
  CAST(parcOs.NOMEPARC AS VARCHAR(200)) AS osParceiro,
  CONVERT(VARCHAR, osAtiva.DATAINI, 120) AS osDataIni,
  ISNULL(metricas.totalOsAno, 0) AS totalOsAno,
  ISNULL(metricas.corretivasAno, 0) AS corretivasAno,
  ISNULL(metricas.preventivasAno, 0) AS preventivasAno,
  CONVERT(VARCHAR, ultimaOs.DATAFIN, 120) AS ultimaOsFinalizada,
  alerta.tipo AS alertaTipo,
  alerta.mensagem AS alertaMensagem,
  alerta.diasAtraso AS alertaDias
FROM SANKHYA.TGFVEI v
LEFT JOIN (
  SELECT m.CODVEICULO, m.NUOS, m.MANUTENCAO, m.DTABERTURA, m.PREVISAO, m.CODPARC, m.DATAINI,
    ROW_NUMBER() OVER (PARTITION BY m.CODVEICULO ORDER BY m.DTABERTURA DESC) AS rn
  FROM SANKHYA.TCFOSCAB m
  WHERE m.DATAFIN IS NULL AND m.STATUS IN ('A', 'E')
    AND (m.AD_STATUSGIG IS NULL OR m.AD_STATUSGIG NOT IN ('AN', 'SN'))
) osAtiva ON osAtiva.CODVEICULO = v.CODVEICULO AND osAtiva.rn = 1
LEFT JOIN SANKHYA.TGFPAR parcOs ON parcOs.CODPARC = osAtiva.CODPARC
LEFT JOIN (
  SELECT
    CODVEICULO,
    COUNT(*) AS totalOsAno,
    SUM(CASE WHEN MANUTENCAO = 'C' THEN 1 ELSE 0 END) AS corretivasAno,
    SUM(CASE WHEN MANUTENCAO = 'P' THEN 1 ELSE 0 END) AS preventivasAno
  FROM SANKHYA.TCFOSCAB
  WHERE YEAR(DTABERTURA) = YEAR(GETDATE())
  GROUP BY CODVEICULO
) metricas ON metricas.CODVEICULO = v.CODVEICULO
LEFT JOIN (
  SELECT m.CODVEICULO, m.DATAFIN,
    ROW_NUMBER() OVER (PARTITION BY m.CODVEICULO ORDER BY m.DATAFIN DESC) AS rn
  FROM SANKHYA.TCFOSCAB m
  WHERE m.DATAFIN IS NOT NULL
) ultimaOs ON ultimaOs.CODVEICULO = v.CODVEICULO AND ultimaOs.rn = 1
LEFT JOIN (
  SELECT
    v2.CODVEICULO,
    CASE
      WHEN m2.AD_BLOQUEIOS = 'S' THEN 'BLOQUEIO'
      WHEN m2.PREVISAO < GETDATE() THEN 'ATRASADA'
      WHEN m2.PREVISAO <= DATEADD(DAY, 7, GETDATE()) THEN 'PREVENTIVA_PROXIMA'
      ELSE NULL
    END AS tipo,
    CASE
      WHEN m2.AD_BLOQUEIOS = 'S' THEN 'Bloqueio comercial ativo'
      WHEN m2.PREVISAO < GETDATE() THEN 'Manutencao atrasada'
      WHEN m2.PREVISAO <= DATEADD(DAY, 7, GETDATE()) THEN 'Preventiva proxima'
      ELSE NULL
    END AS mensagem,
    CASE
      WHEN m2.AD_BLOQUEIOS = 'S' THEN DATEDIFF(DAY, m2.DATAINI, GETDATE())
      WHEN m2.PREVISAO < GETDATE() THEN DATEDIFF(DAY, m2.PREVISAO, GETDATE())
      ELSE NULL
    END AS diasAtraso,
    ROW_NUMBER() OVER (PARTITION BY v2.CODVEICULO ORDER BY
      CASE
        WHEN m2.AD_BLOQUEIOS = 'S' THEN 0
        WHEN m2.PREVISAO < GETDATE() THEN 1
        ELSE 2
      END
    ) AS rn
  FROM SANKHYA.TGFVEI v2
  INNER JOIN SANKHYA.TCFOSCAB m2 ON m2.CODVEICULO = v2.CODVEICULO
  WHERE m2.DATAFIN IS NULL
    AND (m2.AD_BLOQUEIOS = 'S' OR m2.PREVISAO <= DATEADD(DAY, 7, GETDATE()))
) alerta ON alerta.CODVEICULO = v.CODVEICULO AND alerta.rn = 1
WHERE v.ATIVO = 'S' AND ISNULL(v.AD_EXIBEDASH, 'N') = 'S'
ORDER BY
  CASE
    WHEN EXISTS (SELECT 1 FROM SANKHYA.TCFOSCAB m WHERE m.CODVEICULO = v.CODVEICULO AND m.DATAFIN IS NULL AND m.AD_BLOQUEIOS = 'S') THEN 0
    WHEN EXISTS (SELECT 1 FROM SANKHYA.TCFOSCAB m WHERE m.CODVEICULO = v.CODVEICULO AND m.DATAFIN IS NULL AND m.PREVISAO < GETDATE()) THEN 1
    ELSE 2
  END,
  v.PLACA
`;
