export const monitoramentoStats = `
SELECT
  COUNT(*) AS total,
  SUM(CASE WHEN status = 'LIVRE' THEN 1 ELSE 0 END) AS livres,
  SUM(CASE WHEN status = 'EM_USO' THEN 1 ELSE 0 END) AS emUso,
  SUM(CASE WHEN status = 'MANUTENCAO' THEN 1 ELSE 0 END) AS manutencao,
  SUM(CASE WHEN status = 'AGUARDANDO_MANUTENCAO' THEN 1 ELSE 0 END) AS aguardandoManutencao,
  SUM(CASE WHEN status = 'BLOQUEIO_COMERCIAL' THEN 1 ELSE 0 END) AS bloqueioComercial,
  SUM(CASE WHEN status = 'PARADO' THEN 1 ELSE 0 END) AS parado,
  SUM(CASE WHEN status = 'ALUGADO_CONTRATO' THEN 1 ELSE 0 END) AS alugadoContrato,
  SUM(CASE WHEN status = 'RESERVADO_CONTRATO' THEN 1 ELSE 0 END) AS reservadoContrato,
  SUM(CASE WHEN status = 'AGENDADO' THEN 1 ELSE 0 END) AS agendado,
  SUM(CASE WHEN alertaTipo IS NOT NULL THEN 1 ELSE 0 END) AS comAlerta
FROM (
  SELECT
    v.CODVEICULO,
    CASE
      WHEN EXISTS (
        SELECT 1 FROM SANKHYA.TCFOSCAB m
        WHERE m.CODVEICULO = v.CODVEICULO
        AND m.DATAFIN IS NULL AND m.AD_BLOQUEIOS = 'S'
      ) THEN 'BLOQUEIO_COMERCIAL'
      WHEN v.BLOQUEADO = 'S' OR v.ATIVO = 'N' THEN 'PARADO'
      WHEN EXISTS (
        SELECT 1 FROM SANKHYA.TCFOSCAB m
        WHERE m.CODVEICULO = v.CODVEICULO
        AND m.STATUS = 'E' AND m.DATAFIN IS NULL
        AND (m.AD_STATUSGIG IS NULL OR m.AD_STATUSGIG NOT IN ('AN', 'SN'))
      ) THEN 'MANUTENCAO'
      WHEN EXISTS (
        SELECT 1 FROM SANKHYA.TCFOSCAB m
        WHERE m.CODVEICULO = v.CODVEICULO
        AND m.STATUS = 'A' AND m.DATAFIN IS NULL
        AND m.MANUTENCAO != 'P'
        AND (m.AD_STATUSGIG IS NULL OR m.AD_STATUSGIG NOT IN ('AN', 'SN'))
      ) THEN 'AGUARDANDO_MANUTENCAO'
      WHEN EXISTS (
        SELECT 1 FROM SANKHYA.AD_CONTRATOS c
        WHERE c.CODVEICULO = v.CODVEICULO
        AND GETDATE() >= c.DHINIC AND GETDATE() <= c.DHFIN
      ) THEN 'ALUGADO_CONTRATO'
      WHEN EXISTS (
        SELECT 1 FROM SANKHYA.TCSITE i
        INNER JOIN SANKHYA.TCSOSE o ON o.NUMOS = i.NUMOS
        WHERE i.AD_CODVEICULO = v.CODVEICULO
        AND o.SITUACAO = 'P' AND o.DTFECHAMENTO IS NULL
        AND (
          (i.INICEXEC IS NOT NULL AND i.TERMEXEC IS NULL)
          OR (i.DHPREVISTA <= GETDATE() AND i.TERMEXEC IS NULL)
        )
      ) THEN 'EM_USO'
      WHEN EXISTS (
        SELECT 1 FROM SANKHYA.AD_CONTRATOS c
        WHERE c.CODVEICULO = v.CODVEICULO AND c.DHINIC > GETDATE()
      ) THEN 'RESERVADO_CONTRATO'
      WHEN EXISTS (
        SELECT 1 FROM SANKHYA.TCSITE i
        INNER JOIN SANKHYA.TCSOSE o ON o.NUMOS = i.NUMOS
        WHERE i.AD_CODVEICULO = v.CODVEICULO
        AND o.SITUACAO = 'P' AND o.DTFECHAMENTO IS NULL
        AND i.DHPREVISTA > GETDATE() AND i.INICEXEC IS NULL
      ) THEN 'AGENDADO'
      ELSE 'LIVRE'
    END AS status,
    CASE
      WHEN EXISTS (
        SELECT 1 FROM SANKHYA.TCFOSCAB m
        WHERE m.CODVEICULO = v.CODVEICULO AND m.DATAFIN IS NULL
        AND (m.AD_BLOQUEIOS = 'S' OR m.PREVISAO <= DATEADD(DAY, 7, GETDATE()))
      ) THEN 'ALERTA'
      ELSE NULL
    END AS alertaTipo
  FROM SANKHYA.TGFVEI v
  WHERE v.ATIVO = 'S' AND ISNULL(v.AD_EXIBEDASH, 'N') = 'S'
) AS subq
`;
