export const osComerciais = `
SELECT
  o.NUMOS AS numos,
  o.SITUACAO AS situacao,
  o.CODPARC AS codparc,
  CAST(ISNULL(p.NOMEPARC, '') AS VARCHAR(200)) AS nomeParc,
  CONVERT(VARCHAR, o.DHCHAMADA, 120) AS dtabertura,
  CONVERT(VARCHAR, o.DTFECHAMENTO, 120) AS dtfechamento,
  COUNT(i.NUMITEM) AS qtdDiarias,
  CONVERT(VARCHAR, MIN(i.DHPREVISTA), 120) AS dhPrevistaIni,
  CONVERT(VARCHAR, MAX(i.DHPREVISTA), 120) AS dhPrevistaFim,
  CONVERT(VARCHAR, MIN(i.INICEXEC), 120) AS inicexec,
  CONVERT(VARCHAR, MAX(i.TERMEXEC), 120) AS termexec,
  MAX(CAST(ISNULL(i.AD_OBS_OSITE, '') AS VARCHAR(500))) AS localExecucao,
  MAX(CAST(ISNULL(usu.NOMEUSU, '') AS VARCHAR(200))) AS operadorNome,
  MAX(usu.CODPARC) AS codparcOperador,
  MAX(parcOp.TIPPESSOA) AS tippessoaOperador
FROM SANKHYA.TCSITE i
INNER JOIN SANKHYA.TCSOSE o ON o.NUMOS = i.NUMOS
LEFT JOIN SANKHYA.TGFPAR p ON p.CODPARC = o.CODPARC
LEFT JOIN SANKHYA.TSIUSU usu ON usu.CODUSU = i.CODUSU
LEFT JOIN SANKHYA.TGFPAR parcOp ON parcOp.CODPARC = usu.CODPARC
WHERE i.AD_CODVEICULO = @codveiculo
GROUP BY o.NUMOS, o.SITUACAO, o.CODPARC, p.NOMEPARC,
  o.DHCHAMADA, o.DTFECHAMENTO
ORDER BY o.DHCHAMADA DESC
`;
