export const painel = `
SELECT
  v.CODVEICULO AS codveiculo,
  v.PLACA AS placa,
  CAST(v.MARCAMODELO AS VARCHAR(200)) AS marcamodelo,
  CAST(ISNULL(v.AD_TIPOEQPTO, v.CATEGORIA) AS VARCHAR(100)) AS categoria,
  CAST(ISNULL(v.AD_FABRICANTE, '') AS VARCHAR(100)) AS fabricante,
  CAST(ISNULL(v.AD_CAPACIDADE, '') AS VARCHAR(100)) AS capacidade,
  v.KMACUM AS kmacum,
  CAST(ISNULL(v.AD_TAG, '') AS VARCHAR(100)) AS tag,
  CAST(ISNULL(mot.NOMEPARC, '') AS VARCHAR(200)) AS motoristaNome,
  CASE
    WHEN EXISTS (
      SELECT 1 FROM SANKHYA.TCFOSCAB m
      WHERE m.CODVEICULO = v.CODVEICULO
      AND m.DATAFIN IS NULL AND m.AD_BLOQUEIOS = 'S'
    ) THEN 'BLOQUEIO_COMERCIAL'
    WHEN v.BLOQUEADO = 'S' OR v.ATIVO = 'N' THEN 'PARADO'
    WHEN EXISTS (
      SELECT 1 FROM SANKHYA.TCFOSCAB m
      WHERE m.CODVEICULO = v.CODVEICULO
      AND m.STATUS = 'E' AND m.DATAFIN IS NULL
      AND (m.AD_STATUSGIG IS NULL OR m.AD_STATUSGIG NOT IN ('AN', 'SN'))
    ) THEN 'MANUTENCAO'
    WHEN EXISTS (
      SELECT 1 FROM SANKHYA.TCFOSCAB m
      WHERE m.CODVEICULO = v.CODVEICULO
      AND m.STATUS = 'A' AND m.DATAFIN IS NULL
      AND m.MANUTENCAO != 'P'
      AND (m.AD_STATUSGIG IS NULL OR m.AD_STATUSGIG NOT IN ('AN', 'SN'))
    ) THEN 'AGUARDANDO_MANUTENCAO'
    WHEN EXISTS (
      SELECT 1 FROM SANKHYA.AD_CONTRATOS c
      WHERE c.CODVEICULO = v.CODVEICULO
      AND GETDATE() >= c.DHINIC AND GETDATE() <= c.DHFIN
    ) THEN 'ALUGADO_CONTRATO'
    WHEN EXISTS (
      SELECT 1 FROM SANKHYA.TCSITE i
      INNER JOIN SANKHYA.TCSOSE o ON o.NUMOS = i.NUMOS
      WHERE i.AD_CODVEICULO = v.CODVEICULO
      AND o.SITUACAO = 'P' AND o.DTFECHAMENTO IS NULL
      AND (
        (i.INICEXEC IS NOT NULL AND i.TERMEXEC IS NULL)
        OR (i.DHPREVISTA <= GETDATE() AND i.TERMEXEC IS NULL)
      )
    ) THEN 'EM_USO'
    WHEN EXISTS (
      SELECT 1 FROM SANKHYA.AD_CONTRATOS c
      WHERE c.CODVEICULO = v.CODVEICULO AND c.DHINIC > GETDATE()
    ) THEN 'RESERVADO_CONTRATO'
    WHEN EXISTS (
      SELECT 1 FROM SANKHYA.TCSITE i
      INNER JOIN SANKHYA.TCSOSE o ON o.NUMOS = i.NUMOS
      WHERE i.AD_CODVEICULO = v.CODVEICULO
      AND o.SITUACAO = 'P' AND o.DTFECHAMENTO IS NULL
      AND i.DHPREVISTA > GETDATE() AND i.INICEXEC IS NULL
    ) THEN 'AGENDADO'
    ELSE 'LIVRE'
  END AS status
FROM SANKHYA.TGFVEI v
LEFT JOIN SANKHYA.TGFPAR mot ON mot.CODPARC = v.CODMOTORISTA
WHERE v.ATIVO = 'S' AND ISNULL(v.AD_EXIBEDASH, 'N') = 'S'
ORDER BY v.PLACA
`;
