export const utilizacaoMensal = `
SELECT
  FORMAT(s.dia, 'yyyy-MM') AS mes,
  SUM(s.em_manut) AS diasManut,
  SUM(s.em_comercial) AS diasComercial,
  SUM(CASE WHEN s.em_manut = 0 AND s.em_comercial = 0 THEN 1 ELSE 0 END) AS diasLivre,
  COUNT(*) AS diasTotal
FROM (
  SELECT
    c.dia,
    CASE WHEN (SELECT COUNT(*) FROM SANKHYA.TCFOSCAB m
      WHERE m.CODVEICULO = @codveiculo
        AND CAST(m.DATAINI AS DATE) <= c.dia
        AND CAST(
          CASE
            WHEN m.DATAFIN IS NOT NULL THEN m.DATAFIN
            WHEN m.STATUS IN ('A','E') THEN GETDATE()
            ELSE ISNULL(m.DHALTER, m.DATAINI)
          END AS DATE) >= c.dia
    ) > 0 THEN 1 ELSE 0 END AS em_manut,
    CASE WHEN (SELECT COUNT(*) FROM SANKHYA.TCSITE i
      INNER JOIN SANKHYA.TCSOSE o ON o.NUMOS = i.NUMOS
      WHERE i.AD_CODVEICULO = @codveiculo
        AND CAST(i.DHPREVISTA AS DATE) = c.dia
    ) > 0 THEN 1 ELSE 0 END AS em_comercial
  FROM (
    SELECT DATEADD(DAY, n.num, CAST(@dataInicio AS DATE)) AS dia
    FROM (
      SELECT TOP 1100 ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) - 1 AS num
      FROM sys.objects a CROSS JOIN sys.objects b
    ) n
    WHERE DATEADD(DAY, n.num, CAST(@dataInicio AS DATE)) <= CAST(@dataFim AS DATE)
  ) c
) s
GROUP BY FORMAT(s.dia, 'yyyy-MM')
ORDER BY mes
`;

export const utilizacaoResumo = `
SELECT
  (SELECT MIN(x.dt) FROM (
    SELECT MIN(m.DATAINI) AS dt FROM SANKHYA.TCFOSCAB m WHERE m.CODVEICULO = @codveiculo
    UNION ALL
    SELECT MIN(i.DHPREVISTA) FROM SANKHYA.TCSITE i
      INNER JOIN SANKHYA.TCSOSE o ON o.NUMOS = i.NUMOS
      WHERE i.AD_CODVEICULO = @codveiculo
  ) x) AS primeiraAtividade,

  (SELECT COUNT(*) FROM SANKHYA.TCFOSCAB m WHERE m.CODVEICULO = @codveiculo) AS totalOsManut,

  (SELECT COUNT(*) FROM SANKHYA.TCFOSCAB m3
    WHERE m3.CODVEICULO = @codveiculo AND m3.STATUS IN ('A','E')) AS osManutAbertas,

  (SELECT COUNT(DISTINCT o.NUMOS) FROM SANKHYA.TCSITE i
    INNER JOIN SANKHYA.TCSOSE o ON o.NUMOS = i.NUMOS
    WHERE i.AD_CODVEICULO = @codveiculo) AS totalOsCom,

  (SELECT COUNT(i2.NUMITEM) FROM SANKHYA.TCSITE i2
    INNER JOIN SANKHYA.TCSOSE o2 ON o2.NUMOS = i2.NUMOS
    WHERE i2.AD_CODVEICULO = @codveiculo) AS totalDiarias,

  (SELECT COUNT(DISTINCT o4.CODPARC) FROM SANKHYA.TCSITE i4
    INNER JOIN SANKHYA.TCSOSE o4 ON o4.NUMOS = i4.NUMOS
    WHERE i4.AD_CODVEICULO = @codveiculo) AS clientesAtendidos,

  (SELECT CAST(ISNULL(p.NOMEPARC, '') AS VARCHAR(100))
    FROM SANKHYA.TGFVEI v LEFT JOIN SANKHYA.TGFPAR p ON p.CODPARC = v.CODMOTORISTA
    WHERE v.CODVEICULO = @codveiculo) AS motoristaNome,

  (SELECT TOP 1 CAST(ISNULL(l.DESCRLOCAL, '') AS VARCHAR(200))
    FROM SANKHYA.TGFLOC l
    WHERE l.CODPARC = (SELECT v2.CODPARC FROM SANKHYA.TGFVEI v2 WHERE v2.CODVEICULO = @codveiculo)
    AND l.ATIVO = 'S') AS localParceiro
`;

export const utilizacaoPessoas = `
SELECT 'EXECUTOR_MANUTENCAO' AS papel,
  CAST(ISNULL(u.NOMEUSU, '') AS VARCHAR(100)) AS nome,
  m.CODUSU AS codUsuario,
  u.CODPARC AS codparc,
  COUNT(*) AS qtd,
  CONVERT(VARCHAR, MIN(m.DATAINI), 103) AS primeiroEnvolvimento,
  CONVERT(VARCHAR, MAX(ISNULL(m.DATAFIN, m.DHALTER)), 103) AS ultimoEnvolvimento
FROM SANKHYA.TCFOSCAB m
LEFT JOIN SANKHYA.TSIUSU u ON u.CODUSU = m.CODUSU
WHERE m.CODVEICULO = @codveiculo AND m.CODUSU IS NOT NULL
GROUP BY m.CODUSU, u.NOMEUSU, u.CODPARC

UNION ALL

SELECT 'FINALIZADOR_MANUTENCAO' AS papel,
  CAST(ISNULL(u.NOMEUSU, '') AS VARCHAR(100)) AS nome,
  m.CODUSUFINALIZA AS codUsuario,
  u.CODPARC AS codparc,
  COUNT(*) AS qtd,
  CONVERT(VARCHAR, MIN(m.DATAINI), 103) AS primeiroEnvolvimento,
  CONVERT(VARCHAR, MAX(ISNULL(m.DATAFIN, m.DHALTER)), 103) AS ultimoEnvolvimento
FROM SANKHYA.TCFOSCAB m
LEFT JOIN SANKHYA.TSIUSU u ON u.CODUSU = m.CODUSUFINALIZA
WHERE m.CODVEICULO = @codveiculo AND m.CODUSUFINALIZA IS NOT NULL
GROUP BY m.CODUSUFINALIZA, u.NOMEUSU, u.CODPARC

UNION ALL

SELECT 'OPERADOR_VEICULO' AS papel,
  CAST(ISNULL(up.NOMEUSU, '') AS VARCHAR(100)) AS nome,
  pItem.CODUSU AS codUsuario,
  up.CODPARC AS codparc,
  COUNT(DISTINCT vItem.NUMOS) AS qtd,
  CONVERT(VARCHAR, MIN(pItem.DHPREVISTA), 103) AS primeiroEnvolvimento,
  CONVERT(VARCHAR, MAX(pItem.DHPREVISTA), 103) AS ultimoEnvolvimento
FROM SANKHYA.TCSITE vItem
INNER JOIN SANKHYA.TCSITE pItem ON pItem.NUMOS = vItem.NUMOS AND pItem.CODUSU != vItem.CODUSU
INNER JOIN SANKHYA.TSIUSU up ON up.CODUSU = pItem.CODUSU AND up.CODFUNC IS NOT NULL AND up.CODFUNC > 0
WHERE vItem.AD_CODVEICULO = @codveiculo
GROUP BY pItem.CODUSU, up.NOMEUSU, up.CODPARC

UNION ALL

SELECT 'VENDEDOR_COMERCIAL' AS papel,
  CAST(ISNULL(u.NOMEUSU, '') AS VARCHAR(100)) AS nome,
  o.CODATEND AS codUsuario,
  u.CODPARC AS codparc,
  COUNT(DISTINCT o.NUMOS) AS qtd,
  CONVERT(VARCHAR, MIN(o.DHCHAMADA), 103) AS primeiroEnvolvimento,
  CONVERT(VARCHAR, MAX(o.DHCHAMADA), 103) AS ultimoEnvolvimento
FROM SANKHYA.TCSITE i
INNER JOIN SANKHYA.TCSOSE o ON o.NUMOS = i.NUMOS
LEFT JOIN SANKHYA.TSIUSU u ON u.CODUSU = o.CODATEND
WHERE i.AD_CODVEICULO = @codveiculo AND o.CODATEND IS NOT NULL
GROUP BY o.CODATEND, u.NOMEUSU, u.CODPARC

UNION ALL

SELECT 'FECHAMENTO_COMERCIAL' AS papel,
  CAST(ISNULL(u.NOMEUSU, '') AS VARCHAR(100)) AS nome,
  o.CODUSUFECH AS codUsuario,
  u.CODPARC AS codparc,
  COUNT(DISTINCT o.NUMOS) AS qtd,
  CONVERT(VARCHAR, MIN(o.DHCHAMADA), 103) AS primeiroEnvolvimento,
  CONVERT(VARCHAR, MAX(ISNULL(o.DTFECHAMENTO, o.DHCHAMADA)), 103) AS ultimoEnvolvimento
FROM SANKHYA.TCSITE i
INNER JOIN SANKHYA.TCSOSE o ON o.NUMOS = i.NUMOS
LEFT JOIN SANKHYA.TSIUSU u ON u.CODUSU = o.CODUSUFECH
WHERE i.AD_CODVEICULO = @codveiculo AND o.CODUSUFECH IS NOT NULL AND o.CODUSUFECH > 0
GROUP BY o.CODUSUFECH, u.NOMEUSU, u.CODPARC

ORDER BY papel, qtd DESC
`;
