/**
 * Query para visao em tempo real das movimentacoes (TGFVAR + TGFCAB)
 * Inclui dados do usuario que criou (TSIUSU) e tipo de operacao (TGFTOP)
 * Inclui CODPARC do usuario para foto (via TSIUSU -> TGFPAR -> TFPFUN)
 */
export const emTempoRealCabs = `
SELECT TOP(200)
    VAR.NUNOTA        AS NUNOTA,
    VAR.SEQUENCIA     AS SEQUENCIA,
    VAR.NUNOTAORIG    AS NUNOTA_ORIGEM,
    VAR.SEQUENCIAORIG AS SEQUENCIA_ORIGEM,

    CAB.NUMNOTA       AS NUMERO_NOTA,
    CAB.CODEMP        AS EMPRESA,
    CAB.CODPARC       AS CODPARC_NOTA,
    PAR.NOMEPARC      AS PARCEIRO_NOME,
    CAB.DTNEG         AS DATA_NEGOCIACAO,

    CONVERT(VARCHAR(10), CAB.DTMOV, 120) + ' ' +
    CONVERT(VARCHAR(8),  CAB.HRMOV, 108) AS DATA_HORA_MOVIMENTO,

    CAB.STATUSNOTA    AS STATUS_CODIGO,

    CASE CAB.STATUSNOTA
        WHEN 'A' THEN 'Atendimento'
        WHEN 'L' THEN 'Liberada'
        WHEN 'P' THEN 'Pendente'
        ELSE 'Outro'
    END AS STATUS_DESCRICAO,

    CAB.CODTIPOPER    AS CODIGO_TIPO_OPER,
    TOPV.DESCROPER    AS DESCRICAO_TIPO_OPER,
    TOPV.ATUALEST     AS COD_ATUALIZA_ESTOQUE,

    CASE TOPV.ATUALEST
        WHEN 'B' THEN 'Baixar estoque'
        WHEN 'E' THEN 'Entrar no estoque'
        WHEN 'N' THEN 'Nao movimenta estoque'
        WHEN 'R' THEN 'Reservar estoque'
        ELSE 'Indefinido'
    END AS DESCRICAO_ATUALIZA_ESTOQUE,

    CAB.CODUSUINC     AS CODIGO_USUARIO,
    USU.NOMEUSU       AS NOME_USUARIO,
    USU.CODPARC       AS CODPARC_USUARIO,

    CAB.VLRNOTA       AS VALOR_NOTA

FROM TGFVAR VAR

INNER JOIN TGFCAB CAB
    ON CAB.NUNOTA = VAR.NUNOTA

LEFT JOIN TGFPAR PAR
    ON PAR.CODPARC = CAB.CODPARC

LEFT JOIN TGFTOP TOPV
    ON TOPV.CODTIPOPER = CAB.CODTIPOPER
   AND TOPV.DHALTER = (
        SELECT MAX(TOP2.DHALTER)
        FROM TGFTOP TOP2
        WHERE TOP2.CODTIPOPER = CAB.CODTIPOPER
          AND TOP2.DHALTER <= CAB.DTNEG
   )

LEFT JOIN TSIUSU USU
    ON USU.CODUSU = CAB.CODUSUINC

ORDER BY
    VAR.NUNOTA DESC,
    VAR.SEQUENCIA DESC
`;

export const emTempoRealCount = `
SELECT COUNT(*) AS total FROM TGFVAR
`;

export const emTempoRealPaginado = `
SELECT
    VAR.NUNOTA        AS NUNOTA,
    VAR.SEQUENCIA     AS SEQUENCIA,
    VAR.NUNOTAORIG    AS NUNOTA_ORIGEM,
    VAR.SEQUENCIAORIG AS SEQUENCIA_ORIGEM,

    CAB.NUMNOTA       AS NUMERO_NOTA,
    CAB.CODEMP        AS EMPRESA,
    CAB.CODPARC       AS CODPARC_NOTA,
    PAR.NOMEPARC      AS PARCEIRO_NOME,
    CAB.DTNEG         AS DATA_NEGOCIACAO,

    CONVERT(VARCHAR(10), CAB.DTMOV, 120) + ' ' +
    CONVERT(VARCHAR(8),  CAB.HRMOV, 108) AS DATA_HORA_MOVIMENTO,

    CAB.STATUSNOTA    AS STATUS_CODIGO,

    CASE CAB.STATUSNOTA
        WHEN 'A' THEN 'Atendimento'
        WHEN 'L' THEN 'Liberada'
        WHEN 'P' THEN 'Pendente'
        ELSE 'Outro'
    END AS STATUS_DESCRICAO,

    CAB.CODTIPOPER    AS CODIGO_TIPO_OPER,
    TOPV.DESCROPER    AS DESCRICAO_TIPO_OPER,
    TOPV.ATUALEST     AS COD_ATUALIZA_ESTOQUE,

    CASE TOPV.ATUALEST
        WHEN 'B' THEN 'Baixar estoque'
        WHEN 'E' THEN 'Entrar no estoque'
        WHEN 'N' THEN 'Nao movimenta estoque'
        WHEN 'R' THEN 'Reservar estoque'
        ELSE 'Indefinido'
    END AS DESCRICAO_ATUALIZA_ESTOQUE,

    CAB.CODUSUINC     AS CODIGO_USUARIO,
    USU.NOMEUSU       AS NOME_USUARIO,
    USU.CODPARC       AS CODPARC_USUARIO,

    CAB.VLRNOTA       AS VALOR_NOTA

FROM TGFVAR VAR

INNER JOIN TGFCAB CAB
    ON CAB.NUNOTA = VAR.NUNOTA

LEFT JOIN TGFPAR PAR
    ON PAR.CODPARC = CAB.CODPARC

LEFT JOIN TGFTOP TOPV
    ON TOPV.CODTIPOPER = CAB.CODTIPOPER
   AND TOPV.DHALTER = (
        SELECT MAX(TOP2.DHALTER)
        FROM TGFTOP TOP2
        WHERE TOP2.CODTIPOPER = CAB.CODTIPOPER
          AND TOP2.DHALTER <= CAB.DTNEG
   )

LEFT JOIN TSIUSU USU
    ON USU.CODUSU = CAB.CODUSUINC

ORDER BY
    VAR.NUNOTA DESC,
    VAR.SEQUENCIA DESC

OFFSET @OFFSET ROWS
FETCH NEXT @LIMIT ROWS ONLY
`;

export const emTempoRealResumo = `
SELECT
    COUNT(*) AS total,
    SUM(CASE WHEN CAB.STATUSNOTA = 'A' THEN 1 ELSE 0 END) AS atendimento,
    SUM(CASE WHEN CAB.STATUSNOTA = 'L' THEN 1 ELSE 0 END) AS liberada,
    SUM(CASE WHEN CAB.STATUSNOTA = 'P' THEN 1 ELSE 0 END) AS pendente,
    SUM(CASE WHEN TOPV.ATUALEST = 'B' THEN 1 ELSE 0 END) AS baixa_estoque,
    SUM(CASE WHEN TOPV.ATUALEST = 'E' THEN 1 ELSE 0 END) AS entrada_estoque,
    SUM(CASE WHEN TOPV.ATUALEST = 'N' THEN 1 ELSE 0 END) AS sem_movimentacao,
    SUM(CASE WHEN TOPV.ATUALEST = 'R' THEN 1 ELSE 0 END) AS reserva_estoque,
    ISNULL(SUM(CAB.VLRNOTA), 0) AS valor_total

FROM TGFVAR VAR

INNER JOIN TGFCAB CAB
    ON CAB.NUNOTA = VAR.NUNOTA

LEFT JOIN TGFTOP TOPV
    ON TOPV.CODTIPOPER = CAB.CODTIPOPER
   AND TOPV.DHALTER = (
        SELECT MAX(TOP2.DHALTER)
        FROM TGFTOP TOP2
        WHERE TOP2.CODTIPOPER = CAB.CODTIPOPER
          AND TOP2.DHALTER <= CAB.DTNEG
   )

WHERE VAR.NUNOTA IN (
    SELECT TOP(200) V2.NUNOTA
    FROM TGFVAR V2
    ORDER BY V2.NUNOTA DESC
)
`;
