export const buscarPorId = `
SELECT
  c.ID,
  c.CODVEICULO,
  c.CODPARC,
  c.DHINIC,
  c.DHFIN,
  c.OBS,
  c.CREATEDDATE,
  c.UPDATEDDATE,
  c.CREATEBY,
  c.UPDATEDBY,
  v.PLACA,
  v.MARCAMODELO,
  v.AD_TAG,
  p.NOMEPARC as CONTRATANTE,
  CASE
    WHEN GETDATE() BETWEEN c.DHINIC AND c.DHFIN THEN 'VIGENTE'
    WHEN c.DHINIC > GETDATE() THEN 'FUTURO'
    ELSE 'ENCERRADO'
  END as STATUS
FROM AD_CONTRATOS c
LEFT JOIN TGFVEI v ON v.CODVEICULO = c.CODVEICULO
LEFT JOIN TGFPAR p ON p.CODPARC = c.CODPARC
WHERE c.ID = @id
  AND (c.ISDELETED = 'N' OR c.ISDELETED IS NULL)
`;
