export const disponibilidadeVeiculos = `
SELECT
    v.CODVEICULO,
    v.PLACA,
    CAST(v.MARCAMODELO AS VARCHAR(200)) AS MARCAMODELO,
    CASE
        WHEN EXISTS (
            SELECT 1 FROM SANKHYA.AD_CONTRATOS c
            WHERE c.CODVEICULO = v.CODVEICULO
            AND GETDATE() >= c.DHINIC AND GETDATE() <= c.DHFIN
        ) THEN 0 ELSE 1
    END AS DISPONIVEL,
    CASE
        WHEN EXISTS (
            SELECT 1 FROM SANKHYA.AD_CONTRATOS c
            WHERE c.CODVEICULO = v.CODVEICULO
            AND GETDATE() >= c.DHINIC AND GETDATE() <= c.DHFIN
        ) THEN 'ALUGADO'
        WHEN EXISTS (
            SELECT 1 FROM SANKHYA.AD_CONTRATOS c
            WHERE c.CODVEICULO = v.CODVEICULO AND c.DHINIC > GETDATE()
        ) THEN 'RESERVADO'
        ELSE 'DISPONIVEL'
    END AS STATUS_DISPONIBILIDADE
FROM SANKHYA.TGFVEI v
WHERE v.ATIVO = 'S'
ORDER BY v.PLACA
`;

export const disponibilidadePeriodo = `
SELECT
    v.CODVEICULO,
    v.PLACA,
    CAST(v.MARCAMODELO AS VARCHAR(200)) AS MARCAMODELO,
    CASE
        WHEN EXISTS (
            SELECT 1 FROM SANKHYA.AD_CONTRATOS c
            WHERE c.CODVEICULO = v.CODVEICULO
            AND NOT (c.DHFIN < @dataInicio OR c.DHINIC > @dataFim)
        ) THEN 0 ELSE 1
    END AS DISPONIVEL_NO_PERIODO,
    (SELECT COUNT(*) FROM SANKHYA.AD_CONTRATOS c
     WHERE c.CODVEICULO = v.CODVEICULO
     AND NOT (c.DHFIN < @dataInicio OR c.DHINIC > @dataFim)
    ) AS QTD_CONFLITOS
FROM SANKHYA.TGFVEI v
WHERE v.ATIVO = 'S' AND v.CODVEICULO = @codveiculo
`;
