export const porVeiculo = `
SELECT * FROM (
  SELECT
    c.ID,
    c.CODVEICULO,
    c.CODPARC,
    c.DHINIC,
    c.DHFIN,
    c.OBS,
    c.CREATEDDATE,
    c.UPDATEDDATE,
    p.NOMEPARC as CONTRATANTE,
    CASE
      WHEN GETDATE() BETWEEN c.DHINIC AND c.DHFIN THEN 'VIGENTE'
      WHEN c.DHINIC > GETDATE() THEN 'FUTURO'
      ELSE 'ENCERRADO'
    END as STATUS,
    ROW_NUMBER() OVER (ORDER BY c.DHINIC DESC) AS RowNum
  FROM AD_CONTRATOS c
  LEFT JOIN TGFPAR p ON p.CODPARC = c.CODPARC
  WHERE c.CODVEICULO = @codveiculo
    AND (c.ISDELETED = 'N' OR c.ISDELETED IS NULL)
) AS T
WHERE RowNum > @OFFSET AND RowNum <= (@OFFSET + @LIMIT)
`;
