export const porParceiro = `
SELECT * FROM (
  SELECT
    c.ID,
    c.CODVEICULO,
    c.CODPARC,
    c.DHINIC,
    c.DHFIN,
    c.OBS,
    c.CREATEDDATE,
    c.UPDATEDDATE,
    v.PLACA,
    v.MARCAMODELO,
    v.AD_TAG,
    CASE
      WHEN GETDATE() BETWEEN c.DHINIC AND c.DHFIN THEN 'VIGENTE'
      WHEN c.DHINIC > GETDATE() THEN 'FUTURO'
      ELSE 'ENCERRADO'
    END as STATUS,
    ROW_NUMBER() OVER (ORDER BY c.DHINIC DESC) AS RowNum
  FROM AD_CONTRATOS c
  LEFT JOIN TGFVEI v ON v.CODVEICULO = c.CODVEICULO
  WHERE c.CODPARC = @codparc
    AND (c.ISDELETED = 'N' OR c.ISDELETED IS NULL)
) AS T
WHERE RowNum > @OFFSET AND RowNum <= (@OFFSET + @LIMIT)
`;
