export const vigentes = `
SELECT * FROM (
  SELECT
    c.ID,
    c.CODVEICULO,
    c.CODPARC,
    c.DHINIC,
    c.DHFIN,
    c.OBS,
    c.CREATEDDATE,
    c.UPDATEDDATE,
    v.PLACA,
    v.MARCAMODELO,
    v.AD_TAG,
    p.NOMEPARC as CONTRATANTE,
    'VIGENTE' as STATUS,
    ROW_NUMBER() OVER (ORDER BY c.DHINIC DESC) AS RowNum
  FROM AD_CONTRATOS c
  LEFT JOIN TGFVEI v ON v.CODVEICULO = c.CODVEICULO
  LEFT JOIN TGFPAR p ON p.CODPARC = c.CODPARC
  WHERE (c.ISDELETED = 'N' OR c.ISDELETED IS NULL)
    AND GETDATE() BETWEEN c.DHINIC AND c.DHFIN
) AS T
WHERE RowNum > @OFFSET AND RowNum <= (@OFFSET + @LIMIT)
`;
