export const consumoPorVeiculo = `
SELECT
  ID,
  CODVEICULO,
  MODELO,
  FAMILIA,
  ANO,
  MARCA,
  NUMEROFROTA,
  TIPOCOMBUSTIVEL,
  ULTIMAKMH,
  KMRODADOS,
  HORASTRABALHADAS,
  VALORMEDIOLITRO,
  KMPORLITRO,
  LITROSPORHORA,
  TOTALTRANSACAO,
  LITROS,
  DATA_ABASTECIMENTO,
  PLACA_TAG,
  MOTORISTA,
  DT_UPDATE
FROM SANKHYA.AD_CONSUMOVEICULOS
WHERE CODVEICULO = @codveiculo
ORDER BY DATA_ABASTECIMENTO DESC
`;
