export const planosPorVeiculo = `
SELECT
  mv.NUPLANO,
  mv.CODVEICULO,
  mv.DTINCLUSAO,
  m.DESCRICAO,
  m.TIPO,
  m.TEMPO,
  m.KMHORIMETRO,
  m.GERAAUTO,
  m.ATIVO,
  m.PERCTOLERANCIA,
  m.TIPOREP,
  m.REPETIR
FROM SANKHYA.TCFMANVEI mv
JOIN SANKHYA.TCFMAN m ON mv.NUPLANO = m.NUPLANO
WHERE mv.CODVEICULO = @codveiculo
ORDER BY m.DESCRICAO
`;
