export const painelTodos = `
SELECT
  h.ID, h.CODVEICULO, h.IDSIT, h.IDPRI,
  h.DESCRICAO, h.OBS,
  CONVERT(VARCHAR(19), h.DTINICIO, 120) AS DTINICIO,
  CONVERT(VARCHAR(19), h.DTPREVISAO, 120) AS DTPREVISAO,
  h.NUNOTA, h.NUOS, h.NUMOS,
  h.CODPARC, h.EXEOPE, h.EXEMEC,
  h.CODUSUINC,
  v.PLACA AS placa,
  CAST(v.MARCAMODELO AS VARCHAR(200)) AS marcaModelo,
  CAST(ISNULL(v.AD_TIPOEQPTO, v.CATEGORIA) AS VARCHAR(100)) AS veiculoTipo,
  v.AD_TAG AS veiculoTag,
  CAST(ISNULL(v.AD_CAPACIDADE, '') AS VARCHAR(100)) AS veiculoCapacidade,
  CAST(ISNULL(v.AD_FABRICANTE, '') AS VARCHAR(100)) AS veiculoFabricante,
  s.DESCRICAO AS situacaoDescricao,
  s.CODDEP AS situacaoCoddep,
  dep.DESCRDEP AS departamentoNome,
  p.SIGLA AS prioridadeSigla,
  p.DESCRICAO AS prioridadeDescricao,
  par.NOMEPARC AS nomeParc,
  uinc.NOMEUSU AS nomeUsuInc,
  uinc.CODPARC AS codparcUsuInc,
  os.STATUS AS osStatus,
  os.TIPO AS osTipo,
  mos.SITUACAO AS mosSituacao,
  mosp.NOMEPARC AS mosCliente
FROM AD_HSTVEI h
INNER JOIN TGFVEI v ON v.CODVEICULO = h.CODVEICULO
INNER JOIN AD_ADHSTVEISIT s ON s.ID = h.IDSIT
LEFT JOIN TFPDEP dep ON dep.CODDEP = s.CODDEP
LEFT JOIN AD_ADHSTVEIPRI p ON p.IDPRI = h.IDPRI
LEFT JOIN TGFPAR par ON par.CODPARC = h.CODPARC
LEFT JOIN TSIUSU uinc ON uinc.CODUSU = h.CODUSUINC
LEFT JOIN TCFOSCAB os ON os.NUOS = h.NUOS
LEFT JOIN TCSOSE mos ON mos.NUMOS = h.NUMOS
LEFT JOIN TGFPAR mosp ON mosp.CODPARC = mos.CODPARC
WHERE h.DTFIM IS NULL
ORDER BY ISNULL(h.IDPRI, 99), h.DTPREVISAO, v.PLACA
`;
