export const stats = `
SELECT
  (SELECT COUNT(DISTINCT h1.CODVEICULO) FROM AD_HSTVEI h1 WHERE h1.DTFIM IS NULL) AS veiculosComSituacao,
  (SELECT COUNT(*) FROM AD_HSTVEI h2 WHERE h2.DTFIM IS NULL) AS situacoesAtivas,
  (SELECT COUNT(*) FROM AD_HSTVEI h3 WHERE h3.DTFIM IS NULL AND h3.IDPRI = 0) AS urgentes,
  (SELECT COUNT(*) FROM AD_HSTVEI h4 WHERE h4.DTFIM IS NULL AND h4.DTPREVISAO < GETDATE()) AS atrasadas,
  (SELECT COUNT(*) FROM AD_HSTVEI h5 WHERE h5.DTFIM IS NULL AND h5.DTPREVISAO >= GETDATE() AND h5.DTPREVISAO <= DATEADD(DAY, 3, GETDATE())) AS previsao3dias,
  (SELECT COUNT(DISTINCT h6.CODVEICULO) FROM AD_HSTVEI h6 INNER JOIN AD_ADHSTVEISIT s6 ON s6.ID = h6.IDSIT WHERE h6.DTFIM IS NULL AND s6.CODDEP = 1050000) AS veiculosManutencao,
  (SELECT COUNT(DISTINCT h7.CODVEICULO) FROM AD_HSTVEI h7 INNER JOIN AD_ADHSTVEISIT s7 ON s7.ID = h7.IDSIT WHERE h7.DTFIM IS NULL AND s7.CODDEP = 1020000) AS veiculosComercial,
  (SELECT COUNT(DISTINCT h8.CODVEICULO) FROM AD_HSTVEI h8 INNER JOIN AD_ADHSTVEISIT s8 ON s8.ID = h8.IDSIT WHERE h8.DTFIM IS NULL AND s8.CODDEP = 1090000) AS veiculosLogistica,
  (SELECT COUNT(DISTINCT h9.CODVEICULO) FROM AD_HSTVEI h9 INNER JOIN AD_ADHSTVEISIT s9 ON s9.ID = h9.IDSIT WHERE h9.DTFIM IS NULL AND s9.CODDEP = 1140000) AS veiculosOperacao
`;
