export const findFuncionariosHabilitados = `
SELECT 
    CAST(FUN.CODFUNC AS VARCHAR) + '-' + CAST(HAB.CODHAB AS VARCHAR) as id,
    FUN.CODFUNC,
    FUN.NOMEFUNC,
    EMP.CODEMP,
    EMP.RAZAOSOCIAL,
    CAR.DESCRCARGO,
    HABI.DESCRICAO AS HABILITACAO,
    HAB.DTEMISSAO,
    HAB.DTVALIDADE,
    DEP.DESCRDEP AS descricao_dep,
    DEP.CODDEP,
    'OK' AS STATUS_VALIDADE
FROM TFPFUN FUN
INNER JOIN TFPDEP DEP ON DEP.CODDEP = FUN.CODDEP
INNER JOIN TFPCAR CAR ON CAR.CODCARGO = FUN.CODCARGO
INNER JOIN TSIEMP EMP ON EMP.CODEMP = FUN.CODEMP
INNER JOIN TSIUSU USU ON USU.CPF = FUN.CPF 
INNER JOIN AD_TSIUSUHAB HAB ON HAB.CODUSU = USU.CODUSU
INNER JOIN AD_CADHAB HABI ON HABI.CODHAB = HAB.CODHAB
WHERE FUN.SITUACAO = '1'  
  AND HAB.DTVALIDADE >= CAST(GETDATE() AS DATE) 
ORDER BY FUN.NOMEFUNC
`;
