export const getGruposTodos = `
SELECT
  CODGRUPOPROD,
  DESCRGRUPOPROD,
  CODGRUPAI,
  GRAU,
  ANALITICO,
  ATIVO
FROM TGFGRU
WHERE CODGRUPOPROD > 0
ORDER BY GRAU, CODGRUPOPROD
`;

export const getTodosServicosComGrupoTodos = `
SELECT
  pro.CODPROD,
  pro.DESCRPROD,
  pro.CODGRUPOPROD,
  pro.ATIVO,
  COALESCE(srvTotais.qtd_total, 0) AS UTILIZACOES
FROM TGFPRO pro
LEFT JOIN (
  SELECT CODPROD, SUM(QTD) as qtd_total
  FROM TCFSERVOS
  GROUP BY CODPROD
) srvTotais ON pro.CODPROD = srvTotais.CODPROD
WHERE pro.CODGRUPOPROD IS NOT NULL
  AND pro.CODGRUPOPROD > 0
  AND pro.USOPROD = 'S'
ORDER BY pro.CODGRUPOPROD, UTILIZACOES DESC
`;
