export const getGruposHierarquia = `
SELECT 
  CODGRUPOPROD,
  DESCRGRUPOPROD,
  CODGRUPAI,
  GRAU,
  ANALITICO
FROM TGFGRU
WHERE ATIVO = 'S' 
  AND CODGRUPOPROD > 0
ORDER BY GRAU, CODGRUPOPROD
`;

export const getServicosPorGrupo = `
SELECT
  pro.CODPROD,
  pro.DESCRPROD,
  pro.CODGRUPOPROD,
  COALESCE(srvTotais.qtd_total, 0) AS UTILIZACOES
FROM TGFPRO pro
LEFT JOIN (
  SELECT CODPROD, SUM(QTD) as qtd_total
  FROM TCFSERVOS
  GROUP BY CODPROD
) srvTotais ON pro.CODPROD = srvTotais.CODPROD
WHERE pro.CODGRUPOPROD = @CODGRUPOPROD
  AND pro.ATIVO = 'S'
  AND pro.USOPROD = 'S'
ORDER BY UTILIZACOES DESC
`;

export const getTodosServicosComGrupo = `
SELECT
  pro.CODPROD,
  pro.DESCRPROD,
  pro.CODGRUPOPROD,
  COALESCE(srvTotais.qtd_total, 0) AS UTILIZACOES
FROM TGFPRO pro
LEFT JOIN (
  SELECT CODPROD, SUM(QTD) as qtd_total
  FROM TCFSERVOS
  GROUP BY CODPROD
) srvTotais ON pro.CODPROD = srvTotais.CODPROD
WHERE pro.CODGRUPOPROD IS NOT NULL
  AND pro.CODGRUPOPROD > 0
  AND pro.ATIVO = 'S'
  AND pro.USOPROD = 'S'
ORDER BY pro.CODGRUPOPROD, UTILIZACOES DESC
`;
