export const getVeiculosPorProduto = `
SELECT TOP 100
  v.CODVEICULO,
  RTRIM(v.PLACA) AS PLACA,
  RTRIM(v.MARCAMODELO) AS MARCAMODELO,
  RTRIM(CAST(ISNULL(v.AD_TAG, '') AS VARCHAR(30))) AS TAG,
  RTRIM(CAST(ISNULL(v.AD_TIPOEQPTO, '') AS VARCHAR(50))) AS TIPOEQPTO,
  v.ATIVO,
  ISNULL(v.KMACUM, 0) AS KMACUM,
  v.ANOFABRIC,
  v.ANOMOD,
  RTRIM(CAST(ISNULL(v.COMBUSTIVEL, '') AS VARCHAR(20))) AS COMBUSTIVEL,
  RTRIM(CAST(ISNULL(v.CHASSIS, '') AS VARCHAR(20))) AS CHASSIS,
  RTRIM(CAST(ISNULL(v.RENAVAM, '') AS VARCHAR(20))) AS RENAVAM,
  RTRIM(CAST(ISNULL(v.CATEGORIA, '') AS VARCHAR(20))) AS CATEGORIA,
  RTRIM(CAST(ISNULL(v.AD_FABRICANTE, '') AS VARCHAR(100))) AS FABRICANTE,
  RTRIM(CAST(ISNULL(v.AD_CAPACIDADE, '') AS VARCHAR(100))) AS CAPACIDADE,
  RTRIM(CAST(ISNULL(v.AD_TIPOMOTOR, '') AS VARCHAR(100))) AS TIPOMOTOR,
  RTRIM(CAST(ISNULL(v.BLOQUEADO, '') AS VARCHAR(10))) AS BLOQUEADO,
  RTRIM(CAST(ISNULL(v.AD_EMCONTRATO, '') AS VARCHAR(1))) AS EMCONTRATO
FROM TGFVEI v
WHERE v.AD_TIPOEQPTO LIKE @PREFIX + '%'
ORDER BY v.ATIVO DESC, v.AD_TAG, v.PLACA
`;
