export const getProdutoDetalhes = `
SELECT TOP 1
  p.CODPROD,
  RTRIM(CAST(p.DESCRPROD AS VARCHAR(100))) AS DESCRPROD,
  p.CODGRUPOPROD,
  RTRIM(CAST(ISNULL(g.DESCRGRUPOPROD, '') AS VARCHAR(100))) AS DESCRGRUPOPROD,
  p.ATIVO,
  RTRIM(CAST(ISNULL(p.COMPLDESC, '') AS VARCHAR(200))) AS COMPLDESC,
  RTRIM(CAST(ISNULL(p.CODVOL, '') AS VARCHAR(10))) AS CODVOL,
  RTRIM(CAST(ISNULL(p.MARCA, '') AS VARCHAR(50))) AS MARCA,
  RTRIM(CAST(ISNULL(p.REFERENCIA, '') AS VARCHAR(50))) AS REFERENCIA,
  RTRIM(CAST(ISNULL(p.LOCALIZACAO, '') AS VARCHAR(40))) AS LOCALIZACAO,
  ISNULL(p.PESOBRUTO, 0) AS PESOBRUTO,
  ISNULL(p.PESOLIQ, 0) AS PESOLIQ,
  p.CODLOCALPADRAO,
  CASE WHEN p.IMAGEM IS NOT NULL THEN 'S' ELSE 'N' END AS TEMIMAGEM,
  p.USOPROD,
  RTRIM(CAST(ISNULL(p.NCM, '') AS VARCHAR(20))) AS NCM
FROM TGFPRO p
LEFT JOIN TGFGRU g ON p.CODGRUPOPROD = g.CODGRUPOPROD
WHERE p.CODPROD = @CODPROD
`;

export const getProdutoImagem = `
SELECT TOP 1
  CAST('' AS XML).value(
    'xs:base64Binary(sql:column("IMG_BIN"))',
    'VARCHAR(MAX)'
  ) AS IMAGEM_B64
FROM (
  SELECT CAST(p.IMAGEM AS VARBINARY(MAX)) AS IMG_BIN
  FROM TGFPRO p
  WHERE p.CODPROD = @CODPROD
    AND p.IMAGEM IS NOT NULL
) T
`;
