export const getNextCodGrupoProd = `
SELECT MAX(CODGRUPOPROD) AS MAX_COD
FROM TGFGRU
WHERE CODGRUPOPROD > 0
`;

export const getNextCodGrupoProdByPai = `
SELECT MAX(CODGRUPOPROD) AS MAX_COD
FROM TGFGRU
WHERE CODGRUPAI = @CODGRUPAI
  AND CODGRUPOPROD > 0
`;

export const getChildrenCods = `
SELECT CODGRUPOPROD
FROM TGFGRU
WHERE CODGRUPAI = @CODGRUPAI
  AND CODGRUPOPROD > 0
ORDER BY CODGRUPOPROD
`;
