export const getStatsVolumeMensal = `
SELECT
  YEAR(C.DT_CREATED) AS ANO,
  MONTH(C.DT_CREATED) AS MES,
  COUNT(*) AS TOTAL
FROM AD_CHAMADOSCORRIDAS C WITH (NOLOCK)
WHERE C.DT_CREATED >= DATEADD(MONTH, -12, GETDATE())
  AND C.DT_CREATED IS NOT NULL
GROUP BY YEAR(C.DT_CREATED), MONTH(C.DT_CREATED)
ORDER BY ANO, MES
`;
