export const getStatsPorSolicitante = `
SELECT
  C.USU_SOLICITANTE,
  RTRIM(SOL.NOMEUSU) AS NOMESOLICITANTE,
  COUNT(*) AS TOTAL
FROM AD_CHAMADOSCORRIDAS C WITH (NOLOCK)
LEFT JOIN TSIUSU SOL ON SOL.CODUSU = C.USU_SOLICITANTE
WHERE C.USU_SOLICITANTE IS NOT NULL
-- @WHERE
GROUP BY C.USU_SOLICITANTE, SOL.NOMEUSU
ORDER BY TOTAL DESC
`;
