export const getStatsPorTipo = `
SELECT
  C.BUSCARLEVAR,
  COUNT(*) AS TOTAL
FROM AD_CHAMADOSCORRIDAS C WITH (NOLOCK)
WHERE C.BUSCARLEVAR IS NOT NULL
-- @WHERE
GROUP BY C.BUSCARLEVAR
ORDER BY TOTAL DESC
`;
