export const getStatsPorMotorista = `
SELECT
  C.USU_MOTORISTA,
  RTRIM(MOT.NOMEUSU) AS NOMEMOTORISTA,
  COUNT(*) AS TOTAL
FROM AD_CHAMADOSCORRIDAS C WITH (NOLOCK)
LEFT JOIN TSIUSU MOT ON MOT.CODUSU = C.USU_MOTORISTA
WHERE C.USU_MOTORISTA IS NOT NULL
-- @WHERE
GROUP BY C.USU_MOTORISTA, MOT.NOMEUSU
ORDER BY TOTAL DESC
`;
