export const getCount = `
SELECT COUNT(*) AS TOTAL
FROM AD_CHAMADOSCORRIDAS C WITH (NOLOCK)
LEFT JOIN TGFPAR P ON P.CODPARC = C.CODPARC
LEFT JOIN TSIUSU MOT ON MOT.CODUSU = C.USU_MOTORISTA
LEFT JOIN TSIUSU SOL ON SOL.CODUSU = C.USU_SOLICITANTE
LEFT JOIN TSICUS CUS ON CUS.CODCENCUS = SOL.CODCENCUSPAD
WHERE 1=1
-- @WHERE
`;
