export const getById = `
SELECT
  C.ID,
  C.USU_MOTORISTA,
  C.CODPARC,
  C.DESTINO,
  C.STATUS,
  C.USU_SOLICITANTE,
  CONVERT(VARCHAR(19), C.DT_UPDATED, 120) AS DT_UPDATED,
  CONVERT(VARCHAR(19), C.DT_FINISHED, 120) AS DT_FINISHED,
  C.USER_ID,
  CONVERT(VARCHAR(19), C.DT_CREATED, 120) AS DT_CREATED,
  C.PRIORIDADE,
  C.BUSCARLEVAR,
  C.OBS,
  C.PASSAGEIROSMERCADORIA,
  CONVERT(VARCHAR(19), C.DT_ACIONAMENTO, 120) AS DT_ACIONAMENTO,
  C.ENVIAWPP,
  MOT.NOMEUSU AS NOMEMOTORISTA,
  P.NOMEPARC,
  SOL.NOMEUSU AS NOMESOLICITANTE,
  CUS.DESCRCENCUS AS SETOR
FROM AD_CHAMADOSCORRIDAS C WITH (NOLOCK)
LEFT JOIN TGFPAR P ON P.CODPARC = C.CODPARC
LEFT JOIN TSIUSU MOT ON MOT.CODUSU = C.USU_MOTORISTA
LEFT JOIN TSIUSU SOL ON SOL.CODUSU = C.USU_SOLICITANTE
LEFT JOIN TSICUS CUS ON CUS.CODCENCUS = SOL.CODCENCUSPAD
WHERE C.ID = @ID
`;
