export const getMotoristas = `
SELECT DISTINCT U.CODUSU, RTRIM(U.NOMEUSU) AS NOMEUSU
FROM TSIUSU U WITH (NOLOCK)
WHERE U.CODUSU IN (
  SELECT DISTINCT USU_MOTORISTA
  FROM AD_CHAMADOSCORRIDAS WITH (NOLOCK)
  WHERE USU_MOTORISTA IS NOT NULL
)
ORDER BY NOMEUSU
`;
