export const getStatsTempoTransito = `
SELECT
  AVG(DATEDIFF(MINUTE, C.DT_CREATED, C.DT_FINISHED)) AS AVG_MINUTOS,
  MIN(DATEDIFF(MINUTE, C.DT_CREATED, C.DT_FINISHED)) AS MIN_MINUTOS,
  MAX(DATEDIFF(MINUTE, C.DT_CREATED, C.DT_FINISHED)) AS MAX_MINUTOS
FROM AD_CHAMADOSCORRIDAS C WITH (NOLOCK)
WHERE C.DT_CREATED IS NOT NULL
  AND C.DT_FINISHED IS NOT NULL
  AND DATEDIFF(MINUTE, C.DT_CREATED, C.DT_FINISHED) <= 1440
-- @WHERE
`;
