export const getStatsPorHora = `
SELECT
  DATEPART(HOUR, C.DT_ACIONAMENTO) AS HORA,
  COUNT(*) AS TOTAL
FROM AD_CHAMADOSCORRIDAS C WITH (NOLOCK)
WHERE C.DT_ACIONAMENTO IS NOT NULL
-- @WHERE
GROUP BY DATEPART(HOUR, C.DT_ACIONAMENTO)
ORDER BY HORA
`;
