export const getStatsPorParceiro = `
SELECT TOP 20
  C.CODPARC,
  P.NOMEPARC,
  COUNT(*) AS TOTAL
FROM AD_CHAMADOSCORRIDAS C WITH (NOLOCK)
LEFT JOIN TGFPAR P ON P.CODPARC = C.CODPARC
WHERE C.CODPARC IS NOT NULL
-- @WHERE
GROUP BY C.CODPARC, P.NOMEPARC
ORDER BY TOTAL DESC
`;
