export const getList = `
SELECT * FROM (
  SELECT
    C.ID,
    C.USU_MOTORISTA,
    C.CODPARC,
    C.DESTINO,
    C.STATUS,
    C.USU_SOLICITANTE,
    CONVERT(VARCHAR(19), C.DT_UPDATED, 120) AS DT_UPDATED,
    CONVERT(VARCHAR(19), C.DT_FINISHED, 120) AS DT_FINISHED,
    C.USER_ID,
    CONVERT(VARCHAR(19), C.DT_CREATED, 120) AS DT_CREATED,
    C.PRIORIDADE,
    C.BUSCARLEVAR,
    C.OBS,
    C.PASSAGEIROSMERCADORIA,
    CONVERT(VARCHAR(19), C.DT_ACIONAMENTO, 120) AS DT_ACIONAMENTO,
    C.ENVIAWPP,
    MOT.NOMEUSU AS NOMEMOTORISTA,
    MOT.CODPARC AS CODPARC_MOTORISTA,
    P.NOMEPARC,
    SOL.NOMEUSU AS NOMESOLICITANTE,
    SOL.CODPARC AS CODPARC_SOLICITANTE,
    CUS.DESCRCENCUS AS SETOR,
    MOT_CAR.DESCRCARGO AS CARGO_MOTORISTA,
    SOL_CAR.DESCRCARGO AS CARGO_SOLICITANTE,
    P.TELEFONE AS TELEFONE_PARCEIRO,
    P.CEP AS CEP_PARCEIRO,
    P.NUMEND AS NUMEND_PARCEIRO,
    P.COMPLEMENTO AS COMPLEMENTO_PARCEIRO,
    ENDER.NOMEEND AS RUA_PARCEIRO,
    BAI.NOMEBAI AS BAIRRO_PARCEIRO,
    CID.NOMECID AS CIDADE_PARCEIRO,
    UFS.UF AS UF_PARCEIRO,
    ROW_NUMBER() OVER (ORDER BY -- @ORDER
    ) AS RowNum
  FROM AD_CHAMADOSCORRIDAS C WITH (NOLOCK)
  LEFT JOIN TGFPAR P ON P.CODPARC = C.CODPARC
  LEFT JOIN TSIEND ENDER ON ENDER.CODEND = P.CODEND
  LEFT JOIN TSIBAI BAI ON BAI.CODBAI = P.CODBAI
  LEFT JOIN TSICID CID ON CID.CODCID = P.CODCID
  LEFT JOIN TSIUFS UFS ON UFS.CODUF = CID.UF
  LEFT JOIN TSIUSU MOT ON MOT.CODUSU = C.USU_MOTORISTA
  LEFT JOIN TFPFUN MOT_F ON MOT_F.CODEMP = MOT.CODEMP AND MOT_F.CODFUNC = MOT.CODFUNC
  LEFT JOIN TFPCAR MOT_CAR ON MOT_CAR.CODCARGO = MOT_F.CODCARGO
  LEFT JOIN TSIUSU SOL ON SOL.CODUSU = C.USU_SOLICITANTE
  LEFT JOIN TFPFUN SOL_F ON SOL_F.CODEMP = SOL.CODEMP AND SOL_F.CODFUNC = SOL.CODFUNC
  LEFT JOIN TFPCAR SOL_CAR ON SOL_CAR.CODCARGO = SOL_F.CODCARGO
  LEFT JOIN TSICUS CUS ON CUS.CODCENCUS = SOL.CODCENCUSPAD
  WHERE 1=1
  -- @WHERE
) AS T
WHERE RowNum > @OFFSET AND RowNum <= (@OFFSET + @LIMIT)
`;
