export const analisePorTipoVeiculo = `
SELECT
  RTRIM(CAST(V.AD_TIPOEQPTO AS VARCHAR(MAX))) AS tipoVeiculo,
  COUNT(DISTINCT O.NUOS) AS totalOs,
  COUNT(E.SEQUENCIA) AS totalExecucoes,
  COUNT(DISTINCT O.CODVEICULO) AS veiculosDistintos,
  CAST(AVG(CASE
    WHEN (CAST(E.DTFIN AS FLOAT) - CAST(E.DTINI AS FLOAT)) * 1440
      BETWEEN 1 AND 43200
    THEN (CAST(E.DTFIN AS FLOAT) - CAST(E.DTINI AS FLOAT)) * 1440
  END) AS INT) AS mediaMinutos,
  CAST(MIN(CASE
    WHEN (CAST(E.DTFIN AS FLOAT) - CAST(E.DTINI AS FLOAT)) * 1440
      BETWEEN 1 AND 43200
    THEN (CAST(E.DTFIN AS FLOAT) - CAST(E.DTINI AS FLOAT)) * 1440
  END) AS INT) AS minMinutos,
  CAST(MAX(CASE
    WHEN (CAST(E.DTFIN AS FLOAT) - CAST(E.DTINI AS FLOAT)) * 1440
      BETWEEN 1 AND 43200
    THEN (CAST(E.DTFIN AS FLOAT) - CAST(E.DTINI AS FLOAT)) * 1440
  END) AS INT) AS maxMinutos
FROM TCFOSCAB O WITH (NOLOCK)
INNER JOIN TGFVEI V WITH (NOLOCK) ON V.CODVEICULO = O.CODVEICULO
INNER JOIN AD_TCFEXEC E WITH (NOLOCK) ON E.NUOS = O.NUOS
WHERE O.CODVEICULO IS NOT NULL
  AND E.DTFIN IS NOT NULL AND E.DTINI IS NOT NULL
  AND V.AD_TIPOEQPTO IS NOT NULL
  -- @WHERE
GROUP BY RTRIM(CAST(V.AD_TIPOEQPTO AS VARCHAR(MAX)))
ORDER BY COUNT(DISTINCT O.NUOS) DESC
`;
