/**
 * KPIs de manutenção para dashboard
 * Query validada contra PROD em 06/02/2026
 */
export const kpis = `
SELECT
  (SELECT COUNT(*) FROM TCFOSCAB
   WHERE STATUS IN ('A', 'E') AND DATAFIN IS NULL) AS totalAtivas,

  (SELECT COUNT(*) FROM TCFOSCAB
   WHERE STATUS = 'A' AND DATAFIN IS NULL) AS osAbertas,

  (SELECT COUNT(*) FROM TCFOSCAB
   WHERE STATUS = 'E' AND DATAFIN IS NULL) AS osEmExecucao,

  (SELECT COUNT(*) FROM TCFOSCAB
   WHERE STATUS IN ('A', 'E') AND DATAFIN IS NULL
   AND MANUTENCAO = 'C') AS corretivas,

  (SELECT COUNT(*) FROM TCFOSCAB
   WHERE STATUS IN ('A', 'E') AND DATAFIN IS NULL
   AND MANUTENCAO = 'P') AS preventivas,

  (SELECT COUNT(*) FROM TCFOSCAB
   WHERE DATAFIN IS NULL AND AD_BLOQUEIOS = 'S') AS comBloqueioComercial,

  (SELECT COUNT(*) FROM TCFOSCAB
   WHERE STATUS IN ('A', 'E') AND DATAFIN IS NULL
   AND PREVISAO < GETDATE()) AS atrasadas,

  (SELECT COUNT(*) FROM TCFOSCAB
   WHERE STATUS IN ('A', 'E') AND DATAFIN IS NULL
   AND AD_STATUSGIG IN ('AN', 'SN')) AS naoImpeditivas
`;
