export const osDetalhadaExecucoes = `
SELECT
    e.NUOS,
    e.SEQUENCIA,
    e.CODUSU,
    CAST(ISNULL(u1.NOMEUSU, '') AS VARCHAR(200)) AS USUARIO,
    e.CODUSUEXEC,
    CAST(ISNULL(u2.NOMEUSU, '') AS VARCHAR(200)) AS EXECUTOR,
    e.DTINI,
    e.DTFIN,
    DATEDIFF(MINUTE, e.DTINI, e.DTFIN) AS TEMPO_MINUTOS,
    e.CODGRUPOPROD,
    CAST(ISNULL(e.OBS, '') AS VARCHAR(MAX)) AS OBS
FROM SANKHYA.AD_TCFEXEC e
LEFT JOIN SANKHYA.TSIUSU u1 ON u1.CODUSU = e.CODUSU
LEFT JOIN SANKHYA.TSIUSU u2 ON u2.CODUSU = e.CODUSUEXEC
WHERE e.NUOS = @nuos
ORDER BY e.SEQUENCIA
`;
