/** Timeline de mudancas de status de uma OS (AD_LOGSTATUSOS + TSIUSU) */
export const osTimeline = `SELECT L.SEQUENCIA, L.NUOS, CONVERT(VARCHAR(19),L.DHALTER,120) AS DHALTER, L.CODUSU, U.NOMEUSU AS NOME_USUARIO, L.STATUS AS AD_STATUSGIG, L.STATUSFIN AS AD_FINALIZACAO FROM AD_LOGSTATUSOS L LEFT JOIN TSIUSU U ON U.CODUSU=L.CODUSU WHERE L.NUOS=@nuos ORDER BY L.SEQUENCIA`;
