/**
 * Tempo de execucao de servicos de OS — 7 queries
 * Fonte: TCFSERVOS, AD_TCFEXEC, TGFPRO, TGFGRU, TCFOSCAB
 * Filtros de sanidade: fim > inicio, DATAINI > 2022, duracao <= 30 dias
 * Placeholders: -- @WHERE (periodo), -- @WHERE_EXEC (executor), -- @WHERE_GRUPO (grupo)
 * IMPORTANT: API Mother rejects subqueries (FROM (...) sub). No CTEs.
 */

/** 1. Resumo geral (KPI cards) */
export const tempoServicosResumo = `
SELECT
  COUNT(*) AS totalServicos,
  SUM(CASE
    WHEN S.DATAFIN IS NOT NULL AND S.DATAINI IS NOT NULL
      AND S.DATAFIN > S.DATAINI
      AND S.DATAINI > '2022-01-01'
      AND DATEDIFF(DAY, S.DATAINI, S.DATAFIN) <= 30
    THEN 1 ELSE 0
  END) AS comDatasValidas,
  SUM(CASE
    WHEN S.STATUS IS NULL AND S.DATAINI IS NULL AND S.DATAFIN IS NULL
    THEN 1 ELSE 0
  END) AS nuncaExecutados,
  AVG(CASE
    WHEN S.DATAFIN IS NOT NULL AND S.DATAINI IS NOT NULL
      AND S.DATAFIN > S.DATAINI
      AND S.DATAINI > '2022-01-01'
      AND DATEDIFF(DAY, S.DATAINI, S.DATAFIN) <= 30
    THEN CAST(DATEDIFF(MINUTE, S.DATAINI, S.DATAFIN) AS FLOAT) / 60.0
    ELSE NULL
  END) AS mediaHoras
FROM TCFSERVOS S
INNER JOIN TCFOSCAB O ON O.NUOS = S.NUOS
WHERE 1=1
-- @WHERE
`;

/** 2. Media por tipo de manutencao */
export const tempoServicosPorTipo = `
SELECT
  O.MANUTENCAO AS manutencao,
  CASE O.MANUTENCAO
    WHEN 'C' THEN 'Corretiva'
    WHEN 'P' THEN 'Preventiva'
    WHEN '5' THEN 'Borracharia'
    WHEN '1' THEN 'Revisao em Garantia'
    WHEN '2' THEN 'Corretiva Programada'
    WHEN 'R' THEN 'Reforma'
    WHEN 'S' THEN 'Socorro'
    WHEN 'O' THEN 'Outros'
    ELSE ISNULL(O.MANUTENCAO, 'N/A')
  END AS label,
  COUNT(*) AS total,
  SUM(CASE
    WHEN S.DATAFIN IS NOT NULL AND S.DATAINI IS NOT NULL
      AND S.DATAFIN > S.DATAINI
      AND S.DATAINI > '2022-01-01'
      AND DATEDIFF(DAY, S.DATAINI, S.DATAFIN) <= 30
    THEN 1 ELSE 0
  END) AS validos,
  SUM(CASE
    WHEN S.STATUS IS NULL AND S.DATAINI IS NULL AND S.DATAFIN IS NULL
    THEN 1 ELSE 0
  END) AS nuncaExecutados,
  AVG(CASE
    WHEN S.DATAFIN IS NOT NULL AND S.DATAINI IS NOT NULL
      AND S.DATAFIN > S.DATAINI
      AND S.DATAINI > '2022-01-01'
      AND DATEDIFF(DAY, S.DATAINI, S.DATAFIN) <= 30
    THEN CAST(DATEDIFF(MINUTE, S.DATAINI, S.DATAFIN) AS FLOAT) / 60.0
    ELSE NULL
  END) AS mediaHoras
FROM TCFSERVOS S
INNER JOIN TCFOSCAB O ON O.NUOS = S.NUOS
WHERE 1=1
-- @WHERE
GROUP BY O.MANUTENCAO
ORDER BY total DESC
`;

/** 3. Distribuicao por faixa de duracao (sem subquery — API Mother nao suporta) */
export const tempoServicosDistribuicao = `
SELECT
  CASE
    WHEN DATEDIFF(MINUTE, S.DATAINI, S.DATAFIN) < 60 THEN '< 1h'
    WHEN DATEDIFF(MINUTE, S.DATAINI, S.DATAFIN) < 480 THEN '1-8h'
    WHEN DATEDIFF(MINUTE, S.DATAINI, S.DATAFIN) < 1440 THEN '8-24h'
    WHEN DATEDIFF(MINUTE, S.DATAINI, S.DATAFIN) < 4320 THEN '1-3d'
    WHEN DATEDIFF(MINUTE, S.DATAINI, S.DATAFIN) < 10080 THEN '3-7d'
    WHEN DATEDIFF(MINUTE, S.DATAINI, S.DATAFIN) < 43200 THEN '7-30d'
    ELSE '30d+'
  END AS faixa,
  COUNT(*) AS total
FROM TCFSERVOS S
INNER JOIN TCFOSCAB O ON O.NUOS = S.NUOS
WHERE S.DATAFIN IS NOT NULL AND S.DATAINI IS NOT NULL
  AND S.DATAFIN > S.DATAINI
  AND S.DATAINI > '2022-01-01'
  AND DATEDIFF(DAY, S.DATAINI, S.DATAFIN) <= 30
-- @WHERE
GROUP BY
  CASE
    WHEN DATEDIFF(MINUTE, S.DATAINI, S.DATAFIN) < 60 THEN '< 1h'
    WHEN DATEDIFF(MINUTE, S.DATAINI, S.DATAFIN) < 480 THEN '1-8h'
    WHEN DATEDIFF(MINUTE, S.DATAINI, S.DATAFIN) < 1440 THEN '8-24h'
    WHEN DATEDIFF(MINUTE, S.DATAINI, S.DATAFIN) < 4320 THEN '1-3d'
    WHEN DATEDIFF(MINUTE, S.DATAINI, S.DATAFIN) < 10080 THEN '3-7d'
    WHEN DATEDIFF(MINUTE, S.DATAINI, S.DATAFIN) < 43200 THEN '7-30d'
    ELSE '30d+'
  END
`;

/** 4. Por executor/colaborador (AD_TCFEXEC) — COALESCE(CODUSUEXEC, CODUSU) */
export const tempoServicosPorExecutor = `
SELECT
  COALESCE(ex.CODUSUEXEC, ex.CODUSU) AS codusu,
  uexec.NOMEUSU AS nomeExecutor,
  uexec.CODPARC AS codparc,
  fun.CODEMP AS codemp,
  fun.CODFUNC AS codfunc,
  car.DESCRCARGO AS cargo,
  cus.DESCRCENCUS AS departamento,
  COUNT(*) AS totalServicos,
  SUM(CASE WHEN ex.DTFIN IS NOT NULL THEN 1 ELSE 0 END) AS servicosConcluidos,
  AVG(CASE WHEN DATEDIFF(DAY, ex.DTINI, ex.DTFIN) <= 30
    THEN CAST(DATEDIFF(MINUTE, ex.DTINI, ex.DTFIN) AS FLOAT) ELSE NULL END) AS mediaMinutos,
  SUM(CASE WHEN DATEDIFF(DAY, ex.DTINI, ex.DTFIN) <= 30
    THEN DATEDIFF(MINUTE, ex.DTINI, ex.DTFIN) ELSE 0 END) AS totalMinutos
FROM AD_TCFEXEC ex
INNER JOIN TCFOSCAB O ON O.NUOS = ex.NUOS
LEFT JOIN TSIUSU uexec ON COALESCE(ex.CODUSUEXEC, ex.CODUSU) = uexec.CODUSU
LEFT JOIN TFPFUN fun ON uexec.CODPARC = fun.CODPARC AND fun.CODEMP = uexec.CODEMP
LEFT JOIN TFPCAR car ON fun.CODCARGO = car.CODCARGO
LEFT JOIN TSICUS cus ON uexec.CODCENCUSPAD = cus.CODCENCUS
WHERE ex.DTFIN IS NOT NULL AND ex.DTINI IS NOT NULL
  AND ex.DTFIN > ex.DTINI
  AND ex.DTINI > '2022-01-01'
  AND DATEDIFF(DAY, ex.DTINI, ex.DTFIN) <= 30
  AND COALESCE(ex.CODUSUEXEC, ex.CODUSU) IS NOT NULL
-- @WHERE
-- @WHERE_EXEC
GROUP BY COALESCE(ex.CODUSUEXEC, ex.CODUSU), uexec.NOMEUSU, uexec.CODPARC,
  fun.CODEMP, fun.CODFUNC, car.DESCRCARGO, cus.DESCRCENCUS, uexec.CODCENCUSPAD
ORDER BY totalServicos DESC
`;

/** 5. Por grupo de servico (TGFPRO + TGFGRU, somente servicos) */
export const tempoServicosPorGrupo = `
SELECT
  pro.CODGRUPOPROD AS codGrupoProd,
  grp.DESCRGRUPOPROD AS descrGrupo,
  COUNT(*) AS totalServicos,
  SUM(CASE
    WHEN S.DATAFIN IS NOT NULL AND S.DATAINI IS NOT NULL
      AND S.DATAFIN > S.DATAINI
      AND S.DATAINI > '2022-01-01'
      AND DATEDIFF(DAY, S.DATAINI, S.DATAFIN) <= 30
    THEN 1 ELSE 0
  END) AS validos,
  AVG(CASE
    WHEN S.DATAFIN IS NOT NULL AND S.DATAINI IS NOT NULL
      AND S.DATAFIN > S.DATAINI
      AND S.DATAINI > '2022-01-01'
      AND DATEDIFF(DAY, S.DATAINI, S.DATAFIN) <= 30
    THEN CAST(DATEDIFF(MINUTE, S.DATAINI, S.DATAFIN) AS FLOAT) / 60.0
    ELSE NULL
  END) AS mediaHoras
FROM TCFSERVOS S
INNER JOIN TCFOSCAB O ON O.NUOS = S.NUOS
INNER JOIN TGFPRO pro ON S.CODPROD = pro.CODPROD AND pro.USOPROD = 'S'
LEFT JOIN TGFGRU grp ON pro.CODGRUPOPROD = grp.CODGRUPOPROD
WHERE 1=1
-- @WHERE
-- @WHERE_GRUPO
GROUP BY pro.CODGRUPOPROD, grp.DESCRGRUPOPROD
ORDER BY totalServicos DESC
`;

/** 6. Top servicos mais lentos (somente servicos) */
export const tempoServicosTopServicos = `
SELECT TOP 30
  pro.CODPROD AS codProd,
  pro.DESCRPROD AS descrProd,
  COUNT(*) AS totalExecucoes,
  AVG(CAST(DATEDIFF(MINUTE, S.DATAINI, S.DATAFIN) AS FLOAT) / 60.0) AS mediaHoras,
  MIN(CAST(DATEDIFF(MINUTE, S.DATAINI, S.DATAFIN) AS FLOAT) / 60.0) AS minHoras,
  MAX(CAST(DATEDIFF(MINUTE, S.DATAINI, S.DATAFIN) AS FLOAT) / 60.0) AS maxHoras
FROM TCFSERVOS S
INNER JOIN TCFOSCAB O ON O.NUOS = S.NUOS
INNER JOIN TGFPRO pro ON S.CODPROD = pro.CODPROD AND pro.USOPROD = 'S'
WHERE S.DATAFIN IS NOT NULL AND S.DATAINI IS NOT NULL
  AND S.DATAFIN > S.DATAINI
  AND S.DATAINI > '2022-01-01'
  AND DATEDIFF(DAY, S.DATAINI, S.DATAFIN) <= 30
  -- @WHERE
  -- @WHERE_GRUPO
GROUP BY pro.CODPROD, pro.DESCRPROD
HAVING COUNT(*) >= 3
ORDER BY mediaHoras DESC
`;

/** 7. Tendencia mensal (ultimos 24 meses) */
export const tempoServicosTendenciaMensal = `
SELECT
  YEAR(S.DATAINI) AS ano,
  MONTH(S.DATAINI) AS mes,
  COUNT(*) AS totalServicos,
  AVG(CAST(DATEDIFF(MINUTE, S.DATAINI, S.DATAFIN) AS FLOAT) / 60.0) AS mediaHoras
FROM TCFSERVOS S
INNER JOIN TCFOSCAB O ON O.NUOS = S.NUOS
WHERE S.DATAFIN IS NOT NULL AND S.DATAINI IS NOT NULL
  AND S.DATAFIN > S.DATAINI
  AND S.DATAINI > '2022-01-01'
  AND DATEDIFF(DAY, S.DATAINI, S.DATAFIN) <= 30
  AND S.DATAINI >= DATEADD(MONTH, -24, GETDATE())
  -- @WHERE
GROUP BY YEAR(S.DATAINI), MONTH(S.DATAINI)
ORDER BY ano, mes
`;
