export const tendenciaTipoVeiculo = `
SELECT
  CONVERT(VARCHAR(7), O.DTABERTURA, 23) AS mes,
  COUNT(DISTINCT O.NUOS) AS totalOs,
  COUNT(E.SEQUENCIA) AS totalExecucoes,
  CAST(AVG(CASE
    WHEN (CAST(E.DTFIN AS FLOAT) - CAST(E.DTINI AS FLOAT)) * 1440
      BETWEEN 1 AND 43200
    THEN (CAST(E.DTFIN AS FLOAT) - CAST(E.DTINI AS FLOAT)) * 1440
  END) AS INT) AS mediaMinutos
FROM TCFOSCAB O WITH (NOLOCK)
INNER JOIN TGFVEI V WITH (NOLOCK) ON V.CODVEICULO = O.CODVEICULO
INNER JOIN AD_TCFEXEC E WITH (NOLOCK) ON E.NUOS = O.NUOS
WHERE O.CODVEICULO IS NOT NULL
  AND E.DTFIN IS NOT NULL AND E.DTINI IS NOT NULL
  AND RTRIM(CAST(V.AD_TIPOEQPTO AS VARCHAR(MAX))) = '@tipoVeiculo'
  AND O.DTABERTURA >= DATEADD(MONTH, -12, GETDATE())
GROUP BY CONVERT(VARCHAR(7), O.DTABERTURA, 23)
ORDER BY CONVERT(VARCHAR(7), O.DTABERTURA, 23)
`;
