export const topVeiculos = `
SELECT TOP 10
  os.CODVEICULO as codveiculo,
  v.PLACA as placa,
  CAST(v.MARCAMODELO AS VARCHAR(MAX)) as marcaModelo,
  COUNT(*) as totalOs
FROM TCFOSCAB os
LEFT JOIN TGFVEI v ON os.CODVEICULO = v.CODVEICULO
WHERE os.CODVEICULO IS NOT NULL
GROUP BY os.CODVEICULO, v.PLACA, CAST(v.MARCAMODELO AS VARCHAR(MAX))
ORDER BY COUNT(*) DESC
`;
