export const bemDetalhe = `
SELECT
    RTRIM(b.CODBEM) AS codbem,
    b.CODPROD AS codprod,
    CAST(b.DESCRABREV AS VARCHAR(100)) AS descricaoAbreviada,
    CAST(b.DESCRBEM AS VARCHAR(500)) AS descricaoBem,
    CAST(b.DESCRUTILBEM AS VARCHAR(500)) AS descricaoUtilBem,
    CAST(p.DESCRPROD AS VARCHAR(100)) AS categoria,
    ISNULL(b.VLRAQUISICAO, 0) AS vlrAquisicao,
    ISNULL(b.VLRDEP, 0) AS vlrDepreciacao,
    ISNULL(b.VLRSALDO, 0) AS vlrSaldo,
    CONVERT(VARCHAR(10), b.DTCOMPRA, 103) AS dtCompra,
    CONVERT(VARCHAR(10), b.DTBAIXA, 103) AS dtBaixa,
    CONVERT(VARCHAR(10), b.DTINICIODEP, 103) AS dtInicioDep,
    CONVERT(VARCHAR(10), b.DTFIMDEP, 103) AS dtFimDep,
    b.CODEMP AS empresa,
    b.VIDAUTIL AS vidaUtil,
    b.TEMDEPRECIACAO AS temDepreciacao,
    b.NUNOTA AS nunota,
    b.NUNOTABAIXA AS nunotaBaixa,
    CAST(b.NUMCONTRATO AS VARCHAR(50)) AS numContrato,
    ISNULL(b.VLRICMSCIAP, 0) AS vlrIcmsCiap,
    ISNULL(b.VLRTOTDESPESABEM, 0) AS vlrTotDespesaBem,
    ISNULL(b.VALORPRESENTE, 0) AS valorPresente,
    b.CODBEMORIG AS codbemOrig,
    b.CODBEMATUAL AS codbemAtual,
    DATEDIFF(MONTH, b.DTCOMPRA, GETDATE()) AS idadeMeses,
    CASE WHEN ISNULL(b.VLRAQUISICAO, 0) > 0
      THEN CAST(ISNULL(b.VLRDEP, 0) * 100.0 / b.VLRAQUISICAO AS DECIMAL(5,1))
      ELSE 0
    END AS percentualDepreciado,
    v.CODVEICULO AS codveiculo,
    RTRIM(v.PLACA) AS placa,
    CAST(v.MARCAMODELO AS VARCHAR(30)) AS marcaModelo,
    CAST(v.AD_TIPOEQPTO AS VARCHAR(100)) AS tipoEquipamento,
    v.ANOFABRIC AS anofabric,
    v.ANOMOD AS anomod,
    CAST(ISNULL(v.AD_TAG, '') AS VARCHAR(30)) AS tag,
    ISNULL(v.ATIVO, 'S') AS ativo,
    CAST(v.AD_CAPACIDADE AS VARCHAR(50)) AS capacidade,
    CAST(v.AD_FABRICANTE AS VARCHAR(50)) AS fabricante,
    v.KMACUM AS kmAcum,
    CAST(v.RENAVAM AS VARCHAR(30)) AS renavam,
    CAST(v.NUMMOTOR AS VARCHAR(30)) AS numMotor,
    CAST(v.CHASSIS AS VARCHAR(30)) AS chassis,
    CAST(v.COR AS VARCHAR(30)) AS cor,
    v.PESOMAX AS pesoMax,
    v.TARA AS tara,
    CAST(v.COMBUSTIVEL AS VARCHAR(30)) AS combustivel,
    v.PROPRIO AS proprio,
    v.BLOQUEADO AS bloqueado,
    CAST(v.AD_EMCONTRATO AS VARCHAR(10)) AS emContrato,
    CAST(v.AD_TIPOMOTOR AS VARCHAR(50)) AS tipoMotor,
    CASE WHEN mob.CODVEICULO IS NOT NULL THEN 1 ELSE 0 END AS mobilizado,
    CAST(par.RAZAOSOCIAL AS VARCHAR(80)) AS clienteAtual,
    mob.CODPARC AS codparcAtual,
    mob.NUMOS AS numosAtual,
    CONVERT(VARCHAR(10), mob.DHCHAMADA, 103) AS dhChamadaAtual,
    CAST(com.STATUS_VEICULO AS VARCHAR(50)) AS statusComissionamento,
    com.DIASVENCE AS diasVenceComissionamento,
    loc.CODEMP AS locEmpresa,
    loc.CODDEPTO AS locDepartamento,
    CONVERT(VARCHAR(10), loc.DTENTRADA, 103) AS locDtEntrada
FROM SANKHYA.TCIBEM b
LEFT JOIN SANKHYA.TGFPRO p ON p.CODPROD = b.CODPROD
LEFT JOIN SANKHYA.TGFVEI v ON RTRIM(CAST(v.AD_TAG AS VARCHAR(30))) = RTRIM(b.CODBEM)
LEFT JOIN (
    SELECT i2.AD_CODVEICULO AS CODVEICULO, s2.NUMOS, s2.DHCHAMADA, s2.CODPARC,
           ROW_NUMBER() OVER (PARTITION BY i2.AD_CODVEICULO ORDER BY s2.DHCHAMADA DESC) AS rn
    FROM SANKHYA.TCSITE i2
    INNER JOIN SANKHYA.TCSOSE s2 ON s2.NUMOS = i2.NUMOS
    WHERE s2.SITUACAO = 'P' AND i2.AD_CODVEICULO IS NOT NULL
) mob ON mob.CODVEICULO = v.CODVEICULO AND mob.rn = 1
LEFT JOIN SANKHYA.TGFPAR par ON par.CODPARC = mob.CODPARC
LEFT JOIN (
    SELECT CODVEICULO, CAST(STATUS_VEICULO AS VARCHAR(50)) AS STATUS_VEICULO, DIASVENCE,
           ROW_NUMBER() OVER (PARTITION BY CODVEICULO ORDER BY DIASVENCE ASC) AS rn
    FROM SANKHYA.AD_VEICOMISSIONADOS
) com ON com.CODVEICULO = v.CODVEICULO AND com.rn = 1
LEFT JOIN (
    SELECT CODBEM, CODEMP, CODDEPTO, DTENTRADA,
           ROW_NUMBER() OVER (PARTITION BY CODBEM ORDER BY DTENTRADA DESC) AS rn
    FROM SANKHYA.TCILOC
) loc ON loc.CODBEM = b.CODBEM AND loc.rn = 1
WHERE RTRIM(b.CODBEM) = '@codbem' AND (@codprod = 0 OR b.CODPROD = @codprod)
`;
