export const bemDocumentos = `
SELECT
    d.CODVEICULO AS codveiculo,
    d.CODDOC AS coddoc,
    CONVERT(VARCHAR(10), d.VIGENCIAINI, 103) AS vigenciaIni,
    CONVERT(VARCHAR(10), d.VIGENCIAFIN, 103) AS vigenciaFin,
    CASE
      WHEN d.VIGENCIAFIN < GETDATE() THEN 'VENCIDO'
      WHEN d.VIGENCIAFIN <= DATEADD(DAY, 30, GETDATE()) THEN 'VENCE_EM_30D'
      ELSE 'VIGENTE'
    END AS status
FROM SANKHYA.TGFVEIDOC d
INNER JOIN SANKHYA.TGFVEI v ON v.CODVEICULO = d.CODVEICULO
WHERE RTRIM(CAST(v.AD_TAG AS VARCHAR(30))) = '@codbem'
ORDER BY d.VIGENCIAFIN DESC
`;
