export const bemOsHistorico = `
SELECT
    s.NUMOS AS numos,
    s.SITUACAO AS situacao,
    CONVERT(VARCHAR(10), s.DHCHAMADA, 103) AS dhChamada,
    CONVERT(VARCHAR(10), s.DTFECHAMENTO, 103) AS dtFechamento,
    s.CODPARC AS codparc,
    CAST(par.RAZAOSOCIAL AS VARCHAR(80)) AS cliente,
    CAST(srv.DESCRICAO AS VARCHAR(100)) AS servico,
    i.AD_KMINI AS kmIni,
    i.AD_KMFIM AS kmFim,
    i.VLRCOBRADO AS vlrCobrado
FROM SANKHYA.TCSITE i
INNER JOIN SANKHYA.TCSOSE s ON s.NUMOS = i.NUMOS
INNER JOIN SANKHYA.TGFVEI v ON v.CODVEICULO = i.AD_CODVEICULO
LEFT JOIN SANKHYA.TGFPAR par ON par.CODPARC = s.CODPARC
LEFT JOIN SANKHYA.TCSSER srv ON srv.CODSERV = i.CODSERV
WHERE RTRIM(CAST(v.AD_TAG AS VARCHAR(30))) = '@codbem'
ORDER BY s.DHCHAMADA DESC
`;
