export const categoriasResumo = `
SELECT
    b.CODPROD AS codprod,
    CAST(p.DESCRPROD AS VARCHAR(100)) AS categoria,
    COUNT(*) AS quantidade,
    ISNULL(SUM(b.VLRAQUISICAO), 0) AS valorTotal,
    SUM(CASE WHEN mob.CODVEICULO IS NOT NULL THEN 1 ELSE 0 END) AS mobilizados,
    SUM(CASE WHEN mob.CODVEICULO IS NULL THEN 1 ELSE 0 END) AS disponiveis,
    AVG(DATEDIFF(MONTH, b.DTCOMPRA, GETDATE())) AS idadeMedia,
    CASE WHEN COUNT(*) > 0
      THEN CAST(SUM(CASE WHEN mob.CODVEICULO IS NOT NULL THEN 1 ELSE 0 END) * 100.0 / COUNT(*) AS DECIMAL(5,1))
      ELSE 0
    END AS percentualMobilizado
FROM SANKHYA.TCIBEM b
LEFT JOIN SANKHYA.TGFPRO p ON p.CODPROD = b.CODPROD
LEFT JOIN SANKHYA.TGFVEI v ON CAST(v.AD_TAG AS VARCHAR(30)) = b.CODBEM
LEFT JOIN (
    SELECT DISTINCT i2.AD_CODVEICULO AS CODVEICULO
    FROM SANKHYA.TCSITE i2
    INNER JOIN SANKHYA.TCSOSE s2 ON s2.NUMOS = i2.NUMOS
    WHERE s2.SITUACAO = 'P' AND i2.AD_CODVEICULO IS NOT NULL
) mob ON mob.CODVEICULO = v.CODVEICULO
WHERE b.DTBAIXA IS NULL AND b.CODBEM NOT LIKE '%<TODOS>%'
GROUP BY b.CODPROD, CAST(p.DESCRPROD AS VARCHAR(100))
ORDER BY ISNULL(SUM(b.VLRAQUISICAO), 0) DESC
`;
