export const kpiTotalBens = `
SELECT COUNT(*) AS val FROM SANKHYA.TCIBEM WHERE DTBAIXA IS NULL
`;

export const kpiValorPatrimonio = `
SELECT ISNULL(SUM(VLRAQUISICAO), 0) AS val FROM SANKHYA.TCIBEM WHERE DTBAIXA IS NULL
`;

export const kpiMobilizados = `
SELECT COUNT(DISTINCT i.AD_CODVEICULO) AS val FROM SANKHYA.TCSITE i INNER JOIN SANKHYA.TCSOSE s ON s.NUMOS = i.NUMOS WHERE s.SITUACAO = 'P' AND i.AD_CODVEICULO IS NOT NULL
`;

export const kpiTotalVeiculos = `
SELECT COUNT(*) AS val FROM SANKHYA.TGFVEI WHERE ATIVO = 'S'
`;

export const kpiSemPatrimonio = `
SELECT COUNT(*) AS val FROM SANKHYA.TGFVEI v LEFT JOIN SANKHYA.TCIBEM b ON RTRIM(CAST(b.CODBEM AS VARCHAR(30))) = RTRIM(CAST(v.AD_TAG AS VARCHAR(30))) WHERE b.CODBEM IS NULL AND v.ATIVO = 'S'
`;

export const kpiTotalBaixados = `
SELECT COUNT(*) AS val FROM SANKHYA.TCIBEM WHERE DTBAIXA IS NOT NULL
`;

export const kpiAlertasComissionamento = `
SELECT COUNT(*) AS val FROM SANKHYA.AD_VEICOMISSIONADOS WHERE DIASVENCE <= 30 AND DIASVENCE >= 0
`;
