export const depreciacaoConsolidada = `
SELECT
    CAST(p.DESCRPROD AS VARCHAR(100)) AS categoria,
    COUNT(*) AS quantidade,
    ISNULL(SUM(b.VLRAQUISICAO), 0) AS vlrAquisicaoTotal,
    ISNULL(SUM(b.VLRDEP), 0) AS vlrDepreciacaoTotal,
    ISNULL(SUM(b.VLRSALDO), 0) AS vlrSaldoTotal,
    CASE WHEN SUM(ISNULL(b.VLRAQUISICAO, 0)) > 0
      THEN CAST(SUM(ISNULL(b.VLRDEP, 0)) * 100.0 / SUM(b.VLRAQUISICAO) AS DECIMAL(5,1))
      ELSE 0
    END AS percentualMedio,
    SUM(CASE WHEN ISNULL(b.VLRDEP, 0) >= ISNULL(b.VLRAQUISICAO, 0) AND ISNULL(b.VLRAQUISICAO, 0) > 0 THEN 1 ELSE 0 END) AS completos,
    SUM(CASE WHEN ISNULL(b.VLRDEP, 0) > 0 AND ISNULL(b.VLRDEP, 0) < ISNULL(b.VLRAQUISICAO, 0) THEN 1 ELSE 0 END) AS parciais,
    SUM(CASE WHEN ISNULL(b.VLRDEP, 0) = 0 THEN 1 ELSE 0 END) AS semDepreciacao
FROM SANKHYA.TCIBEM b
LEFT JOIN SANKHYA.TGFPRO p ON p.CODPROD = b.CODPROD
WHERE b.DTBAIXA IS NULL AND b.CODBEM NOT LIKE '%<TODOS>%'
GROUP BY CAST(p.DESCRPROD AS VARCHAR(100))
ORDER BY ISNULL(SUM(b.VLRAQUISICAO), 0) DESC
`;
