export const listaBens = `
SELECT
    RTRIM(b.CODBEM) AS codbem,
    b.CODPROD AS codprod,
    CAST(b.DESCRABREV AS VARCHAR(100)) AS descricaoAbreviada,
    CAST(p.DESCRPROD AS VARCHAR(100)) AS categoria,
    ISNULL(b.VLRAQUISICAO, 0) AS vlrAquisicao,
    ISNULL(b.VLRDEP, 0) AS vlrDepreciacao,
    ISNULL(b.VLRSALDO, 0) AS vlrSaldo,
    CONVERT(VARCHAR(10), b.DTCOMPRA, 103) AS dtCompra,
    CONVERT(VARCHAR(10), b.DTBAIXA, 103) AS dtBaixa,
    b.CODEMP AS empresa,
    b.VIDAUTIL AS vidaUtil,
    v.CODVEICULO AS codveiculo,
    RTRIM(v.PLACA) AS placa,
    CAST(v.MARCAMODELO AS VARCHAR(30)) AS marcaModelo,
    CAST(v.AD_TIPOEQPTO AS VARCHAR(100)) AS tipoEquipamento,
    v.ANOFABRIC AS anofabric,
    v.ANOMOD AS anomod,
    CAST(ISNULL(v.AD_TAG, '') AS VARCHAR(30)) AS tag,
    ISNULL(v.ATIVO, 'S') AS ativo,
    CAST(v.AD_CAPACIDADE AS VARCHAR(50)) AS capacidade,
    CAST(v.AD_FABRICANTE AS VARCHAR(50)) AS fabricante,
    v.KMACUM AS kmAcum,
    CASE WHEN mob.CODVEICULO IS NOT NULL THEN 1 ELSE 0 END AS mobilizado,
    CAST(par.RAZAOSOCIAL AS VARCHAR(80)) AS clienteAtual,
    mob.CODPARC AS codparcAtual,
    mob.NUMOS AS numosAtual,
    CONVERT(VARCHAR(10), mob.DHCHAMADA, 103) AS dhChamadaAtual,
    CAST(com.STATUS_VEICULO AS VARCHAR(50)) AS statusComissionamento,
    com.DIASVENCE AS diasVenceComissionamento,
    DATEDIFF(MONTH, b.DTCOMPRA, GETDATE()) AS idadeMeses,
    CASE WHEN ISNULL(b.VLRAQUISICAO, 0) > 0
      THEN CAST(ISNULL(b.VLRDEP, 0) * 100.0 / b.VLRAQUISICAO AS DECIMAL(5,1))
      ELSE 0
    END AS percentualDepreciado,
    1 AS temPatrimonio
FROM SANKHYA.TCIBEM b
LEFT JOIN SANKHYA.TGFPRO p ON p.CODPROD = b.CODPROD
LEFT JOIN SANKHYA.TGFVEI v ON RTRIM(CAST(v.AD_TAG AS VARCHAR(30))) = RTRIM(b.CODBEM)
LEFT JOIN (
    SELECT i2.AD_CODVEICULO AS CODVEICULO, s2.NUMOS, s2.DHCHAMADA, s2.CODPARC,
           ROW_NUMBER() OVER (PARTITION BY i2.AD_CODVEICULO ORDER BY s2.DHCHAMADA DESC) AS rn
    FROM SANKHYA.TCSITE i2
    INNER JOIN SANKHYA.TCSOSE s2 ON s2.NUMOS = i2.NUMOS
    WHERE s2.SITUACAO = 'P' AND i2.AD_CODVEICULO IS NOT NULL
) mob ON mob.CODVEICULO = v.CODVEICULO AND mob.rn = 1
LEFT JOIN SANKHYA.TGFPAR par ON par.CODPARC = mob.CODPARC
LEFT JOIN (
    SELECT CODVEICULO, CAST(STATUS_VEICULO AS VARCHAR(50)) AS STATUS_VEICULO, DIASVENCE,
           ROW_NUMBER() OVER (PARTITION BY CODVEICULO ORDER BY DIASVENCE ASC) AS rn
    FROM SANKHYA.AD_VEICOMISSIONADOS
) com ON com.CODVEICULO = v.CODVEICULO AND com.rn = 1
WHERE b.CODBEM NOT LIKE '%<TODOS>%'
ORDER BY b.CODBEM
`;
