export const mobilizacaoPorVeiculo = `
SELECT
    v.CODVEICULO AS codveiculo,
    b.CODBEM AS codbem,
    CAST(ISNULL(v.AD_TAG, '') AS VARCHAR(30)) AS tag,
    RTRIM(v.PLACA) AS placa,
    CAST(v.AD_TIPOEQPTO AS VARCHAR(100)) AS tipoEquipamento,
    CAST(p.DESCRPROD AS VARCHAR(100)) AS categoria,
    ISNULL(b.VLRAQUISICAO, 0) AS vlrAquisicao,
    s.NUMOS AS numos,
    CONVERT(VARCHAR(10), s.DHCHAMADA, 103) AS dhChamada,
    DATEDIFF(DAY, s.DHCHAMADA, GETDATE()) AS dias,
    s.CODPARC AS codparc,
    CAST(par.RAZAOSOCIAL AS VARCHAR(80)) AS cliente,
    CAST(srv.DESCRICAO AS VARCHAR(100)) AS servico
FROM SANKHYA.TCSITE i
INNER JOIN SANKHYA.TCSOSE s ON s.NUMOS = i.NUMOS
INNER JOIN SANKHYA.TGFVEI v ON v.CODVEICULO = i.AD_CODVEICULO
LEFT JOIN SANKHYA.TCIBEM b ON b.CODBEM = CAST(v.AD_TAG AS VARCHAR(30))
LEFT JOIN SANKHYA.TGFPRO p ON p.CODPROD = b.CODPROD
LEFT JOIN SANKHYA.TGFPAR par ON par.CODPARC = s.CODPARC
LEFT JOIN SANKHYA.TCSSER srv ON srv.CODSERV = i.CODSERV
WHERE s.SITUACAO = 'P' AND i.AD_CODVEICULO IS NOT NULL
ORDER BY v.AD_TAG
`;
