export const topClientes = `
SELECT TOP 10
    CAST(par.RAZAOSOCIAL AS VARCHAR(80)) AS cliente,
    s.CODPARC AS codparc,
    COUNT(DISTINCT i.AD_CODVEICULO) AS veiculos,
    ISNULL(SUM(b.VLRAQUISICAO), 0) AS valorPatrimonio
FROM SANKHYA.TCSITE i
INNER JOIN SANKHYA.TCSOSE s ON s.NUMOS = i.NUMOS
INNER JOIN SANKHYA.TGFVEI v ON v.CODVEICULO = i.AD_CODVEICULO
LEFT JOIN SANKHYA.TCIBEM b ON b.CODBEM = CAST(v.AD_TAG AS VARCHAR(30))
LEFT JOIN SANKHYA.TGFPAR par ON par.CODPARC = s.CODPARC
WHERE s.SITUACAO = 'P' AND i.AD_CODVEICULO IS NOT NULL
GROUP BY s.CODPARC, CAST(par.RAZAOSOCIAL AS VARCHAR(80))
ORDER BY COUNT(DISTINCT i.AD_CODVEICULO) DESC
`;
