export const valorPorCategoria = `
SELECT
    RTRIM(CAST(p.DESCRPROD AS VARCHAR(100))) AS categoria,
    ISNULL(SUM(b.VLRAQUISICAO), 0) AS valor,
    COUNT(*) AS quantidade
FROM SANKHYA.TCIBEM b
LEFT JOIN SANKHYA.TGFPRO p ON p.CODPROD = b.CODPROD
WHERE b.DTBAIXA IS NULL AND b.CODBEM NOT LIKE '%<TODOS>%'
GROUP BY CAST(p.DESCRPROD AS VARCHAR(100))
HAVING ISNULL(SUM(b.VLRAQUISICAO), 0) > 0
ORDER BY ISNULL(SUM(b.VLRAQUISICAO), 0) DESC
`;
