export const getByPeriodo = `
SELECT * FROM (
  SELECT
    S.CODIGO,
    S.SEQ,
    CAST(S.DESCRITIVO AS VARCHAR(MAX)) AS DESCRITIVO,
    S.CODPROD,
    P.DESCRPROD,
    S.QTD,
    S.GERAOS,
    S.NUOS,
    S.DTPROGRAMACAO,
    A.DTINCLUSAO,
    A.CODVEICULO,
    A.TAG,
    A.STATUSOS,
    ROW_NUMBER() OVER (ORDER BY A.DTINCLUSAO DESC, S.CODIGO, S.SEQ) AS RowNum
  FROM AD_APONTSOL S
  INNER JOIN AD_APONTAMENTO A ON A.CODIGO = S.CODIGO
  LEFT JOIN TGFPRO P ON P.CODPROD = S.CODPROD
  WHERE A.DTINCLUSAO >= '@DTINI'
    AND A.DTINCLUSAO < '@DTFIM'
) AS T
WHERE RowNum > @OFFSET AND RowNum <= (@OFFSET + @LIMIT)
`;
