export const getServicosFrequentes = `
SELECT TOP 20
  CAST(DESCRITIVO AS VARCHAR(200)) AS DESCRITIVO,
  COUNT(*) AS QTD_APONTAMENTOS
FROM AD_APONTSOL
WHERE DESCRITIVO IS NOT NULL
GROUP BY CAST(DESCRITIVO AS VARCHAR(200))
ORDER BY QTD_APONTAMENTOS DESC
`;
