export const getByProduto = `
SELECT TOP 50
  S.CODPROD,
  P.DESCRPROD,
  COUNT(*) AS QTD_UTILIZACOES,
  SUM(S.QTD) AS QTD_TOTAL,
  SUM(CASE WHEN S.NUOS IS NOT NULL THEN 1 ELSE 0 END) AS QTD_COM_OS,
  MIN(A.DTINCLUSAO) AS PRIMEIRO_USO,
  MAX(A.DTINCLUSAO) AS ULTIMO_USO
FROM AD_APONTSOL S
INNER JOIN AD_APONTAMENTO A ON A.CODIGO = S.CODIGO
LEFT JOIN TGFPRO P ON P.CODPROD = S.CODPROD
WHERE S.CODPROD IS NOT NULL
GROUP BY S.CODPROD, P.DESCRPROD
ORDER BY QTD_UTILIZACOES DESC
`;
