export const getByVeiculo = `
SELECT
  A.CODVEICULO,
  V.PLACA,
  CAST(V.MARCAMODELO AS VARCHAR(MAX)) AS MARCAMODELO,
  V.AD_TAG AS TAG,
  COUNT(*) AS QTD_SERVICOS,
  SUM(CASE WHEN S.NUOS IS NOT NULL THEN 1 ELSE 0 END) AS QTD_COM_OS,
  SUM(CASE WHEN S.GERAOS = 'S' AND S.NUOS IS NULL THEN 1 ELSE 0 END) AS QTD_PENDENTES,
  MIN(A.DTINCLUSAO) AS PRIMEIRO_APONTAMENTO,
  MAX(A.DTINCLUSAO) AS ULTIMO_APONTAMENTO
FROM AD_APONTSOL S
INNER JOIN AD_APONTAMENTO A ON A.CODIGO = S.CODIGO
LEFT JOIN TGFVEI V ON V.CODVEICULO = A.CODVEICULO
WHERE A.CODVEICULO IS NOT NULL
-- @WHERE
GROUP BY A.CODVEICULO, V.PLACA, CAST(V.MARCAMODELO AS VARCHAR(MAX)), V.AD_TAG
ORDER BY QTD_SERVICOS DESC
`;
