export const getResumo = `
SELECT
  COUNT(*) AS TOTAL_SERVICOS,
  COUNT(DISTINCT S.CODIGO) AS TOTAL_APONTAMENTOS,
  SUM(CASE WHEN S.NUOS IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL_COM_OS,
  SUM(CASE WHEN S.GERAOS = 'S' AND S.NUOS IS NULL THEN 1 ELSE 0 END) AS TOTAL_PENDENTES_OS,
  SUM(CASE WHEN S.GERAOS = 'S' THEN 1 ELSE 0 END) AS TOTAL_GERA_OS,
  SUM(CASE WHEN S.CODPROD IS NOT NULL THEN 1 ELSE 0 END) AS TOTAL_COM_PRODUTO,
  COUNT(DISTINCT S.CODPROD) AS PRODUTOS_DISTINTOS,
  COUNT(DISTINCT A.CODVEICULO) AS VEICULOS_DISTINTOS,
  CASE
    WHEN COUNT(*) > 0
    THEN (SUM(CASE WHEN S.NUOS IS NOT NULL THEN 1 ELSE 0 END) * 100) / COUNT(*)
    ELSE 0
  END AS PERC_COM_OS,
  CASE
    WHEN SUM(CASE WHEN S.GERAOS = 'S' THEN 1 ELSE 0 END) > 0
    THEN (SUM(CASE WHEN S.GERAOS = 'S' AND S.NUOS IS NULL THEN 1 ELSE 0 END) * 100)
      / SUM(CASE WHEN S.GERAOS = 'S' THEN 1 ELSE 0 END)
    ELSE 0
  END AS PERC_PENDENTES
FROM AD_APONTSOL S
LEFT JOIN AD_APONTAMENTO A ON A.CODIGO = S.CODIGO
`;
