export const getByApontamento = `
SELECT
  S.SEQ,
  CAST(S.DESCRITIVO AS VARCHAR(MAX)) AS DESCRITIVO,
  S.CODPROD,
  P.DESCRPROD,
  S.QTD,
  S.GERAOS,
  S.NUOS,
  S.DTPROGRAMACAO,
  S.HR,
  S.KM
FROM AD_APONTSOL S
LEFT JOIN TGFPRO P ON P.CODPROD = S.CODPROD
WHERE S.CODIGO = @CODIGO
ORDER BY S.SEQ
`;
