export const getTimelineVeiculo = `
SELECT * FROM (
  SELECT
    A.DTINCLUSAO,
    A.CODIGO AS CODAPONTAMENTO,
    S.SEQ,
    CAST(S.DESCRITIVO AS VARCHAR(MAX)) AS DESCRITIVO,
    S.CODPROD,
    P.DESCRPROD,
    S.QTD,
    S.GERAOS,
    S.NUOS,
    S.DTPROGRAMACAO,
    A.STATUSOS,
    A.KM,
    A.HORIMETRO,
    V.PLACA,
    CAST(V.MARCAMODELO AS VARCHAR(MAX)) AS MARCAMODELO,
    ROW_NUMBER() OVER (ORDER BY A.DTINCLUSAO DESC, S.SEQ) AS RowNum
  FROM AD_APONTSOL S
  INNER JOIN AD_APONTAMENTO A ON A.CODIGO = S.CODIGO
  LEFT JOIN TGFPRO P ON P.CODPROD = S.CODPROD
  LEFT JOIN TGFVEI V ON V.CODVEICULO = A.CODVEICULO
  WHERE A.CODVEICULO = @CODVEICULO
) AS T
WHERE RowNum > @OFFSET AND RowNum <= (@OFFSET + @LIMIT)
`;
