export const getByApontamento = `
SELECT
  S.CODIGO,
  S.SEQ,
  CAST(S.DESCRITIVO AS VARCHAR(MAX)) AS DESCRITIVO,
  S.CODPROD,
  P.DESCRPROD,
  S.QTD,
  S.GERAOS,
  S.NUOS,
  S.DTPROGRAMACAO,
  S.HR,
  S.KM,
  P.CODGRUPOPROD,
  (SELECT RTRIM(GRU.DESCRGRUPOPROD)
    FROM TGFGRU GRU
    WHERE GRU.CODGRUPOPROD = P.CODGRUPOPROD) AS DESCRGRUPOPROD,
  (SELECT CASE OS.STATUS
    WHEN 'A' THEN 'Aberta'
    WHEN 'R' THEN 'Reaberta'
    WHEN 'E' THEN 'Em execucao'
    WHEN 'F' THEN 'Finalizada'
    ELSE NULL END
  FROM TCFOSCAB OS
  WHERE OS.NUOS = S.NUOS) AS STATUSOS
FROM AD_APONTSOL S
LEFT JOIN TGFPRO P ON P.CODPROD = S.CODPROD
WHERE S.CODIGO = @CODIGO
ORDER BY S.SEQ
`;
