export const getComOs = `
SELECT * FROM (
  SELECT
    S.CODIGO,
    S.SEQ,
    CAST(S.DESCRITIVO AS VARCHAR(MAX)) AS DESCRITIVO,
    S.CODPROD,
    P.DESCRPROD,
    S.QTD,
    S.NUOS,
    S.DTPROGRAMACAO,
    OS.STATUS AS STATUS_OS,
    CONVERT(VARCHAR(19), OS.DTABERTURA, 120) AS DTABERTURA_OS,
    OS.DATAFIN AS DATAFIN_OS,
    OS.CODPARC AS CODPARC_OS,
    A.CODVEICULO,
    A.TAG,
    A.DTINCLUSAO,
    ROW_NUMBER() OVER (ORDER BY S.NUOS DESC) AS RowNum
  FROM AD_APONTSOL S
  INNER JOIN TCFOSCAB OS ON OS.NUOS = S.NUOS
  LEFT JOIN TGFPRO P ON P.CODPROD = S.CODPROD
  LEFT JOIN AD_APONTAMENTO A ON A.CODIGO = S.CODIGO
  WHERE S.NUOS IS NOT NULL
) AS T
WHERE RowNum > @OFFSET AND RowNum <= (@OFFSET + @LIMIT)
`;
