export const getPendentesSemOs = `
SELECT * FROM (
  SELECT
    S.CODIGO,
    S.SEQ,
    CAST(S.DESCRITIVO AS VARCHAR(MAX)) AS DESCRITIVO,
    S.CODPROD,
    P.DESCRPROD,
    S.QTD,
    S.DTPROGRAMACAO,
    A.DTINCLUSAO,
    A.CODVEICULO,
    A.TAG,
    A.STATUSOS,
    V.PLACA,
    CAST(V.MARCAMODELO AS VARCHAR(MAX)) AS MARCAMODELO,
    ROW_NUMBER() OVER (ORDER BY A.DTINCLUSAO DESC, S.SEQ) AS RowNum
  FROM AD_APONTSOL S
  INNER JOIN AD_APONTAMENTO A ON A.CODIGO = S.CODIGO
  LEFT JOIN TGFPRO P ON P.CODPROD = S.CODPROD
  LEFT JOIN TGFVEI V ON V.CODVEICULO = A.CODVEICULO
  WHERE S.GERAOS = 'S'
    AND S.NUOS IS NULL
) AS T
WHERE RowNum > @OFFSET AND RowNum <= (@OFFSET + @LIMIT)
`;
