export const porApontamento = `
SELECT
  S.CODIGO,
  S.SEQ,
  S.DESCRITIVO,
  S.CODPROD,
  P.DESCRPROD,
  S.QTD,
  S.GERAOS,
  S.NUOS,
  S.DTPROGRAMACAO,
  S.HR,
  S.KM
FROM AD_APONTSOL S WITH (NOLOCK)
LEFT JOIN TGFPRO P ON P.CODPROD = S.CODPROD
WHERE S.CODIGO = @CODIGO
ORDER BY S.SEQ
`;
