export const servicosFrequentes = `
SELECT TOP @LIMIT
  CAST(DESCRITIVO AS VARCHAR(200)) AS descritivo,
  COUNT(*) AS quantidade,
  CAST(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM AD_APONTSOL WITH (NOLOCK) WHERE DESCRITIVO IS NOT NULL) AS DECIMAL(5,2)) AS percentual
FROM AD_APONTSOL WITH (NOLOCK)
WHERE DESCRITIVO IS NOT NULL
GROUP BY CAST(DESCRITIVO AS VARCHAR(200))
ORDER BY quantidade DESC
`;
