/**
 * Queries for the "Detalhamento Completo" feature.
 * Comprehensive investigation of a NUNOTA: cab, items, TOP, variacoes,
 * related documents, and cross-references.
 */

/** Related docs by same parceiro + products. @codparc @codprod_list @nunota */
export const cabRelacionadosPorProduto = `
SELECT DISTINCT C.NUNOTA,C.NUMNOTA,C.CODTIPOPER,CONVERT(VARCHAR(10),C.DTNEG,120) AS DTNEG,C.CODPARC,P.NOMEPARC AS PARCEIRO_NOME,C.CODCENCUS,C.VLRNOTA,C.STATUSNOTA,C.CODUSUINC,U.NOMEUSU AS NOME_USUARIO,C.OBSERVACAO
FROM TGFCAB C
INNER JOIN TGFITE I ON I.NUNOTA=C.NUNOTA AND I.CODPROD IN (@codprod_list)
LEFT JOIN TGFPAR P ON P.CODPARC=C.CODPARC
LEFT JOIN TSIUSU U ON U.CODUSU=C.CODUSUINC
WHERE C.CODPARC=@codparc AND C.NUNOTA<>@nunota
ORDER BY C.DTNEG DESC
`;

/** Docs linked by AD_NUNOTAREQORIG. @nunota */
export const cabLinkedByReqOrig = `
SELECT C.NUNOTA,C.NUMNOTA,C.CODTIPOPER,CONVERT(VARCHAR(10),C.DTNEG,120) AS DTNEG,C.CODPARC,P.NOMEPARC AS PARCEIRO_NOME,C.VLRNOTA,C.STATUSNOTA,C.CODUSUINC,U.NOMEUSU AS NOME_USUARIO,C.AD_NUNOTAREQORIG,C.OBSERVACAO
FROM TGFCAB C
LEFT JOIN TGFPAR P ON P.CODPARC=C.CODPARC
LEFT JOIN TSIUSU U ON U.CODUSU=C.CODUSUINC
WHERE (C.AD_NUNOTAREQORIG=@nunota AND C.NUNOTA<>@nunota) OR C.NUNOTA IN (SELECT C2.NUNOTA FROM TGFCAB C2 WHERE C2.AD_NUNOTAREQORIG=(SELECT C3.AD_NUNOTAREQORIG FROM TGFCAB C3 WHERE C3.NUNOTA=@nunota) AND C2.NUNOTA<>@nunota AND C2.AD_NUNOTAREQORIG IS NOT NULL AND C2.AD_NUNOTAREQORIG<>0)
ORDER BY C.DTNEG DESC
`;

/** TGFVAR entries for this NUNOTA (part 1: var data + user) */
export const cabLinkedByVarPart1 = `
SELECT V.NUNOTA,V.NUNOTAORIG AS NUNOTA_ORIGEM,V.SEQUENCIA
FROM TGFVAR V
WHERE V.NUNOTA=@nunota OR V.NUNOTAORIG=@nunota
ORDER BY V.SEQUENCIA DESC
`;

/** TGFVAR entries (part 2: CAB data for each NUNOTA in var) */
export const cabLinkedByVarPart2 = `
SELECT V.NUNOTA,V.SEQUENCIA,C.NUMNOTA,C.CODTIPOPER,T.DESCROPER AS TIPO_OPER_DESCRICAO,CONVERT(VARCHAR(10),C.DTNEG,120) AS DTNEG,C.VLRNOTA,C.STATUSNOTA,C.CODPARC,P.NOMEPARC AS PARCEIRO_NOME
FROM TGFVAR V
LEFT JOIN TGFCAB C ON C.NUNOTA=V.NUNOTA
LEFT JOIN TGFPAR P ON P.CODPARC=C.CODPARC
LEFT JOIN TGFTOP T ON T.CODTIPOPER=C.CODTIPOPER AND T.DHALTER=(SELECT MAX(X.DHALTER) FROM TGFTOP X WHERE X.CODTIPOPER=C.CODTIPOPER AND X.DHALTER<=C.DTNEG)
WHERE V.NUNOTA=@nunota OR V.NUNOTAORIG=@nunota
`;

/** Docs where NUNOTAORIG references this NUNOTA via TGFVAR. @nunota */
export const cabReferenciadoEmItens = `
SELECT DISTINCT C.NUNOTA,C.NUMNOTA,C.CODTIPOPER,CONVERT(VARCHAR(10),C.DTNEG,120) AS DTNEG,C.VLRNOTA,C.STATUSNOTA,C.CODPARC,P.NOMEPARC AS PARCEIRO_NOME,C.CODUSUINC,U.NOMEUSU AS NOME_USUARIO
FROM TGFCAB C
INNER JOIN TGFVAR V ON V.NUNOTA=C.NUNOTA AND V.NUNOTAORIG=@nunota
LEFT JOIN TGFPAR P ON P.CODPARC=C.CODPARC
LEFT JOIN TSIUSU U ON U.CODUSU=C.CODUSUINC
ORDER BY C.DTNEG DESC
`;

/**
 * Quick existence check + basic info even for deleted records.
 * Checks if NUNOTA ever existed by looking at TGFVAR references.
 * @param @nunota
 */
export const cabExistenciaCheck = `
SELECT
    CASE WHEN EXISTS(SELECT 1 FROM TGFCAB WHERE NUNOTA = @nunota) THEN 1 ELSE 0 END AS existeNoCAB,
    (SELECT COUNT(*) FROM TGFVAR WHERE NUNOTA = @nunota OR NUNOTAORIG = @nunota) AS refsNoVAR
`;
