/**
 * Get liberation records from TGFLIB for a given NUNOTA.
 * @param @nunota
 */
export const cabLiberacoes = `
SELECT
    LIB.NUNOTA, LIB.CODUSU,
    USU.NOMEUSU AS NOME_USUARIO,
    CONVERT(VARCHAR(19), LIB.DT, 120) AS DT,
    LIB.LIBERACOES, LIB.OBS, LIB.VLRTOTAL
FROM TGFLIB LIB
LEFT JOIN TSIUSU USU ON USU.CODUSU = LIB.CODUSU
WHERE LIB.NUNOTA = @nunota
ORDER BY LIB.DT
`;

/**
 * Get system liberations from TSILIB for a given NUNOTA in TGFCAB context.
 * @param @nunota
 */
export const cabLiberacoesSistema = `
SELECT L.NUCHAVE,L.TABELA,L.EVENTO,L.SEQUENCIA,L.CODUSUSOLICIT,U1.NOMEUSU AS NOME_SOLICITANTE,CONVERT(VARCHAR(19),L.DHSOLICIT,120) AS DHSOLICIT,L.CODUSULIB,U2.NOMEUSU AS NOME_LIBERADOR,CONVERT(VARCHAR(19),L.DHLIB,120) AS DHLIB,L.VLRLIMITE,L.VLRATUAL,L.VLRLIBERADO,L.VLRTOTAL,L.OBSERVACAO,L.OBSLIB,L.REPROVADO,L.SEQCASCATA
FROM TSILIB L
LEFT JOIN TSIUSU U1 ON U1.CODUSU=L.CODUSUSOLICIT
LEFT JOIN TSIUSU U2 ON U2.CODUSU=L.CODUSULIB
WHERE L.NUCHAVE=@nunota AND L.TABELA='TGFCAB'
ORDER BY L.DHSOLICIT,L.SEQUENCIA
`;
