/**
 * Lixeira queries — TGFCAB_EXC and TGFITE_EXC
 * Split into two parts to stay under API Mother query length limit (~500 chars)
 */

/** Part 1: Basic fields from TGFCAB_EXC + parceiro name */
export const cabLixeiraCabPart1 = `
SELECT E.NUNOTA,E.NUMNOTA,E.CODEMP,E.CODPARC,P.NOMEPARC AS PARCEIRO_NOME,E.VLRNOTA,E.STATUSNOTA,E.CODTIPOPER,E.TIPMOV,CONVERT(VARCHAR(10),E.DTNEG,120) AS DTNEG,E.NUMCOTACAO,E.APROVADO,E.PENDENTE,E.CODCENCUS,E.CODVEND,E.OBSERVACAO,E.HOSTNAME,CONVERT(VARCHAR(19),E.DHEXCLUSAO,120) AS DHEXCLUSAO
FROM TGFCAB_EXC E
LEFT JOIN TGFPAR P ON P.CODPARC=E.CODPARC
WHERE E.NUNOTA=@nunota
`;

/** Part 2: Lookup descriptions (centro custo, vendedor, usuario, TOP) */
export const cabLixeiraCabPart2 = `
SELECT E.NUNOTA,C.DESCRCENCUS AS CENTRO_CUSTO_DESCRICAO,V.APELIDO AS VENDEDOR_NOME,T.DESCROPER AS TIPO_OPER_DESCRICAO
FROM TGFCAB_EXC E
LEFT JOIN TSICUS C ON C.CODCENCUS=E.CODCENCUS
LEFT JOIN TGFVEN V ON V.CODVEND=E.CODVEND
LEFT JOIN TGFTOP T ON T.CODTIPOPER=E.CODTIPOPER AND T.DHALTER=(SELECT MAX(T2.DHALTER) FROM TGFTOP T2 WHERE T2.CODTIPOPER=E.CODTIPOPER AND T2.DHALTER<=E.DTNEG)
WHERE E.NUNOTA=@nunota
`;

/** Deleted items from TGFITE_EXC */
export const cabLixeiraItens = `
SELECT I.NUNOTA,I.SEQUENCIA,I.CODPROD,P.DESCRPROD AS PRODUTO_DESCRICAO,P.REFERENCIA AS PRODUTO_REFERENCIA,I.QTDNEG,I.VLRUNIT,I.VLRTOT,I.CODVOL AS UNIDADE,I.VLRDESC,I.PERCDESC,I.VLRIPI,I.VLRICMS,I.OBSERVACAO AS OBSERVACAO_ITEM,I.USUARIO AS EXCLUIDO_POR,I.HOSTNAME AS EXCLUIDO_DE,CONVERT(VARCHAR(19),I.DHEXCLUSAO,120) AS DHEXCLUSAO
FROM TGFITE_EXC I
LEFT JOIN TGFPRO P ON P.CODPROD=I.CODPROD
WHERE I.NUNOTA=@nunota
ORDER BY I.SEQUENCIA
`;
