/** Cotacao header — compact to stay under API Mother ~500 char limit */
export const cabCotacao = `
SELECT C.NUMCOTACAO,C.SITUACAO,CONVERT(VARCHAR(19),C.DHINIC,120) AS DHINIC,CONVERT(VARCHAR(19),C.DHFINAL,120) AS DHFINAL,C.NUNOTAORIG,C.GERPEDREAL,C.CODEMP,C.CODCENCUS,N.DESCRCENCUS AS CENTRO_CUSTO_DESCRICAO,C.CODUSURESP,U1.NOMEUSU AS NOME_RESPONSAVEL,C.CODUSUREQ,U2.NOMEUSU AS NOME_SOLICITANTE
FROM TGFCOT C
LEFT JOIN TSICUS N ON N.CODCENCUS=C.CODCENCUS
LEFT JOIN TSIUSU U1 ON U1.CODUSU=C.CODUSURESP
LEFT JOIN TSIUSU U2 ON U2.CODUSU=C.CODUSUREQ
WHERE C.NUMCOTACAO=@numcotacao
`;

/** Active docs linked to cotacao */
export const cabCotacaoDocAtivos = `
SELECT C.NUNOTA,C.NUMNOTA,C.CODPARC,P.NOMEPARC AS PARCEIRO_NOME,C.VLRNOTA,C.STATUSNOTA,C.CODTIPOPER,C.TIPMOV,CONVERT(VARCHAR(10),C.DTNEG,120) AS DTNEG,'ATIVO' AS ORIGEM
FROM TGFCAB C
LEFT JOIN TGFPAR P ON P.CODPARC=C.CODPARC
WHERE C.NUMCOTACAO=@numcotacao
ORDER BY C.DTNEG
`;

/** Deleted docs linked to cotacao (excl current nunota) */
export const cabCotacaoDocExcluidos = `
SELECT E.NUNOTA,E.NUMNOTA,E.CODPARC,P.NOMEPARC AS PARCEIRO_NOME,E.VLRNOTA,E.STATUSNOTA,E.CODTIPOPER,E.TIPMOV,CONVERT(VARCHAR(10),E.DTNEG,120) AS DTNEG,'EXCLUIDO' AS ORIGEM
FROM TGFCAB_EXC E
LEFT JOIN TGFPAR P ON P.CODPARC=E.CODPARC
WHERE E.NUMCOTACAO=@numcotacao AND E.NUNOTA<>@nunota
ORDER BY E.DTNEG
`;
