export const notaDetalheTop = `
SELECT
    TOPV.CODTIPOPER, TOPV.DHALTER, TOPV.TIPMOV, TOPV.ATUALEST, TOPV.ATUALFIN,
    TOPV.ATIVO, TOPV.GOLNEG, TOPV.BONIFICACAO, TOPV.LANCDEDUTIVEL,
    TOPV.GERADUPLICATA, TOPV.CONTROLEEST, TOPV.TIPFRETE, TOPV.EMITENTE,
    TOPV.HABILITANFE, TOPV.MODELO,
    TOPV.AD_LAYOUTCAB, TOPV.AD_LAYOUTITE, TOPV.AD_LAYOUTFIN
FROM TGFTOP TOPV
WHERE TOPV.CODTIPOPER = (SELECT CAB.CODTIPOPER FROM TGFCAB CAB WHERE CAB.NUNOTA = @nunota)
  AND TOPV.DHALTER = (SELECT MAX(TOP2.DHALTER) FROM TGFTOP TOP2 WHERE TOP2.CODTIPOPER = TOPV.CODTIPOPER AND TOP2.DHALTER <= (SELECT CAB2.DTNEG FROM TGFCAB CAB2 WHERE CAB2.NUNOTA = @nunota))
`;

export const notaDetalheVar = `
SELECT VAR.NUNOTA, VAR.SEQUENCIA, VAR.NUNOTAORIG AS NUNOTA_ORIGEM, VAR.SEQUENCIAORIG AS SEQUENCIA_ORIGEM
FROM TGFVAR VAR
WHERE VAR.NUNOTA = @nunota
`;
