export const notaDetalheCab = `
SELECT
    CAB.NUNOTA, CAB.NUMNOTA, CAB.CODEMP, EMP.NOMEFANTASIA AS NOME_EMPRESA,
    CAB.CODPARC, PAR.NOMEPARC AS PARCEIRO_NOME, PAR.TIPPESSOA AS PARCEIRO_TIPO_PESSOA,
    PAR.CGC_CPF AS PARCEIRO_CGC_CPF, CID.NOMECID AS PARCEIRO_CIDADE, CID.UF AS PARCEIRO_UF,
    CONVERT(VARCHAR(10), CAB.DTNEG, 120) AS DTNEG,
    CONVERT(VARCHAR(10), CAB.DTMOV, 120) AS DTMOV,
    CONVERT(VARCHAR(8), CAB.HRMOV, 108) AS HRMOV,
    CONVERT(VARCHAR(10), CAB.DTENTSAI, 120) AS DTENTSAI,
    CONVERT(VARCHAR(10), CAB.DTFATUR, 120) AS DTFATUR,
    CAB.STATUSNOTA, CAB.STATUSNFE, CAB.CODTIPOPER,
    TOPV.ATUALEST, TOPV.ATUALFIN, TOPV.TIPMOV,
    CAB.VLRNOTA, CAB.VLRFRETE, CAB.VLRIPI, CAB.VLRICMS, CAB.VLRSUBST, CAB.BASEICMS,
    CAB.CODUSUINC, USU.NOMEUSU AS NOME_USUARIO_INC, USU.CODPARC AS CODPARC_USUARIO_INC,
    CAB.CODUSUALTER, USU2.NOMEUSU AS NOME_USUARIO_ALTER,
    CONVERT(VARCHAR(19), CAB.DTALTER, 120) AS DTALTER, CAB.OBSERVACAO,
    CAB.CODNAT, CAB.CODCENCUS, CAB.CODVEND, VEN.APELIDO AS VENDEDOR_NOME,
    CAB.NUFIN, CAB.CHAVENFE, CAB.SERIENOTA, CAB.NUMCOTACAO
FROM TGFCAB CAB
LEFT JOIN TGFPAR PAR ON PAR.CODPARC = CAB.CODPARC
LEFT JOIN TSIEMP EMP ON EMP.CODEMP = CAB.CODEMP
LEFT JOIN TSICID CID ON CID.CODCID = PAR.CODCID
LEFT JOIN TGFTOP TOPV ON TOPV.CODTIPOPER = CAB.CODTIPOPER AND TOPV.DHALTER = (SELECT MAX(TOP2.DHALTER) FROM TGFTOP TOP2 WHERE TOP2.CODTIPOPER = CAB.CODTIPOPER AND TOP2.DHALTER <= CAB.DTNEG)
LEFT JOIN TSIUSU USU ON USU.CODUSU = CAB.CODUSUINC
LEFT JOIN TSIUSU USU2 ON USU2.CODUSU = CAB.CODUSUALTER
LEFT JOIN TGFVEN VEN ON VEN.CODVEND = CAB.CODVEND
WHERE CAB.NUNOTA = @nunota
`;
