export const notaDetalheItens = `
SELECT
    ITE.NUNOTA, ITE.SEQUENCIA, ITE.CODPROD,
    PRO.REFERENCIA AS PRODUTO_REFERENCIA, PRO.MARCA AS PRODUTO_MARCA,
    PRO.USOPROD, PRO.CODVOL AS UNIDADE,
    ITE.CODLOCALORIG, ITE.CODLOCALDESTINO, ITE.CONTROLE,
    ITE.QTDNEG, ITE.QTDENTREGUE,
    ITE.QTDNEG - ISNULL(ITE.QTDENTREGUE, 0) AS QTD_PENDENTE,
    ITE.VLRUNIT, ITE.VLRTOT,
    ITE.VLRICMS, ITE.VLRIPI, ITE.BASEICMS, ITE.ALIQICMS, ITE.ALIQIPI,
    ITE.CODCFO, ITE.CODTRIB
FROM TGFITE ITE
INNER JOIN TGFPRO PRO ON PRO.CODPROD = ITE.CODPROD
WHERE ITE.NUNOTA = @nunota
ORDER BY ITE.SEQUENCIA
`;
