/**
 * Query para detalhe completo do cabecalho da nota (TGFCAB)
 * Inclui dados do parceiro, usuario, tipo operacao (versionada) e empresa
 * @param @nunota - NUNOTA da nota
 */
export const notaDetalheCab = `
SELECT
    CAB.NUNOTA,
    CAB.NUMNOTA,
    CAB.CODEMP,
    EMP.NOMEFANTASIA     AS NOME_EMPRESA,
    CAB.CODPARC,
    PAR.NOMEPARC         AS PARCEIRO_NOME,
    PAR.TIPPESSOA        AS PARCEIRO_TIPO_PESSOA,
    PAR.CGC_CPF          AS PARCEIRO_CGC_CPF,
    PAR.CODCID           AS PARCEIRO_CODCID,
    CID.NOMECID          AS PARCEIRO_CIDADE,
    CID.UF               AS PARCEIRO_UF,

    CONVERT(VARCHAR(10), CAB.DTNEG, 120) AS DTNEG,
    CONVERT(VARCHAR(10), CAB.DTMOV, 120) AS DTMOV,
    CONVERT(VARCHAR(8),  CAB.HRMOV, 108) AS HRMOV,
    CONVERT(VARCHAR(10), CAB.DTMOV, 120) + ' ' +
    CONVERT(VARCHAR(8),  CAB.HRMOV, 108) AS DATA_HORA_MOVIMENTO,
    CONVERT(VARCHAR(10), CAB.DTENTSAI, 120) AS DTENTSAI,
    CONVERT(VARCHAR(10), CAB.DTFATUR, 120) AS DTFATUR,

    CAB.STATUSNOTA,
    CASE CAB.STATUSNOTA
        WHEN 'A' THEN 'Atendimento'
        WHEN 'L' THEN 'Liberada'
        WHEN 'P' THEN 'Pendente'
        ELSE 'Outro'
    END AS STATUS_DESCRICAO,

    CAB.STATUSNFE,
    CASE CAB.STATUSNFE
        WHEN 'A' THEN 'Autorizada'
        WHEN 'D' THEN 'Denegada'
        WHEN 'E' THEN 'Aguardando'
        WHEN 'R' THEN 'Rejeitada'
        WHEN 'C' THEN 'Cancelada'
        WHEN 'I' THEN 'Inutilizada'
        ELSE ISNULL(CAB.STATUSNFE, '-')
    END AS STATUS_NFE_DESCRICAO,

    CAB.CODTIPOPER,
    TOPV.DESCROPER       AS TIPO_OPER_DESCRICAO,
    TOPV.ATUALEST,
    CASE TOPV.ATUALEST
        WHEN 'B' THEN 'Baixar estoque'
        WHEN 'E' THEN 'Entrar no estoque'
        WHEN 'N' THEN 'Nao movimenta estoque'
        WHEN 'R' THEN 'Reservar estoque'
        ELSE 'Indefinido'
    END AS ATUALEST_DESCRICAO,
    TOPV.ATUALFIN,
    CASE TOPV.ATUALFIN
        WHEN 'S' THEN 'Sim'
        WHEN 'N' THEN 'Nao'
        ELSE ISNULL(TOPV.ATUALFIN, '-')
    END AS ATUALFIN_DESCRICAO,
    TOPV.TIPMOV,
    CASE TOPV.TIPMOV
        WHEN 'C' THEN 'Compra'
        WHEN 'D' THEN 'Devolucao'
        WHEN 'O' THEN 'Outros'
        WHEN 'P' THEN 'Pedido'
        WHEN 'V' THEN 'Venda'
        WHEN 'T' THEN 'Transferencia'
        ELSE ISNULL(TOPV.TIPMOV, '-')
    END AS TIPMOV_DESCRICAO,

    CAB.VLRNOTA,
    CAB.VLRDESC,
    CAB.VLRFRETE,
    CAB.VLRIPI,
    CAB.VLRICMS,
    CAB.VLRSUBST,
    CAB.BASEICMS,
    CAB.VLRDESPTOT,

    CAB.CODUSUINC,
    USU.NOMEUSU          AS NOME_USUARIO_INC,
    USU.CODPARC          AS CODPARC_USUARIO_INC,

    CAB.CODUSUALTER,
    USU2.NOMEUSU         AS NOME_USUARIO_ALTER,

    CONVERT(VARCHAR(19), CAB.DTALTER, 120) AS DTALTER,
    CAB.OBSERVACAO,
    CAB.CODNAT,
    NAT.DESCRNAT         AS NATUREZA_DESCRICAO,
    CAB.CODCENCUS,
    CEN.DESCRCENCUS      AS CENTRO_CUSTO_DESCRICAO,
    CAB.CODPROJ,
    CAB.CODTIPVENDA,
    CAB.CODVEND,
    VEN.APELIDO          AS VENDEDOR_NOME,
    CAB.NUFIN,
    CAB.CHAVENFE,
    CAB.SERIENOTA,
    CAB.NUMCOTACAO

FROM TGFCAB CAB

LEFT JOIN TGFPAR PAR
    ON PAR.CODPARC = CAB.CODPARC

LEFT JOIN TSIEMP EMP
    ON EMP.CODEMP = CAB.CODEMP

LEFT JOIN TSICID CID
    ON CID.CODCID = PAR.CODCID

LEFT JOIN TGFTOP TOPV
    ON TOPV.CODTIPOPER = CAB.CODTIPOPER
   AND TOPV.DHALTER = (
        SELECT MAX(TOP2.DHALTER)
        FROM TGFTOP TOP2
        WHERE TOP2.CODTIPOPER = CAB.CODTIPOPER
          AND TOP2.DHALTER <= CAB.DTNEG
   )

LEFT JOIN TSIUSU USU
    ON USU.CODUSU = CAB.CODUSUINC

LEFT JOIN TSIUSU USU2
    ON USU2.CODUSU = CAB.CODUSUALTER

LEFT JOIN TGFNAT NAT
    ON NAT.CODNAT = CAB.CODNAT

LEFT JOIN TSICUS CEN
    ON CEN.CODCENCUS = CAB.CODCENCUS

LEFT JOIN TGFVEN VEN
    ON VEN.CODVEND = CAB.CODVEND

WHERE CAB.NUNOTA = @nunota
`;
