/**
 * Query para itens da nota (TGFITE) com dados do produto
 * @param @nunota - NUNOTA da nota
 */
export const notaDetalheItens = `
SELECT
    ITE.NUNOTA,
    ITE.SEQUENCIA,
    ITE.CODPROD,
    PRO.DESCRPROD        AS PRODUTO_DESCRICAO,
    PRO.REFERENCIA       AS PRODUTO_REFERENCIA,
    PRO.CODGRUPOPROD,
    GRU.DESCRGRUPOPROD   AS GRUPO_PRODUTO,
    PRO.MARCA            AS PRODUTO_MARCA,
    PRO.USOPROD,
    CASE PRO.USOPROD
        WHEN 'R' THEN 'Revenda'
        WHEN 'C' THEN 'Consumo'
        WHEN 'M' THEN 'Materia Prima'
        WHEN 'S' THEN 'Servico'
        WHEN 'P' THEN 'Producao'
        WHEN 'I' THEN 'Imobilizado'
        ELSE ISNULL(PRO.USOPROD, '-')
    END AS USOPROD_DESCRICAO,
    ITE.CODLOCALORIG,
    ITE.CODLOCALDESTINO,
    ITE.CONTROLE,

    ITE.QTDNEG,
    ITE.QTDENTREGUE,
    ITE.QTDNEG - ISNULL(ITE.QTDENTREGUE, 0) AS QTD_PENDENTE,

    ITE.VLRUNIT,
    ITE.VLRTOT,
    ITE.VLRDESC,
    ITE.PERCDESC,
    ITE.VLRICMS,
    ITE.VLRIPI,
    ITE.BASEICMS,
    ITE.ALIQICMS,
    ITE.ALIQIPI,
    ITE.CODCFO,
    ITE.CODTRIB,
    ITE.OBSERVACAO       AS OBSERVACAO_ITEM,

    PRO.CODVOL           AS UNIDADE

FROM TGFITE ITE

INNER JOIN TGFPRO PRO
    ON PRO.CODPROD = ITE.CODPROD

LEFT JOIN TGFGRU GRU
    ON GRU.CODGRUPOPROD = PRO.CODGRUPOPROD

WHERE ITE.NUNOTA = @nunota

ORDER BY ITE.SEQUENCIA
`;
