export const pesquisar = `
SELECT TOP 100
  u.CODUSU AS codusu,
  RTRIM(CAST(u.NOMEUSU AS VARCHAR(100))) AS nomeusu,
  RTRIM(CAST(u.EMAIL AS VARCHAR(100))) AS email,
  COALESCE(u.CODPARC, f.CODPARC) AS codparc,
  RTRIM(CAST(p.NOMEPARC AS VARCHAR(MAX))) AS nomeparc,
  u.CODEMP AS codemp,
  RTRIM(CAST(e.NOMEFANTASIA AS VARCHAR(MAX))) AS nomeempresa,
  u.CODFUNC AS codfunc,
  u.CODGRUPO AS codgrupo,
  RTRIM(CAST(g.NOMEGRUPO AS VARCHAR(MAX))) AS nomegrupo,
  CASE
    WHEN u.DTLIMACESSO IS NULL OR u.DTLIMACESSO >= GETDATE() THEN 'S'
    ELSE 'N'
  END AS ativo
FROM TSIUSU u
OUTER APPLY (
  SELECT TOP 1 ff.CODPARC, dep.DESCRDEP
  FROM TFPFUN ff
  LEFT JOIN TFPDEP dep ON dep.CODDEP = ff.CODDEP
  WHERE ff.CODFUNC = u.CODFUNC AND ff.CODEMP = u.CODEMP
) f
LEFT JOIN TGFPAR p ON COALESCE(u.CODPARC, f.CODPARC) = p.CODPARC
LEFT JOIN TSIEMP e ON u.CODEMP = e.CODEMP
LEFT JOIN TSIGRU g ON u.CODGRUPO = g.CODGRUPO
WHERE 1=1
-- @ATIVO
-- @SEARCH
-- @DEPARTAMENTO
ORDER BY u.NOMEUSU
`;
