/**
 * Gateway error code registry — single source of truth for all error codes.
 * All codes are ERR_ prefixed string literals.
 * Do NOT remove ErrorType enum — kept for backward compatibility.
 */
export enum GatewayErrorCode {
  // Guard rejections
  ERR_WRITE_FORBIDDEN = 'ERR_WRITE_FORBIDDEN',
  ERR_TABLE_PROTECTED = 'ERR_TABLE_PROTECTED',
  ERR_TABLE_WRITE_NOT_ALLOWED = 'ERR_TABLE_WRITE_NOT_ALLOWED',
  ERR_TABLE_EXTRACTION_FAILED = 'ERR_TABLE_EXTRACTION_FAILED',
  ERR_BOSS_APPROVAL_REQUIRED = 'ERR_BOSS_APPROVAL_REQUIRED',
  ERR_BOSS_TOKEN_INVALID = 'ERR_BOSS_TOKEN_INVALID', // Boss approval token present but invalid (signature/expiry/claims)
  ERR_MUTATION_DISABLED = 'ERR_MUTATION_DISABLED',
  ERR_RATE_LIMIT = 'ERR_RATE_LIMIT',
  ERR_ADMIN_REQUIRED = 'ERR_ADMIN_REQUIRED',

  // Auth errors
  ERR_UNAUTHORIZED = 'ERR_UNAUTHORIZED',
  ERR_INVALID_CREDENTIALS = 'ERR_INVALID_CREDENTIALS',
  ERR_TOKEN_EXPIRED = 'ERR_TOKEN_EXPIRED',

  // SQL/Database errors
  ERR_SQL_SYNTAX = 'ERR_SQL_SYNTAX',
  ERR_SQL_INVALID_COLUMN = 'ERR_SQL_INVALID_COLUMN',
  ERR_SQL_INVALID_TABLE = 'ERR_SQL_INVALID_TABLE',
  ERR_SQL_PERMISSION_DENIED = 'ERR_SQL_PERMISSION_DENIED',
  ERR_SQL_TYPE_MISMATCH = 'ERR_SQL_TYPE_MISMATCH',
  ERR_SQL_CONSTRAINT_VIOLATION = 'ERR_SQL_CONSTRAINT_VIOLATION',
  ERR_DATABASE_CONNECTION = 'ERR_DATABASE_CONNECTION',
  ERR_DATABASE_DEADLOCK = 'ERR_DATABASE_DEADLOCK',
  ERR_DATABASE_TIMEOUT = 'ERR_DATABASE_TIMEOUT',

  // Query validation errors
  ERR_QUERY_EMPTY = 'ERR_QUERY_EMPTY',
  ERR_QUERY_NOT_SELECT = 'ERR_QUERY_NOT_SELECT',
  ERR_QUERY_FORBIDDEN_COMMAND = 'ERR_QUERY_FORBIDDEN_COMMAND',
  ERR_QUERY_INJECTION_PATTERN = 'ERR_QUERY_INJECTION_PATTERN',

  // Validation
  ERR_VALIDATION_FAILED = 'ERR_VALIDATION_FAILED',

  // System fallback
  ERR_INTERNAL = 'ERR_INTERNAL',
}
