export const getCount = `
SELECT COUNT(*) AS TOTAL
FROM AD_COMADM A WITH (NOLOCK)
LEFT JOIN TGFPAR P ON P.CODPARC = A.CODPARC
LEFT JOIN TSIUSU SOL ON SOL.CODUSU = A.SOLICITANTE
LEFT JOIN TSICUS CUS ON CUS.CODCENCUS = SOL.CODCENCUSPAD
LEFT JOIN TSIUSU ATR ON ATR.CODUSU = A.SOLICITADO
WHERE 1=1
-- @WHERE
`;
