export const getOcorrencias = `
SELECT
  O.NUCHAMADO,
  O.SEQUENCIA,
  O.DESCROCORRENCIA,
  O.DHOCORRENCIA,
  O.ATENDENTE,
  U.NOMEUSU AS NOMEATENDENTE,
  U.CODPARC AS CODPARCATENDENTE
FROM AD_COMADM1 O WITH (NOLOCK)
LEFT JOIN TSIUSU U ON U.CODUSU = O.ATENDENTE
WHERE O.NUCHAMADO = @nuchamado
ORDER BY O.SEQUENCIA ASC
`;
