export const getPorSetor = `
SELECT
  CUS.DESCRCENCUS AS SETOR,
  COUNT(*) AS TOTAL,
  SUM(CASE WHEN A.STATUS = 'F' THEN 1 ELSE 0 END) AS FINALIZADOS,
  SUM(CASE WHEN A.STATUS IN ('P','E','S','A') THEN 1 ELSE 0 END) AS ATIVOS
FROM AD_COMADM A WITH (NOLOCK)
LEFT JOIN TSIUSU SOL ON SOL.CODUSU = A.SOLICITANTE
LEFT JOIN TSICUS CUS ON CUS.CODCENCUS = SOL.CODCENCUSPAD
GROUP BY CUS.DESCRCENCUS
ORDER BY TOTAL DESC
`;
