export const getChatList = `
SELECT * FROM (
  SELECT
    A.NUCHAMADO,
    A.STATUS,
    A.PRIORIDADE,
    A.TIPOCHAMADO,
    CUS.DESCRCENCUS AS SETOR,
    A.SOLICITANTE,
    SOL.NOMEUSU AS NOMESOLICITANTE,
    SOL.CODPARC AS CODPARCSOLICITANTE,
    LEFT(CAST(A.DESCRCHAMADO AS VARCHAR(MAX)), 100) AS DESCRCHAMADO,
    CONVERT(VARCHAR(19),
      COALESCE(
        (SELECT MAX(O.DHOCORRENCIA) FROM AD_COMADM1 O WHERE O.NUCHAMADO = A.NUCHAMADO),
        A.DHALTER,
        A.DHCHAMADO
      ), 120) AS ULTIMA_ATIVIDADE,
    (SELECT TOP 1 LEFT(CAST(O2.DESCROCORRENCIA AS VARCHAR(MAX)), 100)
     FROM AD_COMADM1 O2
     WHERE O2.NUCHAMADO = A.NUCHAMADO
     ORDER BY O2.SEQUENCIA DESC) AS ULTIMA_TRATATIVA_TEXTO,
    (SELECT TOP 1 U2.NOMEUSU
     FROM AD_COMADM1 O2
     LEFT JOIN TSIUSU U2 ON U2.CODUSU = O2.ATENDENTE
     WHERE O2.NUCHAMADO = A.NUCHAMADO
     ORDER BY O2.SEQUENCIA DESC) AS ULTIMA_TRATATIVA_AUTOR,
    (SELECT COUNT(1) FROM AD_COMADM1 O3 WHERE O3.NUCHAMADO = A.NUCHAMADO) AS TOTAL_OCORRENCIAS,
    ROW_NUMBER() OVER (ORDER BY
      COALESCE(
        (SELECT MAX(O4.DHOCORRENCIA) FROM AD_COMADM1 O4 WHERE O4.NUCHAMADO = A.NUCHAMADO),
        A.DHALTER,
        A.DHCHAMADO
      ) DESC
    ) AS RowNum
  FROM AD_COMADM A WITH (NOLOCK)
  LEFT JOIN TSIUSU SOL ON SOL.CODUSU = A.SOLICITANTE
  LEFT JOIN TSICUS CUS ON CUS.CODCENCUS = SOL.CODCENCUSPAD
  WHERE 1=1
  -- @WHERE
) AS T
WHERE RowNum > @OFFSET AND RowNum <= (@OFFSET + @LIMIT)
`;
