export const getById = `
SELECT
  A.NUCHAMADO,
  A.DESCRCHAMADO,
  A.STATUS,
  A.PRIORIDADE,
  A.TIPOCHAMADO,
  CONVERT(VARCHAR(19), A.DHCHAMADO, 120) AS DHCHAMADO,
  CONVERT(VARCHAR(19), A.DHFINCHAM, 120) AS DHFINCHAM,
  CONVERT(VARCHAR(19), A.DHPREVENTREGA, 120) AS DHPREVENTREGA,
  CONVERT(VARCHAR(19), A.DHVALIDACAO, 120) AS DHVALIDACAO,
  CONVERT(VARCHAR(19), A.DHALTER, 120) AS DHALTER,
  A.SOLICITANTE,
  A.SOLICITADO,
  A.FINALIZADOPOR,
  A.VALIDADOPOR,
  A.CODUSUALTER,
  A.CODPARC,
  CUS.DESCRCENCUS AS SETOR,
  P.NOMEPARC,
  SOL.NOMEUSU AS NOMESOLICITANTE,
  SOL.CODPARC AS CODPARCSOLICITANTE,
  ATR.NOMEUSU AS NOMEATRIBUIDO,
  ATR.CODPARC AS CODPARCATRIBUIDO,
  FIN.NOMEUSU AS NOMEFINALIZADOR,
  FIN.CODPARC AS CODPARCFINALIZADOR,
  ALT.NOMEUSU AS NOMEALTERADOR,
  ALT.CODPARC AS CODPARCALTERADOR,
  VAL.NOMEUSU AS NOMEVALIDADOR,
  VAL.CODPARC AS CODPARCVALIDADOR,
  (SELECT COUNT(1) FROM TSIANX ANX WITH (NOLOCK)
   WHERE ANX.NOMEINSTANCIA IN ('COMADM','COMADM1')
   AND ANX.PKREGISTRO LIKE CAST(A.NUCHAMADO AS VARCHAR) + '[_]%') AS TEM_ANEXO
FROM AD_COMADM A WITH (NOLOCK)
LEFT JOIN TGFPAR P ON P.CODPARC = A.CODPARC
LEFT JOIN TSIUSU SOL ON SOL.CODUSU = A.SOLICITANTE
LEFT JOIN TSICUS CUS ON CUS.CODCENCUS = SOL.CODCENCUSPAD
LEFT JOIN TSIUSU ATR ON ATR.CODUSU = A.SOLICITADO
LEFT JOIN TSIUSU FIN ON FIN.CODUSU = A.FINALIZADOPOR
LEFT JOIN TSIUSU ALT ON ALT.CODUSU = A.CODUSUALTER
LEFT JOIN TSIUSU VAL ON VAL.CODUSU = A.VALIDADOPOR
WHERE A.NUCHAMADO = @nuchamado
`;
