export const getUsuariosChamados = `
SELECT U.CODUSU, RTRIM(U.NOMEUSU) AS NOMEUSU, U.CODPARC, U.CODGRUPO
FROM TSIUSU U WITH (NOLOCK)
WHERE (U.DTLIMACESSO IS NULL OR U.DTLIMACESSO >= GETDATE())
ORDER BY NOMEUSU
`;
