// Kanban query: brings ALL active chamados + only recent 20 for F/C
// Uses UNION ALL to limit closed statuses at the SQL level
const KANBAN_COLS = `
  A.NUCHAMADO,
  A.DESCRCHAMADO,
  A.STATUS,
  A.PRIORIDADE,
  A.TIPOCHAMADO,
  CONVERT(VARCHAR(19), A.DHCHAMADO, 120) AS DHCHAMADO,
  CONVERT(VARCHAR(19), A.DHFINCHAM, 120) AS DHFINCHAM,
  CONVERT(VARCHAR(19), A.DHPREVENTREGA, 120) AS DHPREVENTREGA,
  CONVERT(VARCHAR(19), A.DHVALIDACAO, 120) AS DHVALIDACAO,
  CONVERT(VARCHAR(19), A.DHALTER, 120) AS DHALTER,
  A.SOLICITANTE,
  A.SOLICITADO,
  A.FINALIZADOPOR,
  A.VALIDADOPOR,
  A.CODUSUALTER,
  A.CODPARC,
  CUS.DESCRCENCUS AS SETOR,
  P.NOMEPARC,
  SOL.NOMEUSU AS NOMESOLICITANTE,
  SOL.CODPARC AS CODPARCSOLICITANTE,
  ATR.NOMEUSU AS NOMEATRIBUIDO,
  ATR.CODPARC AS CODPARCATRIBUIDO,
  FIN.NOMEUSU AS NOMEFINALIZADOR,
  FIN.CODPARC AS CODPARCFINALIZADOR,
  ALT.NOMEUSU AS NOMEALTERADOR,
  ALT.CODPARC AS CODPARCALTERADOR,
  VAL.NOMEUSU AS NOMEVALIDADOR,
  VAL.CODPARC AS CODPARCVALIDADOR,
  ISNULL(ANX_COUNT.TOTAL, 0) AS TEM_ANEXO`;

const KANBAN_JOINS = `
FROM AD_COMADM A WITH (NOLOCK)
LEFT JOIN TGFPAR P ON P.CODPARC = A.CODPARC
LEFT JOIN TSIUSU SOL ON SOL.CODUSU = A.SOLICITANTE
LEFT JOIN TSICUS CUS ON CUS.CODCENCUS = SOL.CODCENCUSPAD
LEFT JOIN TSIUSU ATR ON ATR.CODUSU = A.SOLICITADO
LEFT JOIN TSIUSU FIN ON FIN.CODUSU = A.FINALIZADOPOR
LEFT JOIN TSIUSU ALT ON ALT.CODUSU = A.CODUSUALTER
LEFT JOIN TSIUSU VAL ON VAL.CODUSU = A.VALIDADOPOR
LEFT JOIN (
  SELECT
    LEFT(ANX.PKREGISTRO, CHARINDEX('_', ANX.PKREGISTRO) - 1) AS NUCHAMADO_STR,
    COUNT(1) AS TOTAL
  FROM TSIANX ANX WITH (NOLOCK)
  WHERE ANX.NOMEINSTANCIA IN ('COMADM', 'COMADM1')
    AND ANX.PKREGISTRO LIKE '%[_]%'
  GROUP BY LEFT(ANX.PKREGISTRO, CHARINDEX('_', ANX.PKREGISTRO) - 1)
) ANX_COUNT ON CAST(A.NUCHAMADO AS VARCHAR) = ANX_COUNT.NUCHAMADO_STR`;

export const getKanban = `
SELECT ${KANBAN_COLS}
${KANBAN_JOINS}
WHERE A.STATUS NOT IN ('F', 'C')
-- @WHERE
ORDER BY A.PRIORIDADE ASC, A.DHCHAMADO DESC
`;

// Closed statuses: only TOP 20 most recent per status
export const getKanbanClosed = `
SELECT * FROM (
  SELECT TOP 20 ${KANBAN_COLS}
  ${KANBAN_JOINS}
  WHERE A.STATUS = '@STATUS'
  -- @WHERE
  ORDER BY A.DHCHAMADO DESC
) AS T
`;

// Count totals per status for the badge display
export const getKanbanCounts = `
SELECT A.STATUS, COUNT(1) AS TOTAL
FROM AD_COMADM A WITH (NOLOCK)
WHERE 1=1
-- @WHERE
GROUP BY A.STATUS
`;
