export const getResumoStatus = `
SELECT STATUS, COUNT(*) AS TOTAL
FROM AD_COMADM WITH (NOLOCK)
GROUP BY STATUS
`;

export const getResumoPrioridade = `
SELECT PRIORIDADE, COUNT(*) AS TOTAL
FROM AD_COMADM WITH (NOLOCK)
GROUP BY PRIORIDADE
`;

export const getResumoTipo = `
SELECT TIPOCHAMADO, COUNT(*) AS TOTAL
FROM AD_COMADM WITH (NOLOCK)
GROUP BY TIPOCHAMADO
`;

export const getResumoTotal = `
SELECT COUNT(*) AS TOTAL
FROM AD_COMADM WITH (NOLOCK)
`;
