export const ocorrenciasAtivas = `
SELECT
  OCO.CODEMP AS codemp,
  OCO.CODFUNC AS codfunc,
  FUN.CODPARC AS codparc,
  FUN.NOMEFUNC AS nomeFuncionario,
  EMP.NOMEFANTASIA AS nomeEmpresa,
  OCO.CODHISTOCOR AS codHistoCor,
  HIS.DESCRHISTOCOR AS descricaoHistoCor,
  CONVERT(VARCHAR(10), OCO.DTINICOCOR, 120) AS dtInicio,
  CONVERT(VARCHAR(10), OCO.DTFINALOCOR, 120) AS dtFinal,
  CONVERT(VARCHAR(10), OCO.DTPREVRET, 120) AS dtPrevRetorno,
  OCO.DESCROCOR AS descricao,
  OCO.CID AS cid,
  DEP.DESCRCENCUS AS departamento,
  CAR.DESCRCARGO AS cargo
FROM TFPOCO OCO
JOIN TFPFUN FUN ON FUN.CODFUNC = OCO.CODFUNC AND FUN.CODEMP = OCO.CODEMP
JOIN TSIEMP EMP ON EMP.CODEMP = OCO.CODEMP
LEFT JOIN TFPHIS HIS ON HIS.CODHISTOCOR = OCO.CODHISTOCOR
LEFT JOIN TSICUS DEP ON DEP.CODCENCUS = FUN.CODDEP
LEFT JOIN TFPCAR CAR ON CAR.CODCARGO = FUN.CODCARGO
WHERE OCO.DTINICOCOR <= GETDATE()
  AND (OCO.DTFINALOCOR IS NULL OR OCO.DTFINALOCOR >= GETDATE())
ORDER BY OCO.DTINICOCOR DESC
`;

export const resumoOcorrenciasAtivas = `
SELECT COUNT(*) AS totalAtivas
FROM TFPOCO OCO
WHERE OCO.DTINICOCOR <= GETDATE()
  AND (OCO.DTFINALOCOR IS NULL OR OCO.DTFINALOCOR >= GETDATE())
`;

export const ocorrenciasPorTipo = `
SELECT
  OCO.CODHISTOCOR AS codHistoCor,
  HIS.DESCRHISTOCOR AS descricao,
  COUNT(*) AS quantidade
FROM TFPOCO OCO
LEFT JOIN TFPHIS HIS ON HIS.CODHISTOCOR = OCO.CODHISTOCOR
WHERE OCO.DTINICOCOR <= GETDATE()
  AND (OCO.DTFINALOCOR IS NULL OR OCO.DTFINALOCOR >= GETDATE())
GROUP BY OCO.CODHISTOCOR, HIS.DESCRHISTOCOR
ORDER BY quantidade DESC
`;
