export const buscarPorId = `
SELECT
  A.CODIGO,
  A.CODUSU,
  A.CODVEICULO,
  A.KM,
  A.HORIMETRO,
  A.DTINCLUSAO,
  A.DTPROGRAMACAO,
  A.NUOS,
  A.TAG,
  A.STATUSOS,
  A.BORRCHARIA,
  A.ELETRICA,
  A.FUNILARIA,
  A.MECANICA,
  A.CALDEIRARIA,
  A.OBS,
  A.OSEXTERNA,
  A.OPEXTERNO,
  V.PLACA,
  CAST(V.MARCAMODELO AS VARCHAR(200)) AS MARCAMODELO,
  V.CODMARCA,
  U.NOMEUSU,
  U.EMAIL AS EMAILUSU,
  CASE A.STATUSOS
    WHEN 'MA' THEN 'Manutenção'
    WHEN 'AN' THEN 'Em Análise'
    WHEN 'AV' THEN 'Aprovado'
    WHEN 'SN' THEN 'Sem Necessidade'
    ELSE 'Sem Status'
  END AS statusOsLabel,
  (SELECT COUNT(*) FROM AD_APONTSOL S WHERE S.CODIGO = A.CODIGO) AS totalServicos,
  (SELECT COUNT(*) FROM AD_APONTAMENTOSCHECKLIST C WHERE C.CODAPONTAMENTO = A.CODIGO AND C.ATIVO = 'S') AS totalChecklists
FROM AD_APONTAMENTO A WITH (NOLOCK)
LEFT JOIN TGFVEI V ON V.CODVEICULO = A.CODVEICULO
LEFT JOIN TSIUSU U ON U.CODUSU = A.CODUSU
WHERE A.CODIGO = @CODIGO
`;
