export const comOs = `
SELECT TOP @LIMIT
  A.CODIGO,
  A.TAG,
  A.DTINCLUSAO,
  A.NUOS,
  A.STATUSOS,
  V.PLACA,
  CAST(V.MARCAMODELO AS VARCHAR(200)) AS MARCAMODELO,
  U.NOMEUSU,
  CASE A.STATUSOS
    WHEN 'MA' THEN 'Manutenção'
    WHEN 'AN' THEN 'Em Análise'
    WHEN 'AV' THEN 'Aprovado'
    WHEN 'SN' THEN 'Sem Necessidade'
    ELSE 'Sem Status'
  END AS statusOsLabel,
  (SELECT COUNT(*) FROM AD_APONTSOL S WHERE S.CODIGO = A.CODIGO) AS totalServicos
FROM AD_APONTAMENTO A WITH (NOLOCK)
LEFT JOIN TGFVEI V ON V.CODVEICULO = A.CODVEICULO
LEFT JOIN TSIUSU U ON U.CODUSU = A.CODUSU
WHERE A.NUOS IS NOT NULL
ORDER BY A.DTINCLUSAO DESC
`;
