export const dashboardTotais = `
SELECT
  (SELECT COUNT(*) FROM AD_APONTAMENTO WITH (NOLOCK)) AS totalApontamentos,
  (SELECT COUNT(*) FROM AD_APONTSOL WITH (NOLOCK)) AS totalServicos,
  (SELECT CAST(COUNT(*) * 1.0 / NULLIF((SELECT COUNT(*) FROM AD_APONTAMENTO), 0) AS DECIMAL(10,2)) FROM AD_APONTSOL WITH (NOLOCK)) AS mediaServicosPorApontamento,
  (SELECT COUNT(*) FROM AD_APONTAMENTO WITH (NOLOCK) WHERE NUOS IS NOT NULL) AS apontamentosComOs,
  (SELECT CAST(COUNT(*) * 100.0 / NULLIF((SELECT COUNT(*) FROM AD_APONTAMENTO), 0) AS DECIMAL(5,2)) FROM AD_APONTAMENTO WITH (NOLOCK) WHERE NUOS IS NOT NULL) AS percentualConvertidoOs,
  (SELECT COUNT(*) FROM AD_APONTAMENTOSCHECKLIST WITH (NOLOCK) WHERE ATIVO = 'S') AS totalChecklists,
  (SELECT COUNT(*) FROM AD_APONTAMENTOSCHECKLIST WITH (NOLOCK) WHERE ATIVO = 'S' AND STATUSINTEGRACAO = 'PENDENTE') AS checklistsPendentes
`;
