export const dashboardTipos = `
SELECT 'BORRACHARIA' AS tipo, COUNT(*) AS total FROM AD_APONTAMENTO WITH (NOLOCK) WHERE BORRCHARIA = 'S'
UNION ALL
SELECT 'ELETRICA', COUNT(*) FROM AD_APONTAMENTO WITH (NOLOCK) WHERE ELETRICA = 'S'
UNION ALL
SELECT 'FUNILARIA', COUNT(*) FROM AD_APONTAMENTO WITH (NOLOCK) WHERE FUNILARIA = 'S'
UNION ALL
SELECT 'MECANICA', COUNT(*) FROM AD_APONTAMENTO WITH (NOLOCK) WHERE MECANICA = 'S'
UNION ALL
SELECT 'CALDEIRARIA', COUNT(*) FROM AD_APONTAMENTO WITH (NOLOCK) WHERE CALDEIRARIA = 'S'
ORDER BY total DESC
`;
