export const inconsistencias = `
SELECT
  A.CODIGO,
  A.DTINCLUSAO,
  A.CODUSU,
  U.NOMEUSU,
  A.TAG,
  A.STATUSOS,
  CASE
    WHEN A.CODVEICULO IS NULL AND A.TAG IS NULL THEN 'SEM_VEICULO_E_TAG'
    WHEN A.CODVEICULO IS NULL THEN 'SEM_VEICULO'
    WHEN A.STATUSOS IS NULL THEN 'SEM_STATUS'
    ELSE 'OUTRO'
  END AS tipoProblema
FROM AD_APONTAMENTO A WITH (NOLOCK)
LEFT JOIN TSIUSU U ON U.CODUSU = A.CODUSU
WHERE A.CODVEICULO IS NULL
   OR A.STATUSOS IS NULL
ORDER BY A.DTINCLUSAO DESC
`;
