export const listarCount = `
SELECT COUNT(*) AS totalRegistros
FROM AD_APONTAMENTO A WITH (NOLOCK)
LEFT JOIN TGFVEI V ON V.CODVEICULO = A.CODVEICULO
LEFT JOIN TSIUSU U ON U.CODUSU = A.CODUSU
WHERE 1=1
-- @WHERE
`;
