export const porVeiculo = `
SELECT
  A.CODIGO,
  A.CODUSU,
  A.KM,
  A.HORIMETRO,
  A.DTINCLUSAO,
  A.NUOS,
  A.TAG,
  A.STATUSOS,
  A.OBS,
  A.BORRCHARIA,
  A.ELETRICA,
  A.FUNILARIA,
  A.MECANICA,
  A.CALDEIRARIA,
  V.PLACA,
  CAST(V.MARCAMODELO AS VARCHAR(200)) AS MARCAMODELO,
  U.NOMEUSU,
  CASE A.STATUSOS
    WHEN 'MA' THEN 'Manutenção'
    WHEN 'AN' THEN 'Em Análise'
    WHEN 'AV' THEN 'Aprovado'
    WHEN 'SN' THEN 'Sem Necessidade'
    ELSE 'Sem Status'
  END AS statusOsLabel,
  (SELECT COUNT(*) FROM AD_APONTSOL S WHERE S.CODIGO = A.CODIGO) AS totalServicos
FROM AD_APONTAMENTO A WITH (NOLOCK)
LEFT JOIN TGFVEI V ON V.CODVEICULO = A.CODVEICULO
LEFT JOIN TSIUSU U ON U.CODUSU = A.CODUSU
WHERE A.CODVEICULO = @CODVEICULO
ORDER BY A.DTINCLUSAO DESC
`;
