export const funcionarioCompleto = `
SELECT TOP 1
  F.CODEMP AS codemp,
  F.CODFUNC AS codfunc,
  F.CODPARC AS codparc,
  P.NOMEPARC AS nomeparc,
  P.CGC_CPF AS cgcCpf,
  P.TELEFONE AS telefone,
  P.EMAIL AS email,
  F.SITUACAO AS situacao,
  CONVERT(VARCHAR(10), F.DTADM, 120) AS dtadm,
  CONVERT(VARCHAR(10), F.DTDEM, 120) AS dtdem,
  (SELECT TOP 1 fho.CODCARGAHOR FROM TFPFHO fho
    WHERE fho.CODEMP = F.CODEMP AND fho.CODFUNC = F.CODFUNC
    ORDER BY fho.DTINIESCALA DESC) AS codcargahor,
  F.SALBASE AS salario,
  F.CODCARGO AS codcargo,
  CAR.DESCRCARGO AS cargo,
  F.CODFUNCAO AS codfuncao,
  FCO.DESCRFUNCAO AS funcao,
  F.CODDEP AS coddep,
  DEP.DESCRDEP AS departamento,
  EMP.NOMEFANTASIA AS empresa
FROM TFPFUN F
INNER JOIN TGFPAR P ON F.CODPARC = P.CODPARC
LEFT JOIN TFPCAR CAR ON F.CODCARGO = CAR.CODCARGO
LEFT JOIN TFPFCO FCO ON F.CODFUNCAO = FCO.CODFUNCAO
LEFT JOIN TFPDEP DEP ON F.CODDEP = DEP.CODDEP
LEFT JOIN TSIEMP EMP ON F.CODEMP = EMP.CODEMP
WHERE F.CODPARC = @codparc AND F.SITUACAO = '1'
ORDER BY F.DTADM DESC
`;
