export const colaboradoresComMateriais = `
SELECT USU.CODUSU, USU.NOMEUSU, PAR.CODPARC, PAR.NOMEPARC,
  COUNT(DISTINCT EST.CODPROD) AS QTD_PRODUTOS,
  CONVERT(INT, SUM(EST.ESTOQUE)) AS QTD_TOTAL
FROM TGFEST EST
JOIN TGFPAR PAR ON PAR.CODPARC = EST.CODPARC
JOIN TSIUSU USU ON USU.CODPARC = PAR.CODPARC AND PAR.CODPARC <> 0
WHERE EST.ESTOQUE <> 0
GROUP BY USU.CODUSU, USU.NOMEUSU, PAR.CODPARC, PAR.NOMEPARC
ORDER BY USU.NOMEUSU
`;

export const materiaisDoUsuario = `
SELECT
  EST.CODPROD, PRO.DESCRPROD, GRU.DESCRGRUPOPROD,
  PAR.NOMEPARC, CONVERT(INT, SUM(EST.ESTOQUE)) AS QTDE
FROM TGFEST EST
JOIN TGFPRO PRO ON PRO.CODPROD = EST.CODPROD
JOIN TGFGRU GRU ON PRO.CODGRUPOPROD = GRU.CODGRUPOPROD
JOIN TGFPAR PAR ON PAR.CODPARC = EST.CODPARC
JOIN TSIUSU USU ON USU.CODPARC = PAR.CODPARC AND PAR.CODPARC <> 0
WHERE EST.ESTOQUE <> 0 AND USU.CODUSU = @CODUSU
GROUP BY EST.CODPROD, PRO.DESCRPROD, GRU.DESCRGRUPOPROD, PAR.NOMEPARC
ORDER BY GRU.DESCRGRUPOPROD, PRO.DESCRPROD
`;

export const materiaisDoParceiro = `
SELECT
  EST.CODPROD, PRO.DESCRPROD, GRU.DESCRGRUPOPROD,
  PAR.NOMEPARC, CONVERT(INT, SUM(EST.ESTOQUE)) AS QTDE
FROM TGFEST EST
JOIN TGFPRO PRO ON PRO.CODPROD = EST.CODPROD
JOIN TGFGRU GRU ON PRO.CODGRUPOPROD = GRU.CODGRUPOPROD
JOIN TGFPAR PAR ON PAR.CODPARC = EST.CODPARC
WHERE EST.ESTOQUE <> 0 AND EST.CODPARC = @CODPARC
GROUP BY EST.CODPROD, PRO.DESCRPROD, GRU.DESCRGRUPOPROD, PAR.NOMEPARC
ORDER BY GRU.DESCRGRUPOPROD, PRO.DESCRPROD
`;
