export const historicoSerie = `
SELECT
  s.SERIE, s.NUNOTA, s.SEQUENCIA, s.ATUALESTOQUE,
  s.CODPROD, p.DESCRPROD,
  s.CODUSU, u.NOMEUSU,
  s.AVARIADO, s.SERIEFAB, s.SMARTCARD,
  c.DTNEG, c.TIPMOV, c.CODTIPOPER, c.NUMNOTA, c.STATUSNOTA,
  t.DESCROPER,
  c.CODPARC, par.NOMEPARC,
  i.CODLOCALORIG, lo.DESCRLOCAL AS LOCAL_NOME,
  i.QTDNEG
FROM TGFSER s
JOIN TGFCAB c ON s.NUNOTA = c.NUNOTA
JOIN TGFTOP t ON c.CODTIPOPER = t.CODTIPOPER AND c.DHTIPOPER = t.DHALTER
JOIN TGFPRO p ON s.CODPROD = p.CODPROD
LEFT JOIN TGFITE i ON s.NUNOTA = i.NUNOTA AND i.SEQUENCIA = ABS(s.SEQUENCIA)
LEFT JOIN TGFLOC lo ON i.CODLOCALORIG = lo.CODLOCAL
LEFT JOIN TGFPAR par ON c.CODPARC = par.CODPARC
LEFT JOIN TSIUSU u ON s.CODUSU = u.CODUSU
WHERE s.SERIE = '@SERIE' AND s.CODPROD = @CODPROD
ORDER BY c.DTNEG DESC, s.NUNOTA DESC, s.SEQUENCIA
`;
