export const listarSeriesPorProduto = `
SELECT
  um.SERIE, um.CODPROD, p.DESCRPROD,
  um.DTNEG AS ULTIMA_MOVIMENTACAO,
  um.TIPMOV, t.DESCROPER,
  um.CODPARC, par.NOMEPARC AS COM_QUEM,
  um.CODUSU, u.NOMEUSU AS MOVIMENTADO_POR,
  um.AVARIADO,
  i.CODLOCALORIG, lo.DESCRLOCAL AS LOCAL_ATUAL
FROM (
  SELECT s.SERIE, s.CODPROD, s.NUNOTA, s.SEQUENCIA, s.CODUSU, s.AVARIADO,
    c.DTNEG, c.TIPMOV, c.CODTIPOPER, c.DHTIPOPER, c.CODPARC,
    ROW_NUMBER() OVER (PARTITION BY s.SERIE, s.CODPROD ORDER BY c.DTNEG DESC, s.NUNOTA DESC) AS rn
  FROM TGFSER s
  JOIN TGFCAB c ON s.NUNOTA = c.NUNOTA
  WHERE s.CODPROD = @CODPROD AND s.SEQUENCIA > 0
) um
JOIN TGFPRO p ON um.CODPROD = p.CODPROD
JOIN TGFTOP t ON um.CODTIPOPER = t.CODTIPOPER AND um.DHTIPOPER = t.DHALTER
LEFT JOIN TGFITE i ON um.NUNOTA = i.NUNOTA AND i.SEQUENCIA = um.SEQUENCIA
LEFT JOIN TGFLOC lo ON i.CODLOCALORIG = lo.CODLOCAL
LEFT JOIN TGFPAR par ON um.CODPARC = par.CODPARC
LEFT JOIN TSIUSU u ON um.CODUSU = u.CODUSU
WHERE um.rn = 1
ORDER BY um.SERIE
`;
