export const resumoPorProduto = `
SELECT s.CODPROD, p.DESCRPROD, COUNT(DISTINCT s.SERIE) as QTD_SERIES
FROM TGFSER s
JOIN TGFPRO p ON s.CODPROD = p.CODPROD
GROUP BY s.CODPROD, p.DESCRPROD
HAVING COUNT(DISTINCT s.SERIE) > 0
ORDER BY QTD_SERIES DESC
`;
