SELECT 
    FUN.CODFUNC,
    FUN.NOMEFUNC,
    EMP.CODEMP,
    EMP.RAZAOSOCIAL,
    CAR.DESCRCARGO,
    HABI.DESCRICAO AS HABILITACAO,
    CONVERT(VARCHAR(10), HAB.DTEMISSAO, 103) AS DTEMISSAO,
    CONVERT(VARCHAR(10), HAB.DTVALIDADE, 103) AS DTVALIDADE,
    'OK' AS STATUS_VALIDADE
FROM TFPFUN FUN
INNER JOIN TFPCAR CAR ON CAR.CODCARGO = FUN.CODCARGO
INNER JOIN TSIEMP EMP ON EMP.CODEMP = FUN.CODEMP
INNER JOIN TSIUSU USU ON USU.CPF = FUN.CPF 
INNER JOIN AD_TSIUSUHAB HAB ON HAB.CODUSU = USU.CODUSU
INNER JOIN AD_CADHAB HABI ON HABI.CODHAB = HAB.CODHAB
WHERE FUN.SITUACAO = '1'  
  AND HAB.DTVALIDADE >= CAST(GETDATE() AS DATE) 
ORDER BY FUN.NOMEFUNC
