/**
 * Generic attachment query for any Sankhya module.
 * Replace @INSTANCIAS with comma-separated quoted names: 'COMADM','COMADM1'
 * Replace @PK_PATTERN with a LIKE pattern: 'CAST(@pk AS VARCHAR) + ''_%'''
 */
export const getByInstancia = `
SELECT
  ANX.NUATTACH,
  ANX.NOMEARQUIVO,
  ANX.DESCRICAO,
  ANX.CHAVEARQUIVO,
  CONVERT(VARCHAR(19), ANX.DHCAD, 120) AS DHCAD,
  CONVERT(VARCHAR(19), ANX.DHALTER, 120) AS DHALTER,
  ANX.LINK,
  ANX.TIPOAPRES,
  ANX.TIPOACESSO,
  ANX.NOMEINSTANCIA,
  ANX.PKREGISTRO,
  U.NOMEUSU AS NOMEUPLOADER,
  U.CODPARC AS CODPARCUPLOADER
FROM TSIANX ANX WITH (NOLOCK)
LEFT JOIN TSIUSU U ON ANX.CODUSU = U.CODUSU
WHERE ANX.NOMEINSTANCIA IN (@INSTANCIAS)
  AND ANX.PKREGISTRO LIKE @PK_PATTERN
ORDER BY ANX.DHCAD DESC
`;
