/** Filter options scoped to RDO period — departamentos */
export const filtrosDepartamentos = `
SELECT DISTINCT
  dep.CODDEP as codigo,
  dep.DESCRDEP as nome,
  COUNT(DISTINCT rdo.CODPARC) as qtdColaboradores
FROM AD_RDOAPONTAMENTOS rdo
LEFT JOIN TGFPAR parc ON rdo.CODPARC = parc.CODPARC
LEFT JOIN (
  SELECT CODPARC, CODDEP,
    ROW_NUMBER() OVER (PARTITION BY CODPARC ORDER BY DTADM DESC) as rn
  FROM TFPFUN WHERE SITUACAO = '1'
) fun ON parc.CODPARC = fun.CODPARC AND fun.rn = 1
LEFT JOIN TFPDEP dep ON fun.CODDEP = dep.CODDEP
WHERE dep.CODDEP IS NOT NULL
-- @WHERE
GROUP BY dep.CODDEP, dep.DESCRDEP
ORDER BY dep.DESCRDEP
`;

/** Filter options scoped to RDO period — cargos */
export const filtrosCargos = `
SELECT DISTINCT
  car.CODCARGO as codigo,
  car.DESCRCARGO as nome
FROM AD_RDOAPONTAMENTOS rdo
LEFT JOIN TGFPAR parc ON rdo.CODPARC = parc.CODPARC
LEFT JOIN (
  SELECT CODPARC, CODCARGO,
    ROW_NUMBER() OVER (PARTITION BY CODPARC ORDER BY DTADM DESC) as rn
  FROM TFPFUN WHERE SITUACAO = '1'
) fun ON parc.CODPARC = fun.CODPARC AND fun.rn = 1
LEFT JOIN TFPCAR car ON fun.CODCARGO = car.CODCARGO
WHERE car.CODCARGO IS NOT NULL
-- @WHERE
GROUP BY car.CODCARGO, car.DESCRCARGO
ORDER BY car.DESCRCARGO
`;

/** Filter options scoped to RDO period — funcoes */
export const filtrosFuncoes = `
SELECT DISTINCT
  fnc.CODFUNCAO as codigo,
  fnc.DESCRFUNCAO as nome
FROM AD_RDOAPONTAMENTOS rdo
LEFT JOIN TGFPAR parc ON rdo.CODPARC = parc.CODPARC
LEFT JOIN (
  SELECT CODPARC, CODFUNCAO,
    ROW_NUMBER() OVER (PARTITION BY CODPARC ORDER BY DTADM DESC) as rn
  FROM TFPFUN WHERE SITUACAO = '1'
) fun ON parc.CODPARC = fun.CODPARC AND fun.rn = 1
LEFT JOIN TFPFCO fnc ON fun.CODFUNCAO = fnc.CODFUNCAO
WHERE fnc.CODFUNCAO IS NOT NULL
-- @WHERE
GROUP BY fnc.CODFUNCAO, fnc.DESCRFUNCAO
ORDER BY fnc.DESCRFUNCAO
`;

/** Filter options scoped to RDO period — empresas */
export const filtrosEmpresas = `
SELECT DISTINCT
  emp.CODEMP as codigo,
  emp.NOMEFANTASIA as nome
FROM AD_RDOAPONTAMENTOS rdo
LEFT JOIN TGFPAR parc ON rdo.CODPARC = parc.CODPARC
LEFT JOIN (
  SELECT CODPARC, CODEMP,
    ROW_NUMBER() OVER (PARTITION BY CODPARC ORDER BY DTADM DESC) as rn
  FROM TFPFUN WHERE SITUACAO = '1'
) fun ON parc.CODPARC = fun.CODPARC AND fun.rn = 1
LEFT JOIN TSIEMP emp ON fun.CODEMP = emp.CODEMP
WHERE emp.CODEMP IS NOT NULL
-- @WHERE
GROUP BY emp.CODEMP, emp.NOMEFANTASIA
ORDER BY emp.NOMEFANTASIA
`;
