export const getAlmocoPorColaborador = `
SELECT
  rdo.CODPARC as codparc,
  fho.CODCARGAHOR as codcargahor,
  DATEPART(WEEKDAY, rdo.DTREF) as diasem,
  COUNT(det.ITEM) as qtdOcorrencias,
  ISNULL(SUM(
    CASE WHEN det.HRFIM > det.HRINI AND det.HRFIM <= 2400 THEN
      ((det.HRFIM / 100) * 60 + (det.HRFIM % 100)) -
      ((det.HRINI / 100) * 60 + (det.HRINI % 100))
    ELSE 0 END
  ), 0) as totalMinutos
FROM AD_RDOAPONDETALHES det
JOIN AD_RDOAPONTAMENTOS rdo ON det.CODRDO = rdo.CODRDO
JOIN TGFPAR parc ON rdo.CODPARC = parc.CODPARC
LEFT JOIN (
  SELECT CODPARC, CODEMP, CODFUNC, CODDEP, CODCARGO, CODFUNCAO,
    ROW_NUMBER() OVER (PARTITION BY CODPARC ORDER BY DTADM DESC) as rn
  FROM TFPFUN WHERE SITUACAO = '1'
) fun ON parc.CODPARC = fun.CODPARC AND fun.rn = 1
LEFT JOIN (
  SELECT CODEMP, CODFUNC, CODCARGAHOR,
    ROW_NUMBER() OVER (PARTITION BY CODEMP, CODFUNC ORDER BY DTINIESCALA DESC) as rn
  FROM TFPFHO
) fho ON fun.CODEMP = fho.CODEMP AND fun.CODFUNC = fho.CODFUNC AND fho.rn = 1
WHERE det.RDOMOTIVOCOD = 3
-- @WHERE
GROUP BY rdo.CODPARC, fho.CODCARGAHOR, DATEPART(WEEKDAY, rdo.DTREF)
`;
