export const listar = `
SELECT * FROM (
  SELECT
    rdo.CODRDO,
    rdo.CODPARC,
    CONVERT(VARCHAR(10), rdo.DTREF, 23) as DTREF,
    parc.NOMEPARC as nomeparc,
    dep.DESCRDEP as departamento,
    car.DESCRCARGO as cargo,
    (
      SELECT COUNT(*)
      FROM AD_RDOAPONDETALHES d
      WHERE d.CODRDO = rdo.CODRDO
    ) as totalItens,
    (
      SELECT ISNULL(SUM(CASE WHEN d.HRFIM > d.HRINI AND d.HRFIM <= 2400 THEN
        ((d.HRFIM / 100) * 60 + (d.HRFIM % 100)) -
        ((d.HRINI / 100) * 60 + (d.HRINI % 100))
      ELSE 0 END), 0)
      FROM AD_RDOAPONDETALHES d
      WHERE d.CODRDO = rdo.CODRDO
    ) as totalMinutos,
    (
      SELECT CAST(ISNULL(SUM(CASE WHEN d.HRFIM > d.HRINI AND d.HRFIM <= 2400 THEN
        ((d.HRFIM / 100) * 60 + (d.HRFIM % 100)) -
        ((d.HRINI / 100) * 60 + (d.HRINI % 100))
      ELSE 0 END) / 60.0, 0) AS DECIMAL(10,2))
      FROM AD_RDOAPONDETALHES d
      WHERE d.CODRDO = rdo.CODRDO
    ) as totalHoras,
    (
      SELECT TOP 1
        RIGHT('0' + CAST(d2.HRINI / 100 AS VARCHAR), 2) + ':' + RIGHT('0' + CAST(d2.HRINI % 100 AS VARCHAR), 2)
      FROM AD_RDOAPONDETALHES d2
      WHERE d2.CODRDO = rdo.CODRDO
      ORDER BY d2.ITEM ASC
    ) as primeiraHora,
    (
      SELECT TOP 1
        RIGHT('0' + CAST(d2.HRFIM / 100 AS VARCHAR), 2) + ':' + RIGHT('0' + CAST(d2.HRFIM % 100 AS VARCHAR), 2)
      FROM AD_RDOAPONDETALHES d2
      WHERE d2.CODRDO = rdo.CODRDO
      ORDER BY d2.ITEM DESC
    ) as ultimaHora,
    (
      SELECT COUNT(DISTINCT d2.NUOS)
      FROM AD_RDOAPONDETALHES d2
      WHERE d2.CODRDO = rdo.CODRDO AND d2.NUOS IS NOT NULL
    ) as qtdOs,
    (
      SELECT TOP 1 d2.NUOS
      FROM AD_RDOAPONDETALHES d2
      WHERE d2.CODRDO = rdo.CODRDO AND d2.NUOS IS NOT NULL
      ORDER BY d2.ITEM ASC
    ) as primeiroNuos,
    (
      SELECT TOP 1 os.STATUS
      FROM AD_RDOAPONDETALHES d2
      INNER JOIN TCFOSCAB os ON d2.NUOS = os.NUOS
      WHERE d2.CODRDO = rdo.CODRDO AND d2.NUOS IS NOT NULL
    ) as osStatus,
    (
      SELECT TOP 1 os.MANUTENCAO
      FROM AD_RDOAPONDETALHES d2
      INNER JOIN TCFOSCAB os ON d2.NUOS = os.NUOS
      WHERE d2.CODRDO = rdo.CODRDO AND d2.NUOS IS NOT NULL
    ) as osManutencao,
    (
      SELECT TOP 1 os.AD_STATUSGIG
      FROM AD_RDOAPONDETALHES d2
      INNER JOIN TCFOSCAB os ON d2.NUOS = os.NUOS
      WHERE d2.CODRDO = rdo.CODRDO AND d2.NUOS IS NOT NULL
    ) as osStatusGig,
    (
      SELECT TOP 1 CONVERT(VARCHAR(10), os.DATAINI, 23)
      FROM AD_RDOAPONDETALHES d2
      INNER JOIN TCFOSCAB os ON d2.NUOS = os.NUOS
      WHERE d2.CODRDO = rdo.CODRDO AND d2.NUOS IS NOT NULL
    ) as osDataIni,
    (
      SELECT TOP 1 CONVERT(VARCHAR(10), os.PREVISAO, 23)
      FROM AD_RDOAPONDETALHES d2
      INNER JOIN TCFOSCAB os ON d2.NUOS = os.NUOS
      WHERE d2.CODRDO = rdo.CODRDO AND d2.NUOS IS NOT NULL
    ) as osPrevisao,
    (
      SELECT TOP 1
        (SELECT COUNT(*) FROM TCFSERVOS s WHERE s.NUOS = os.NUOS)
      FROM AD_RDOAPONDETALHES d2
      INNER JOIN TCFOSCAB os ON d2.NUOS = os.NUOS
      WHERE d2.CODRDO = rdo.CODRDO AND d2.NUOS IS NOT NULL
    ) as osQtdServicos,
    (
      SELECT TOP 1 v.PLACA
      FROM AD_RDOAPONDETALHES d2
      INNER JOIN TCFOSCAB os ON d2.NUOS = os.NUOS
      INNER JOIN TGFVEI v ON os.CODVEICULO = v.CODVEICULO
      WHERE d2.CODRDO = rdo.CODRDO AND d2.NUOS IS NOT NULL
    ) as veiculoPlaca,
    (
      SELECT TOP 1 v.AD_TAG
      FROM AD_RDOAPONDETALHES d2
      INNER JOIN TCFOSCAB os ON d2.NUOS = os.NUOS
      INNER JOIN TGFVEI v ON os.CODVEICULO = v.CODVEICULO
      WHERE d2.CODRDO = rdo.CODRDO AND d2.NUOS IS NOT NULL
    ) as veiculoTag,
    (
      SELECT TOP 1 v.MARCAMODELO
      FROM AD_RDOAPONDETALHES d2
      INNER JOIN TCFOSCAB os ON d2.NUOS = os.NUOS
      INNER JOIN TGFVEI v ON os.CODVEICULO = v.CODVEICULO
      WHERE d2.CODRDO = rdo.CODRDO AND d2.NUOS IS NOT NULL
    ) as veiculoModelo,
    fun.CODCARGAHOR as codcargahor,
    ROW_NUMBER() OVER (ORDER BY -- @ORDER
    ) AS RowNum
  FROM AD_RDOAPONTAMENTOS rdo
  LEFT JOIN TGFPAR parc ON rdo.CODPARC = parc.CODPARC
  LEFT JOIN (
    SELECT f2.CODPARC, f2.CODDEP, f2.CODCARGO, f2.CODFUNCAO, f2.CODEMP,
      (SELECT TOP 1 fho.CODCARGAHOR FROM TFPFHO fho
       WHERE fho.CODEMP = f2.CODEMP AND fho.CODFUNC = f2.CODFUNC
       ORDER BY fho.DTINIESCALA DESC) AS CODCARGAHOR,
      ROW_NUMBER() OVER (PARTITION BY f2.CODPARC ORDER BY f2.DTADM DESC) as rn
    FROM TFPFUN f2 WHERE f2.SITUACAO = '1'
  ) fun ON parc.CODPARC = fun.CODPARC AND fun.rn = 1
  LEFT JOIN TFPDEP dep ON fun.CODDEP = dep.CODDEP
  LEFT JOIN TFPCAR car ON fun.CODCARGO = car.CODCARGO
  WHERE 1=1
  -- @WHERE
) AS T
WHERE RowNum > @OFFSET AND RowNum <= (@OFFSET + @LIMIT)
`;
