export interface OsComercial {
  NUMOS: number;
  NUMCONTRATO: number | null;
  CODPARC: number;
  CODCONTATO: number | null;
  CONTATO: string | null;
  NOMECONTATO: string | null;
  TELCONTATO: string | null;
  CODPARCATEND: number | null;
  SITUACAO: string;
  DHCHAMADA: Date;
  DTPREVISTA: Date | null;
  DTFECHAMENTO: Date | null;
  DHFECHAMENTOSLA: Date | null;
  CODATEND: number | null;
  CODUSURESP: number;
  CODUSUFECH: number | null;
  CODUSUALTER: number | null;
  CODUSUSOLICITANTE: number | null;
  CODVEND: number | null;
  TEMPPREVISTO: number | null;
  TEMPGASTO: number | null;
  TEMPOGASTOSLA: number | null;
  TEMPOSLA: number | null;
  POSSUISLA: string | null;
  DESCRICAO: string | null;
  TIPO: string | null;
  IDENTIFICADOR: string | null;
  ENDERECO: string | null;
  COMPLEMENTO: string | null;
  BAIRRO: string | null;
  CIDADE: string | null;
  CODBEM: string | null;
  SERIE: string | null;
  NUFAP: number | null;
  NUMETAPA: number | null;
  NUMOSCLIENTE: string | null;
  CODCOS: number | null;
  CODCOSANT: number | null;
  CODCENCUS: number | null;
  CODSERVFLUXO: number | null;
  VARIACAOFLUXO: number | null;
  CODTPN: number | null;
  CODOAT: number | null;
  CODPLA: number | null;
  NOMEMODELO: string | null;
  MODELOVISIVELAPPOS: string | null;
  CODPROCMAHA: number | null;
  IMPACTO: string | null;
  URGENCIA: string | null;
  AD_EXIBEDASH: string | null;
  DTALTER: Date | null;
}
