export const feriasAtuais = `
SELECT
  FER.CODEMP AS codemp,
  FER.CODFUNC AS codfunc,
  FUN.CODPARC AS codparc,
  FUN.NOMEFUNC AS nomeFuncionario,
  EMP.NOMEFANTASIA AS nomeEmpresa,
  CONVERT(VARCHAR(10), FER.DTSAIDA, 120) AS dtSaida,
  FER.NUMDIASFER AS numDiasFer,
  DATEADD(day, FER.NUMDIASFER, FER.DTSAIDA) AS dtRetorno,
  ISNULL(FER.ABONOPEC, 0) AS abonoPec,
  ISNULL(FER.APROVADO, 'N') AS aprovado,
  CONVERT(VARCHAR(10), FER.DTPREVISTA, 120) AS dtPrevista,
  DEP.DESCRCENCUS AS departamento,
  CAR.DESCRCARGO AS cargo
FROM TFPFER FER
JOIN TFPFUN FUN ON FUN.CODFUNC = FER.CODFUNC AND FUN.CODEMP = FER.CODEMP
JOIN TSIEMP EMP ON EMP.CODEMP = FER.CODEMP
LEFT JOIN TSICUS DEP ON DEP.CODCENCUS = FUN.CODDEP
LEFT JOIN TFPCAR CAR ON CAR.CODCARGO = FUN.CODCARGO
WHERE FER.DTSAIDA <= GETDATE()
  AND DATEADD(day, FER.NUMDIASFER, FER.DTSAIDA) >= GETDATE()
ORDER BY FER.DTSAIDA DESC
`;

export const feriasProximas = `
SELECT
  FER.CODEMP AS codemp,
  FER.CODFUNC AS codfunc,
  FUN.CODPARC AS codparc,
  FUN.NOMEFUNC AS nomeFuncionario,
  EMP.NOMEFANTASIA AS nomeEmpresa,
  CONVERT(VARCHAR(10), FER.DTSAIDA, 120) AS dtSaida,
  FER.NUMDIASFER AS numDiasFer,
  DATEADD(day, FER.NUMDIASFER, FER.DTSAIDA) AS dtRetorno,
  ISNULL(FER.ABONOPEC, 0) AS abonoPec,
  ISNULL(FER.APROVADO, 'N') AS aprovado,
  CONVERT(VARCHAR(10), FER.DTPREVISTA, 120) AS dtPrevista,
  DEP.DESCRCENCUS AS departamento,
  CAR.DESCRCARGO AS cargo
FROM TFPFER FER
JOIN TFPFUN FUN ON FUN.CODFUNC = FER.CODFUNC AND FUN.CODEMP = FER.CODEMP
JOIN TSIEMP EMP ON EMP.CODEMP = FER.CODEMP
LEFT JOIN TSICUS DEP ON DEP.CODCENCUS = FUN.CODDEP
LEFT JOIN TFPCAR CAR ON CAR.CODCARGO = FUN.CODCARGO
WHERE FER.DTSAIDA > GETDATE()
  AND FER.DTSAIDA <= DATEADD(day, @dias, GETDATE())
ORDER BY FER.DTSAIDA ASC
`;

export const resumoFerias = `
SELECT
  (SELECT COUNT(*) FROM TFPFER
   WHERE DTSAIDA <= GETDATE() AND DATEADD(day, NUMDIASFER, DTSAIDA) >= GETDATE()
  ) AS emFeriasAgora,
  (SELECT COUNT(*) FROM TFPFER
   WHERE DTSAIDA > GETDATE() AND DTSAIDA <= DATEADD(day, 30, GETDATE())
  ) AS programadas
`;

export const solicitacoesFeriasPendentes = `
SELECT COUNT(*) AS pendentes
FROM TFPSFE
WHERE STATUS = 'P'
`;
