export const historicoKmPorVeiculo = `
SELECT
  CODVEICULO,
  SEQUENCIA,
  KM,
  ORIGEM,
  CODUSU,
  DHALTER,
  DHREFERENCIA,
  AD_HORIMETRO,
  AD_ODOMETRO
FROM SANKHYA.TMSVEIHKM
WHERE CODVEICULO = @codveiculo
ORDER BY DHREFERENCIA DESC
`;
